package authtest

import (
	"crypto"
	"crypto/ecdsa"
	"crypto/ed25519"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/rsa"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"maps"

	"github.com/picatz/jose/pkg/jwa"
	"github.com/picatz/jose/pkg/jwk"
)

// rsaKeyBits is the modulus size of every RSA key generated here.
//
// 2048 is the smallest size RFC 7518 permits for RS256, which is what this
// wants: a test double should be generating the cheapest key its verifier will
// accept, and a larger one would only make every test that uses one slower.
const rsaKeyBits = 2048

// Key is a signing key an [Issuer] publishes and mints tokens with.
//
// A key is generated by [GenerateKey] and is usable only in this process: the
// private half never leaves it, and the public half is published only by the
// [Issuer] that holds the key.
//
// The zero value is not usable.
type Key struct {
	id        string
	algorithm jwa.Algorithm
	private   crypto.PrivateKey
	public    crypto.PublicKey

	publishedAlgorithm jwa.Algorithm // "alg" in the published JWK; empty to omit
	publishedUse       string        // "use" in the published JWK; empty to omit
}

// KeyOption changes how a key is published in an issuer's key set. It does not
// change the key itself.
type KeyOption func(*Key)

// PublishAlgorithm publishes an "alg" parameter in the key's JWK, declaring the
// one algorithm the key may be used with.
//
// Passing the key's own algorithm models an issuer that is specific about what
// its keys are for. Passing a different one models an issuer whose published
// metadata disagrees with what it signs, which a relying party has to refuse
// rather than resolve in the token's favour.
func PublishAlgorithm(algorithm jwa.Algorithm) KeyOption {
	return func(k *Key) { k.publishedAlgorithm = algorithm }
}

// PublishUse publishes a "use" parameter in the key's JWK, such as "sig" for a
// key published for signatures.
//
// A key set is otherwise published without one, since the parameter is optional
// and many providers omit it.
func PublishUse(use string) KeyOption {
	return func(k *Key) { k.publishedUse = use }
}

// GenerateKey returns a new signing key for the given algorithm, published in a
// key set under the given key id.
//
// An empty id publishes a key with no "kid", which is what a provider that has
// only ever had one key looks like. A token signed by such a key carries no key
// id either, so a relying party has to find the key some other way.
//
// The supported algorithms are the asymmetric ones a token can plausibly be
// signed with: RS256, RS384, RS512, PS256, PS384, PS512, ES256, ES384, ES512
// and EdDSA. Any other name panics, including the symmetric ones and "none",
// which no issuer's key set can legitimately contain. To present a token signed
// with one of those, build it in the test that is proving it is refused; that
// is an attacker's token rather than an issuer's.
//
// RSA keys take noticeably longer to generate than the rest. Prefer ES256
// unless the test is about RSA.
func GenerateKey(id string, algorithm jwa.Algorithm, options ...KeyOption) *Key {
	key := &Key{id: id, algorithm: algorithm}

	switch algorithm {
	case jwa.RS256, jwa.RS384, jwa.RS512, jwa.PS256, jwa.PS384, jwa.PS512:
		private, err := rsa.GenerateKey(rand.Reader, rsaKeyBits)
		if err != nil {
			panic(fmt.Sprintf("authtest: generating an RSA key: %v", err))
		}
		key.private, key.public = private, &private.PublicKey
	case jwa.ES256, jwa.ES384, jwa.ES512:
		private, err := ecdsa.GenerateKey(curveFor(algorithm), rand.Reader)
		if err != nil {
			panic(fmt.Sprintf("authtest: generating an ECDSA key: %v", err))
		}
		key.private, key.public = private, &private.PublicKey
	case jwa.EdDSA:
		public, private, err := ed25519.GenerateKey(rand.Reader)
		if err != nil {
			panic(fmt.Sprintf("authtest: generating an Ed25519 key: %v", err))
		}
		key.private, key.public = private, public
	default:
		panic(fmt.Sprintf("authtest: no key can be generated for algorithm %q", algorithm))
	}

	for _, option := range options {
		option(key)
	}

	return key
}

// ID returns the key id this key is published and signs under, which is empty
// for a key published without one.
func (k *Key) ID() string { return k.id }

// Algorithm returns the algorithm this key signs with.
func (k *Key) Algorithm() jwa.Algorithm { return k.algorithm }

// Public returns the public half of the key, which is what a relying party
// would obtain from the issuer's key set.
func (k *Key) Public() crypto.PublicKey { return k.public }

// JWK returns the JSON Web Key an issuer publishes for this key, including
// whatever [PublishAlgorithm] and [PublishUse] asked for.
//
// The result is a fresh map, so a test may alter it to publish something
// malformed without disturbing the key.
func (k *Key) JWK() map[string]any {
	value, err := jwk.ValueFromPublicKey(k.public)
	if err != nil {
		panic(fmt.Sprintf("authtest: publishing a %s key: %v", k.algorithm, err))
	}

	published := make(map[string]any, len(value)+2)
	maps.Copy(published, value)

	// "use" is only published when a test asked for it. Some providers publish
	// it, some do not, and a double that always did would make the omission
	// untestable.
	delete(published, jwk.PublicKeyUse)

	if k.id != "" {
		published[jwk.KeyID] = k.id
	}
	if k.publishedAlgorithm != "" {
		published[jwk.Algorithm] = k.publishedAlgorithm
	}
	if k.publishedUse != "" {
		published[jwk.PublicKeyUse] = k.publishedUse
	}

	return published
}

// Sign returns a signed token with exactly the given JOSE header and claims,
// with nothing filled in and nothing checked.
//
// This is the way to present a token whose header disagrees with the key that
// signed it, or that carries a header parameter a relying party must refuse. It
// is deliberately lower level than [Issuer.MintToken]: no standard claim is
// added, no audience is required, and the header is whatever the map says,
// including a "kid" that is not a string or an "alg" that names something this
// key cannot do.
//
// The signature is always produced with the key's own algorithm, since that is
// the only one it can produce. Naming another in the header is how a token that
// lies about how it was signed is built.
func (k *Key) Sign(headers map[string]any, claims map[string]any) string {
	signingInput := encodeSegment(headers) + "." + encodeSegment(claims)

	signature, err := k.sign([]byte(signingInput))
	if err != nil {
		panic(fmt.Sprintf("authtest: signing with a %s key: %v", k.algorithm, err))
	}

	return signingInput + "." + base64.RawURLEncoding.EncodeToString(signature)
}

// sign returns the JWS signature over the signing input.
func (k *Key) sign(signingInput []byte) ([]byte, error) {
	hash := hashFor(k.algorithm)

	var digest []byte
	if hash != 0 {
		sum := hash.New()
		sum.Write(signingInput)
		digest = sum.Sum(nil)
	}

	switch private := k.private.(type) {
	case *rsa.PrivateKey:
		switch k.algorithm {
		case jwa.PS256, jwa.PS384, jwa.PS512:
			// RFC 7518 section 3.5 fixes the salt length at the hash length.
			return rsa.SignPSS(rand.Reader, private, hash, digest, &rsa.PSSOptions{
				SaltLength: rsa.PSSSaltLengthEqualsHash,
				Hash:       hash,
			})
		default:
			return rsa.SignPKCS1v15(rand.Reader, private, hash, digest)
		}
	case *ecdsa.PrivateKey:
		// JWS carries an ECDSA signature as the fixed-width concatenation of r
		// and s, not as the ASN.1 sequence crypto/ecdsa returns by default, and
		// the width is the curve's rather than the signature's: a coordinate
		// with leading zero bytes still occupies its full width.
		r, s, err := ecdsa.Sign(rand.Reader, private, digest)
		if err != nil {
			return nil, err
		}

		width := (private.Curve.Params().BitSize + 7) / 8

		signature := make([]byte, 2*width)
		r.FillBytes(signature[:width])
		s.FillBytes(signature[width:])

		return signature, nil
	case ed25519.PrivateKey:
		// Ed25519 hashes internally, so it signs the input rather than a digest.
		return ed25519.Sign(private, signingInput), nil
	default:
		return nil, fmt.Errorf("no signer for key type %T", k.private)
	}
}

// curveFor returns the curve RFC 7518 pairs with an ECDSA algorithm.
func curveFor(algorithm jwa.Algorithm) elliptic.Curve {
	switch algorithm {
	case jwa.ES256:
		return elliptic.P256()
	case jwa.ES384:
		return elliptic.P384()
	case jwa.ES512:
		return elliptic.P521()
	default:
		panic(fmt.Sprintf("authtest: no curve for algorithm %q", algorithm))
	}
}

// hashFor returns the hash RFC 7518 pairs with an algorithm, or zero for EdDSA,
// which hashes the message itself.
func hashFor(algorithm jwa.Algorithm) crypto.Hash {
	switch algorithm {
	case jwa.RS256, jwa.PS256, jwa.ES256:
		return crypto.SHA256
	case jwa.RS384, jwa.PS384, jwa.ES384:
		return crypto.SHA384
	case jwa.RS512, jwa.PS512, jwa.ES512:
		return crypto.SHA512
	case jwa.EdDSA:
		return 0
	default:
		panic(fmt.Sprintf("authtest: no hash for algorithm %q", algorithm))
	}
}

// encodeSegment returns the base64url encoding of a JOSE segment, with no
// padding, which is what JWS compact serialization requires.
func encodeSegment(value map[string]any) string {
	encoded, err := json.Marshal(value)
	if err != nil {
		panic(fmt.Sprintf("authtest: encoding a token segment: %v", err))
	}

	return base64.RawURLEncoding.EncodeToString(encoded)
}
