// Command operationregistry verifies and generates the privileged-operation registry.
package main

import (
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"os"
	"regexp"
	"sort"
	"strings"
)

type manifest struct {
	SchemaVersion int         `json:"schema_version"`
	Operations    []operation `json:"operations"`
}
type operation struct {
	Operation   string   `json:"operation"`
	Action      string   `json:"action"`
	Resource    string   `json:"resource_constructor"`
	Enforcement string   `json:"enforcement_point"`
	Audit       string   `json:"audit_event"`
	Surfaces    []string `json:"surfaces"`
	Status      string   `json:"status"`
}

func main() {
	generate := flag.Bool("generate", false, "generate documentation and policy vocabulary")
	flag.Parse()
	b, err := os.ReadFile("security/operations/registry.json")
	if err != nil {
		fail(err)
	}
	var m manifest
	if err = json.Unmarshal(b, &m); err != nil {
		fail(err)
	}
	if err = verify(m); err != nil {
		fail(err)
	}
	if *generate {
		if err = writeGenerated(m); err != nil {
			fail(err)
		}
	}
}
func fail(err error) { fmt.Fprintln(os.Stderr, "operation registry:", err); os.Exit(1) }
func verify(m manifest) error {
	var problems []string
	seen, actionBySurface := map[string]bool{}, map[string]string{}
	for _, o := range m.Operations {
		if o.Operation == "" || seen[o.Operation] {
			problems = append(problems, "missing or duplicate operation: "+o.Operation)
		}
		seen[o.Operation] = true
		if o.Action == "" {
			problems = append(problems, o.Operation+": no authorization action")
		}
		if o.Resource == "" {
			problems = append(problems, o.Operation+": no resource constructor")
		}
		if o.Enforcement == "" {
			problems = append(problems, o.Operation+": no enforcement point")
		}
		if o.Audit == "" {
			problems = append(problems, o.Operation+": no decision/audit instrumentation")
		}
		if len(o.Surfaces) == 0 {
			problems = append(problems, o.Operation+": no serving surface")
		}
		if o.Status != "active" && o.Status != "deprecated" {
			problems = append(problems, o.Operation+": invalid status")
		}
		for _, s := range o.Surfaces {
			k := s + "\x00" + o.Operation
			if old, ok := actionBySurface[k]; ok && old != o.Action {
				problems = append(problems, o.Operation+": inconsistent actions across "+s)
			}
			actionBySurface[k] = o.Action
		}
	}
	proto, err := readRepoFile("proto/flowstate/v1/service.proto")
	if err != nil {
		return err
	}
	re := regexp.MustCompile(`(?m)^  rpc ([A-Za-z0-9_]+)\(`)
	for _, match := range re.FindAllStringSubmatch(string(proto), -1) {
		id := "flowstate.v1.WorkflowService/" + match[1]
		if !seen[id] {
			problems = append(problems, id+": RPC has no registered authorization action (reachable RPCs, including deprecated RPCs, must remain in the manifest)")
		}
	}
	// MCP projects every WorkflowService descriptor. Requiring the MCP surface here
	// proves its dispatch cannot outrun the principal-preserving RPC entry.
	for _, o := range m.Operations {
		if strings.HasPrefix(o.Operation, "flowstate.v1.WorkflowService/") && !contains(o.Surfaces, "mcp") {
			problems = append(problems, o.Operation+": MCP projection has no principal-preserving authorization path")
		}
	}
	if len(problems) > 0 {
		sort.Strings(problems)
		return errors.New(strings.Join(problems, "\n"))
	}
	return nil
}

func readRepoFile(name string) ([]byte, error) {
	dir, err := os.Getwd()
	if err != nil {
		return nil, err
	}
	for {
		path := dir + string(os.PathSeparator) + name
		if b, readErr := os.ReadFile(path); readErr == nil {
			return b, nil
		}
		parent := dir[:strings.LastIndex(dir, string(os.PathSeparator))]
		if parent == "" || parent == dir {
			return nil, fmt.Errorf("cannot find repository file %s", name)
		}
		dir = parent
	}
}

func contains(xs []string, w string) bool {
	for _, x := range xs {
		if x == w {
			return true
		}
	}
	return false
}
func writeGenerated(m manifest) error {
	sort.Slice(m.Operations, func(i, j int) bool { return m.Operations[i].Operation < m.Operations[j].Operation })
	var d strings.Builder
	d.WriteString("<!-- Generated by go run ./tools/operationregistry -generate; do not edit. -->\n# Privileged operation registry\n\n| Operation | Action | Resource constructor | Enforcement | Audit event | Surfaces | Status |\n|---|---|---|---|---|---|---|\n")
	actions := map[string]bool{}
	for _, o := range m.Operations {
		fmt.Fprintf(&d, "| `%s` | `%s` | `%s` | `%s` | `%s` | %s | %s |\n", o.Operation, o.Action, o.Resource, o.Enforcement, o.Audit, strings.Join(o.Surfaces, ", "), o.Status)
		actions[o.Action] = true
	}
	if err := os.WriteFile("docs/reference/privileged-operations.md", []byte(d.String()), 0644); err != nil {
		return err
	}
	vocab := struct {
		SchemaVersion int      `json:"schema_version"`
		Actions       []string `json:"actions"`
	}{1, make([]string, 0, len(actions))}
	for a := range actions {
		vocab.Actions = append(vocab.Actions, a)
	}
	sort.Strings(vocab.Actions)
	b, _ := json.MarshalIndent(vocab, "", "  ")
	return os.WriteFile("security/operations/policy-vocabulary.json", append(b, '\n'), 0644)
}
