// Command protoc-gen-flowstate-ts generates TypeScript declarations for the
// JSON a schema's messages travel as.
//
// Flowstate's CLI answers in the proto3 JSON mapping (`flow validate -o
// jsonl`, `flow list -o jsonl`, the RPC surface), so a program reading those
// answers, such as the Claude Code mod in editors/claude-code, needs types for
// exactly that shape. Writing them by hand makes a second spelling of the
// schema that drifts the first time a field is added. This plugin derives them
// from the schema in the same `buf generate` run as the Go types, so the
// existing drift check holds them and a schema change shows up as a diff in
// the declarations.
//
// Run it next to the Go plugins and name the messages that are the entry
// points; everything they reach comes with them:
//
//	plugins:
//	  - local: [go, tool, protoc-gen-flowstate-ts]
//	    out: editors/claude-code/types
//	    strategy: all
//	    opt:
//	      - file=flowstate.d.ts
//	      - message=flowstate.v1.DiagnosticReport
//
// # The shape it declares
//
// The proto3 JSON mapping with every field populated, which is how the CLI
// renders (EmitUnpopulated): a scalar, list or map field is always present
// and holds its zero value rather than being omitted, a message field is
// `null` when unset, and field names are the lowerCamelCase JSON names. 64-bit
// integers are strings, bytes are base64 strings, enums are their value
// names, and Timestamp and Duration are their string forms. A oneof member or
// proto3 `optional` field may be absent. Leading comments in the .proto become
// TSDoc, so an editor shows the schema's own prose.
//
// A message type outside the supported well-known set is an error rather than
// an `unknown` that quietly stops checking anything.
//
// The plugin is built on protogen alone, so it adds nothing to the module
// graph beyond google.golang.org/protobuf.
package main

import (
	"errors"
	"flag"
	"fmt"
	"slices"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/types/descriptorpb"
	"google.golang.org/protobuf/types/pluginpb"
)

func main() {
	opts, run := plugin()
	opts.Run(run)
}

// plugin returns the generator's options and the function protogen runs over
// each request with them. main and the tests share it, so a test drives the
// same path protoc does.
func plugin() (protogen.Options, func(*protogen.Plugin) error) {
	var (
		flags    flag.FlagSet
		file     = flags.String("file", "flowstate.d.ts", "name of the generated file")
		messages []string
	)
	flags.Func("message", "full name of an entry-point message; repeatable", func(name string) error {
		messages = append(messages, name)
		return nil
	})
	return protogen.Options{ParamFunc: flags.Set}, func(gen *protogen.Plugin) error {
		gen.SupportedFeatures = uint64(pluginpb.CodeGeneratorResponse_FEATURE_PROTO3_OPTIONAL |
			pluginpb.CodeGeneratorResponse_FEATURE_SUPPORTS_EDITIONS)
		gen.SupportedEditionsMinimum = descriptorpb.Edition_EDITION_PROTO2
		gen.SupportedEditionsMaximum = descriptorpb.Edition_EDITION_2024
		return generate(gen, *file, messages)
	}
}

// generate writes one declaration file holding the named messages and every
// type they reach.
func generate(gen *protogen.Plugin, filename string, entries []string) error {
	if len(entries) == 0 {
		return errors.New("no message= option: name at least one entry-point message")
	}
	if !strings.HasSuffix(filename, ".d.ts") {
		return fmt.Errorf("file=%s: a declaration file ends in .d.ts", filename)
	}

	c := &collector{
		messages: make(map[protoreflect.FullName]*protogen.Message),
		enums:    make(map[protoreflect.FullName]*protogen.Enum),
		names:    make(map[string]protoreflect.FullName),
	}
	byName := make(map[protoreflect.FullName]*protogen.Message)
	for _, f := range gen.Files {
		for _, m := range allMessages(f.Messages) {
			byName[m.Desc.FullName()] = m
		}
	}
	for _, name := range entries {
		m, ok := byName[protoreflect.FullName(name)]
		if !ok {
			return fmt.Errorf("message=%s: no such message in the files given", name)
		}
		if err := c.addMessage(m); err != nil {
			return err
		}
	}

	g := gen.NewGeneratedFile(filename, "")
	g.P("// Code generated by protoc-gen-flowstate-ts. DO NOT EDIT.")
	g.P("//")
	g.P("// The proto3 JSON shape the flow CLI and the RPC surface answer in, with every")
	g.P("// field populated: a message field is null when unset, a 64-bit integer is a")
	g.P("// string, and an enum is its value name. Derived from the schema; change the")
	g.P("// .proto and run `buf generate`.")
	for _, name := range sortedKeys(c.enums) {
		g.P()
		c.writeEnum(g, c.enums[name])
	}
	for _, name := range sortedKeys(c.messages) {
		g.P()
		if err := c.writeMessage(g, c.messages[name]); err != nil {
			return err
		}
	}
	return nil
}

// allMessages returns messages and every message nested in them.
func allMessages(top []*protogen.Message) []*protogen.Message {
	var out []*protogen.Message
	for _, m := range top {
		out = append(out, m)
		out = append(out, allMessages(m.Messages)...)
	}
	return out
}

func sortedKeys[V any](m map[protoreflect.FullName]V) []protoreflect.FullName {
	keys := make([]protoreflect.FullName, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	slices.Sort(keys)
	return keys
}

// collector gathers the closure of types reachable from the entry points.
type collector struct {
	messages map[protoreflect.FullName]*protogen.Message
	enums    map[protoreflect.FullName]*protogen.Enum
	// names maps a TypeScript name back to the declaration that claimed it, so
	// two packages' same-named messages are an error and not one silently
	// replacing the other.
	names map[string]protoreflect.FullName
}

func (c *collector) claim(name string, full protoreflect.FullName) error {
	if other, taken := c.names[name]; taken && other != full {
		return fmt.Errorf("%s and %s would both be declared as %s", other, full, name)
	}
	c.names[name] = full
	return nil
}

func (c *collector) addMessage(m *protogen.Message) error {
	if _, done := c.messages[m.Desc.FullName()]; done || wellKnown(m.Desc) != "" {
		return nil
	}
	if err := c.claim(tsName(m.Desc), m.Desc.FullName()); err != nil {
		return err
	}
	c.messages[m.Desc.FullName()] = m
	for _, f := range m.Fields {
		if err := c.addField(f); err != nil {
			return err
		}
	}
	return nil
}

func (c *collector) addField(f *protogen.Field) error {
	switch {
	case f.Desc.IsMap():
		return c.addField(f.Message.Fields[1])
	case f.Enum != nil:
		if _, done := c.enums[f.Enum.Desc.FullName()]; !done {
			if err := c.claim(tsName(f.Enum.Desc), f.Enum.Desc.FullName()); err != nil {
				return err
			}
			c.enums[f.Enum.Desc.FullName()] = f.Enum
		}
	case f.Message != nil:
		if wellKnown(f.Message.Desc) == "" {
			return c.addMessage(f.Message)
		}
	}
	return nil
}

// tsName is a declaration's TypeScript name: its name within the package, with
// nesting joined by underscores (Parent.Child becomes Parent_Child).
func tsName(d protoreflect.Descriptor) string {
	name := string(d.FullName())
	if pkg := string(d.ParentFile().Package()); pkg != "" {
		name = strings.TrimPrefix(name, pkg+".")
	}
	return strings.ReplaceAll(name, ".", "_")
}

// wellKnown returns the TypeScript type a well-known message travels as in
// JSON, or "" when m is not one. The ones the schema does not use are an
// error at the field, not here.
func wellKnown(m protoreflect.MessageDescriptor) string {
	if m.ParentFile().Package() != "google.protobuf" {
		return ""
	}
	switch m.Name() {
	case "Timestamp", "Duration", "FieldMask", "StringValue", "BytesValue", "Int64Value", "UInt64Value":
		return "string"
	case "BoolValue":
		return "boolean"
	case "Int32Value", "UInt32Value", "FloatValue", "DoubleValue":
		return "number"
	case "Struct":
		return "{ [key: string]: unknown }"
	case "Value":
		return "unknown"
	case "ListValue":
		return "unknown[]"
	case "Empty":
		return "Record<string, never>"
	}
	return ""
}

func (c *collector) writeEnum(g *protogen.GeneratedFile, e *protogen.Enum) {
	writeDoc(g, "", e.Comments.Leading)
	values := make([]string, 0, len(e.Values))
	for _, v := range e.Values {
		values = append(values, `"`+string(v.Desc.Name())+`"`)
	}
	g.P("export type ", tsName(e.Desc), " = ", strings.Join(values, " | "))
}

func (c *collector) writeMessage(g *protogen.GeneratedFile, m *protogen.Message) error {
	writeDoc(g, "", m.Comments.Leading)
	g.P("export interface ", tsName(m.Desc), " {")
	for _, f := range m.Fields {
		typ, err := fieldType(f)
		if err != nil {
			return fmt.Errorf("%s: %w", f.Desc.FullName(), err)
		}
		writeDoc(g, "  ", f.Comments.Leading)
		optional := ""
		switch {
		case f.Desc.ContainingOneof() != nil && !f.Desc.ContainingOneof().IsSynthetic(), f.Desc.HasOptionalKeyword():
			optional = "?"
		case f.Message != nil && !f.Desc.IsList() && !f.Desc.IsMap():
			optional, typ = "?", typ+" | null"
		}
		g.P("  ", f.Desc.JSONName(), optional, ": ", typ)
	}
	g.P("}")
	return nil
}

// fieldType is the TypeScript type of a field's JSON value.
func fieldType(f *protogen.Field) (string, error) {
	if f.Desc.IsMap() {
		key := f.Message.Fields[0]
		if key.Desc.Kind() == protoreflect.BoolKind {
			return "", errors.New("a map keyed by bool is not supported")
		}
		val, err := singular(f.Message.Fields[1])
		if err != nil {
			return "", err
		}
		return "{ [key: string]: " + val + " }", nil
	}
	typ, err := singular(f)
	if err != nil {
		return "", err
	}
	if f.Desc.IsList() {
		if strings.ContainsAny(typ, " |{") {
			typ = "(" + typ + ")"
		}
		typ += "[]"
	}
	return typ, nil
}

func singular(f *protogen.Field) (string, error) {
	switch f.Desc.Kind() {
	case protoreflect.StringKind, protoreflect.BytesKind,
		protoreflect.Int64Kind, protoreflect.Sint64Kind, protoreflect.Sfixed64Kind,
		protoreflect.Uint64Kind, protoreflect.Fixed64Kind:
		return "string", nil
	case protoreflect.BoolKind:
		return "boolean", nil
	case protoreflect.Int32Kind, protoreflect.Sint32Kind, protoreflect.Sfixed32Kind,
		protoreflect.Uint32Kind, protoreflect.Fixed32Kind,
		protoreflect.FloatKind, protoreflect.DoubleKind:
		return "number", nil
	case protoreflect.EnumKind:
		return tsName(f.Enum.Desc), nil
	case protoreflect.MessageKind:
		if wk := wellKnown(f.Message.Desc); wk != "" {
			return wk, nil
		}
		if f.Message.Desc.ParentFile().Package() == "google.protobuf" {
			return "", fmt.Errorf("%s has no declared JSON shape", f.Message.Desc.FullName())
		}
		return tsName(f.Message.Desc), nil
	}
	return "", fmt.Errorf("unsupported field kind %s", f.Desc.Kind())
}

// writeDoc writes a leading comment as TSDoc.
func writeDoc(g *protogen.GeneratedFile, indent string, leading protogen.Comments) {
	if strings.TrimSpace(string(leading)) == "" {
		return
	}
	// A comment line holds the text after the slashes, usually with one leading
	// space; keep the relative indentation of the rest.
	text := strings.ReplaceAll(strings.TrimSuffix(string(leading), "\n"), "*/", "*\\/")
	g.P(indent, "/**")
	for line := range strings.SplitSeq(text, "\n") {
		line = strings.TrimPrefix(line, " ")
		g.P(strings.TrimRight(indent+" * "+line, " "))
	}
	g.P(indent, " */")
}
