// Code generated by protoc-gen-flowstate-doc. DO NOT EDIT.
// source: flowstate/v1/type.proto

package protodoc

import (
	protodocimpl "github.com/picatz/flowstate/pkg/flowstate/v1/protodoc/protodocimpl"
)

func init() {
	protodocimpl.RegisterFile("flowstate/v1/type.proto", []protodocimpl.Comment{
		{
			Name: "flowstate.v1.Type",
			Leading: " Type is the shape of a value, shared by declarations, descriptors, CEL\n" +
				" checking, and every projection that describes a workflow's contract.\n" +
				"\n" +
				" It is structural rather than a rendered string so only the Flowfile compiler\n" +
				" parses type expressions. Consumers of the compiled specification read this\n" +
				" message directly and cannot acquire a second type grammar. The message arm is\n" +
				" reserved for descriptor-backed user types; the compiler does not produce it\n" +
				" until that language surface exists.\n",
		},
		{
			Name:    "flowstate.v1.Type.scalar",
			Leading: " Scalar is one of the closed primitive data kinds above.\n",
		},
		{
			Name:    "flowstate.v1.Type.list",
			Leading: " List is the type of every element in a list.\n",
		},
		{
			Name:    "flowstate.v1.Type.map",
			Leading: " Map has string keys and values of one declared type.\n",
		},
		{
			Name: "flowstate.v1.Type.enum",
			Leading: " Enum marks a closed string set whose members remain on the declaration's\n" +
				" sibling `values` field, where their per-value documentation belongs.\n",
		},
		{
			Name:    "flowstate.v1.Type.message",
			Leading: " Message is the fully qualified Protobuf name of a descriptor-backed type.\n",
		},
		{
			Name:    "flowstate.v1.Type.dyn",
			Leading: " Dyn is a value whose more precise shape is not knowable at compile time.\n",
		},
		{
			Name: "flowstate.v1.Type.Map",
			Leading: " Map is a map with string keys and values of one declared type. String is\n" +
				" fixed rather than another Type field because run values cross JSON\n" +
				" boundaries, where object keys cannot be anything else.\n",
		},
		{
			Name:    "flowstate.v1.Type.Map.value",
			Leading: " Value is the type of every map value.\n",
		},
		{
			Name: "flowstate.v1.Type.Scalar",
			Leading: " Scalar is one indivisible data kind. UINT is deliberately absent: Flowstate\n" +
				" represents integers as signed int64 values and refuses larger unsigned\n" +
				" values at the boundary rather than exposing a numeric kind the DSL cannot\n" +
				" use consistently.\n",
		},
	})
}
