// Code generated by protoc-gen-flowstate-doc. DO NOT EDIT.
// source: flowstate/v1/reports.proto

package protodoc

import (
	protodocimpl "github.com/picatz/flowstate/pkg/flowstate/v1/protodoc/protodocimpl"
)

func init() {
	protodocimpl.RegisterFile("flowstate/v1/reports.proto", []protodocimpl.Comment{
		{
			Name: "flowstate.v1.FixChange",
			Leading: " FixChange is one edit `flow fix` made, or would make under `--check`.\n" +
				"\n" +
				" A schema type for the same reason [Diagnostic] is: `flow fix --output json`\n" +
				" hands this to whatever is driving the CLI, and a hand-invented shape would give\n" +
				" `--output json` two meanings on one binary.\n",
		},
		{
			Name:    "flowstate.v1.FixChange.line",
			Leading: " Line is the 1-based line the change was made at.\n",
		},
		{
			Name:    "flowstate.v1.FixChange.message",
			Leading: " Message says what changed, in the terms an author wrote the file in.\n",
		},
		{
			Name: "flowstate.v1.FixReport",
			Leading: " FixReport is what `flow fix` (or `flow fix --check`) did to one file.\n" +
				"\n" +
				" Per file rather than per invocation, on the same reasoning as [DiagnosticReport]:\n" +
				" `flow fix a.yaml b.yaml` touches two files and a consumer wants to know which\n" +
				" report belongs to which. `Changed` answers \"would git see a diff\" on its own,\n" +
				" because a file with nothing to change produces neither a change nor a refusal\n" +
				" and would otherwise look indistinguishable from one that was never reached.\n" +
				"\n" +
				" The file is also the unit the rewrite happens in: one that cannot be converted\n" +
				" entirely is not written at all, while the others named in the same invocation\n" +
				" convert on their own merits.\n",
		},
		{
			Name: "flowstate.v1.FixReport.file",
			Leading: " File is the path as it was given on the command line, so a reader can find it\n" +
				" again without resolving anything.\n",
		},
		{
			Name: "flowstate.v1.FixReport.changed",
			Leading: " Changed reports that the file was rewritten, or would be under `--check`.\n" +
				" False whenever anything was refused, because then nothing was written at all.\n",
		},
		{
			Name: "flowstate.v1.FixReport.changes",
			Leading: " Changes is every edit made, or that would have been made had the file\n" +
				" converted, in source order. Empty when there was nothing to do. A file with\n" +
				" refusals lists what it found here and applies none of it, so that one run\n" +
				" tells an author the whole of the work rather than the first item of it.\n",
		},
		{
			Name: "flowstate.v1.FixReport.refusals",
			Leading: " Refusals are the places the rewriter could not act on safely, positioned where\n" +
				" a position exists. A file with refusals was left exactly as it was: the\n" +
				" rewrite is per file and all or nothing, because half a migration is a file\n" +
				" claiming a form it is not in.\n",
		},
		{
			Name: "flowstate.v1.FixReport.notes",
			Leading: " Notes are places worth a human's eye that are not problems and do not affect\n" +
				" whether the file is finished: a comment mentioning a step that has moved, for\n" +
				" instance. Distinct from Refusals for the reason `flow fix` draws that line\n" +
				" itself: a caller must not fail a build on one of these.\n",
		},
		{
			Name: "flowstate.v1.FixReport.stale_pins",
			Leading: " StalePins are the `digest:` pins in this file that the run invalidated: this\n" +
				" file calls another one the same run rewrote, and the pin it holds names the\n" +
				" bytes that file had before. Positioned at the pin.\n" +
				"\n" +
				" Reported rather than re-stamped. A pin is the caller saying which bytes it\n" +
				" read, so a rewriter that quietly wrote a new one would be authorizing bytes\n" +
				" nobody has looked at — turning a security check off in the course of running\n" +
				" a migration, which is the one thing `flow fix` refuses to do everywhere else.\n" +
				" Each entry names the digest to adopt, so adopting one is a paste rather than\n" +
				" a calculation.\n" +
				"\n" +
				" Distinct from Notes because a caller must fail on one: the run has left this\n" +
				" file's call refusing to compile, and `flow fix . && git commit` must not\n" +
				" succeed on a tree in that state.\n",
		},
		{
			Name: "flowstate.v1.FmtReport",
			Leading: " FmtReport is what `flow fmt` (or `flow fmt --check`) did to one file.\n" +
				"\n" +
				" `flow fmt` is not comment- or position-preserving the way `flow fix` is (it\n" +
				" reads a file into a workflow and renders that back out from nothing), so a\n" +
				" refusal here is \"this file did not parse (or could not be rendered back out)\"\n" +
				" rather than one shape among several, and rarely carries a position of its own\n" +
				" beyond what the parser's own error already gives.\n",
		},
		{
			Name:    "flowstate.v1.FmtReport.file",
			Leading: " File is the path as it was given on the command line.\n",
		},
		{
			Name:    "flowstate.v1.FmtReport.changed",
			Leading: " Changed reports that the file was reformatted, or would be under `--check`.\n",
		},
		{
			Name: "flowstate.v1.FmtReport.refusals",
			Leading: " Refusals are the reasons the file was left untouched: it did not parse, or the\n" +
				" workflow it parsed into cannot be rendered back out. Positioned where the\n" +
				" parser could position it, unpositioned where the failure is only a message.\n",
		},
		{
			Name: "flowstate.v1.FixReports",
			Leading: " FixReports is what `flow fix` produced, across every file it was given.\n" +
				"\n" +
				" The same reason [ValidationReport] exists beside [DiagnosticReport]: `json` is\n" +
				" one document per invocation and `jsonl` is one per line, and fixing three files\n" +
				" produces three [FixReport] messages, which is three lines of `jsonl` and,\n" +
				" without something to hold them, three documents where `json` promises one.\n",
		},
		{
			Name:    "flowstate.v1.FixReports.files",
			Leading: " Files is one report per file given, in the order they were given.\n",
		},
		{
			Name: "flowstate.v1.FmtReports",
			Leading: " FmtReports is what `flow fmt` produced, across every file it was given, on the\n" +
				" same reasoning as [FixReports].\n",
		},
		{
			Name:    "flowstate.v1.FmtReports.files",
			Leading: " Files is one report per file given, in the order they were given.\n",
		},
		{
			Name: "flowstate.v1.TestCase",
			Leading: " TestCase is what one test in a `*.test.yaml` file produced.\n" +
				"\n" +
				" Per case rather than per file, on the same reasoning as [FixReport]: a test\n" +
				" file usually holds more than one `tests:` entry, and a reader wants to know\n" +
				" which one failed without re-deriving it from an index.\n",
		},
		{
			Name: "flowstate.v1.TestCase.name",
			Leading: " Name is the test's own `name:`, so a report reads the same words the\n" +
				" author wrote.\n",
		},
		{
			Name:    "flowstate.v1.TestCase.passed",
			Leading: " Passed is true when every expectation in the case held.\n",
		},
		{
			Name: "flowstate.v1.TestCase.failures",
			Leading: " Failures are the expectations that did not hold, positioned to the test\n" +
				" file where an expectation's own position is known: a diagnostic in the\n" +
				" same shape `flow validate` and `flow fix` already report, so a consumer of\n" +
				" `-o json` learns one schema for \"something is wrong\" across every verb.\n",
		},
		{
			Name: "flowstate.v1.TestCase.error",
			Leading: " Error is set instead of Failures when the case could not run to a verdict\n" +
				" at all: the workflow it names failed to compile, a stub described a task\n" +
				" the registry does not have, or the run failed in a way the case did not\n" +
				" declare with `expect.failed`. That is distinct from an expectation that ran\n" +
				" and did not hold.\n",
		},
		{
			Name: "flowstate.v1.TestCase.duration",
			Leading: " Duration is how long the case took to run, in wall-clock time. Never a\n" +
				" reading of virtual time: it is what a person deciding whether the suite\n" +
				" is still fast wants to know, and virtual time inside the run answers a\n" +
				" different question.\n",
		},
		{
			Name: "flowstate.v1.TestCase.warnings",
			Leading: " Warnings are facts worth reading that are not verdicts: the case\n" +
				" passed or failed on Failures and Error alone, and these neither block nor\n" +
				" excuse it. The one producer is a stub the case declared and the run\n" +
				" never answered through — a task-form stub whose task was never invoked,\n" +
				" or a matcher tried and never matched — which is a hole in the case's own\n" +
				" account rather than in the run. `flow test --fail-on-warning` promotes\n" +
				" them to the exit code the way `--coverage-required` promotes a coverage\n" +
				" gap; the report itself is identical either way, because whether a run\n" +
				" opted in is a property of the invocation, not of the suite (the same\n" +
				" reasoning [CoverageReport] records for `--coverage-required`).\n",
		},
		{
			Name: "flowstate.v1.TestReport",
			Leading: " TestReport is what `flow test` produced for one `*.test.yaml` file.\n" +
				"\n" +
				" Per file rather than per invocation, on the same reasoning as\n" +
				" [DiagnosticReport]: `flow test examples/` discovers more than one file and a\n" +
				" consumer wants to know which report belongs to which.\n",
		},
		{
			Name: "flowstate.v1.TestReport.file",
			Leading: " File is the path as it was given on the command line, so a reader can\n" +
				" find it again without resolving anything.\n",
		},
		{
			Name: "flowstate.v1.TestReport.cases",
			Leading: " Cases is one result per `tests:` entry in the file, in the order they\n" +
				" were written. Empty when Refused is set: no case was ever reached.\n",
		},
		{
			Name: "flowstate.v1.TestReport.refused",
			Leading: " Refused reports that the file itself could not be run as a test file (it\n" +
				" did not parse, or named a workflow that could not be loaded), which is\n" +
				" reported once for the file rather than once per case.\n",
		},
		{
			Name: "flowstate.v1.TestReport.coverage",
			Leading: " Coverage is one branch-coverage account per workflow the file's cases\n" +
				" targeted. A `*.test.yaml` usually tests one workflow and\n" +
				" carries exactly one entry, but each case names its own `workflow:`, so a\n" +
				" file may target several, and coverage is kept separate per workflow so a\n" +
				" step one workflow reaches never masks the same step id left unreached in\n" +
				" another. Empty when the file was refused, or when no case compiled a\n" +
				" workflow to account for.\n",
		},
		{
			Name: "flowstate.v1.TestReport.schedules",
			Leading: " Schedules is what seeded-schedule exploration found for this file, and is\n" +
				" unset when the invocation explored nothing. That is the default: `flow\n" +
				" test` with no `--seeds` or `--seed` runs each case once, in written order.\n" +
				"\n" +
				" On the machine report for the reason Coverage is: CI reads the account\n" +
				" rather than scraping the prose from stderr, and a `--seeds` run whose\n" +
				" exploration left no machine-readable trace is a green nobody can check.\n" +
				" The cases and coverage beside this field still describe the\n" +
				" written-order runs alone, so a verdict never depends on which seeds were\n" +
				" drawn; a divergence here fails the command without changing any case's\n" +
				" own passed/failed.\n",
		},
		{
			Name: "flowstate.v1.TestReport.skipped",
			Leading: " Skipped is every selected case that was not run, with why: a `skip:`\n" +
				" reason the file wrote, or the first failure `--fail-fast` stopped at. A\n" +
				" skipped case is not in Cases and reaches no coverage, so a report whose\n" +
				" Cases is empty because everything was skipped is told apart here from one\n" +
				" that ran nothing.\n",
		},
		{
			Name:    "flowstate.v1.SkippedTestCase",
			Leading: " SkippedTestCase is one case a `flow test` run selected and did not run.\n",
		},
		{
			Name:    "flowstate.v1.SkippedTestCase.name",
			Leading: " Name is the case's full name, as TestCase.name spells it.\n",
		},
		{
			Name: "flowstate.v1.SkippedTestCase.reason",
			Leading: " Reason is the file's `skip:` text, or the sentence naming the failure a\n" +
				" `--fail-fast` run stopped at.\n",
		},
		{
			Name: "flowstate.v1.ScheduleExploration",
			Leading: " ScheduleExploration is what running one `*.test.yaml`'s cases under seeded\n" +
				" schedules found, beyond the written-order run the rest of the report\n" +
				" describes.\n",
		},
		{
			Name: "flowstate.v1.ScheduleExploration.schedules",
			Leading: " Schedules is how many seeded schedules each explored case ran under,\n" +
				" beyond its written-order run. Counted from what really ran, not from what\n" +
				" was asked for.\n",
		},
		{
			Name:    "flowstate.v1.ScheduleExploration.cases",
			Leading: " Cases is how many of the file's cases were explored.\n",
		},
		{
			Name: "flowstate.v1.ScheduleExploration.decisions",
			Leading: " Decisions is the largest number of scheduling choices any one schedule of\n" +
				" any case asked for.\n" +
				"\n" +
				" Zero means no case reached a junction: the file's workflows have no\n" +
				" `parallel:` and no `async:`, so every schedule explored was written order\n" +
				" and the exploration proved nothing beyond what the ordinary run already\n" +
				" proved. Recorded rather than inferred, because that distinction is\n" +
				" invisible from the outcome alone — a green from exploring nothing must\n" +
				" not read as a green from exploring.\n",
		},
		{
			Name: "flowstate.v1.ScheduleExploration.truncated",
			Leading: " Truncated reports that some schedule spent its whole decision budget and\n" +
				" took written order for the rest of its run, so the interleaving it\n" +
				" explored stopped partway.\n",
		},
		{
			Name: "flowstate.v1.ScheduleExploration.divergence",
			Leading: " Divergence is the first case whose observables were not the same under a\n" +
				" seeded schedule as under written order, unset when every case agreed with\n" +
				" itself under every schedule explored.\n",
		},
		{
			Name: "flowstate.v1.ScheduleDivergenceReport",
			Leading: " ScheduleDivergenceReport is one case that observed a difference the schedule\n" +
				" made: the finding `--seeds` exists to surface, carried with the seed because\n" +
				" a divergence nobody can replay is a random number.\n",
		},
		{
			Name:    "flowstate.v1.ScheduleDivergenceReport.case",
			Leading: " Case is the name of the test case, as the file spells it.\n",
		},
		{
			Name: "flowstate.v1.ScheduleDivergenceReport.seed",
			Leading: " Seed is the schedule that disagreed — the whole of what a replay needs:\n" +
				" `flow test --seed <seed>` on the same file runs exactly this schedule.\n",
		},
		{
			Name: "flowstate.v1.ScheduleDivergenceReport.decisions",
			Leading: " Decisions is how many scheduling choices the diverging seed's run made.\n" +
				" The written-order baseline always makes zero: it asks a scheduler for\n" +
				" nothing.\n",
		},
		{
			Name: "flowstate.v1.ScheduleDivergenceReport.truncated",
			Leading: " Truncated reports that the diverging schedule spent its whole decision\n" +
				" budget, so what it explored is only the part before the bound.\n",
		},
		{
			Name: "flowstate.v1.ScheduleDivergenceReport.written_order",
			Leading: " WrittenOrder is the display rendering of the baseline: the observable\n" +
				" account of the ordinary run, for a person reading the failure rather than\n" +
				" replaying it. The comparison is made over the runs themselves, not over\n" +
				" this. Values the case withholds, a called workflow's declared-sensitive\n" +
				" inputs included, are withheld here as in the rest of the report, and the\n" +
				" rendering then ends by saying so. What either run withholds is withheld\n" +
				" from both renderings, since a reader sees them together.\n",
		},
		{
			Name: "flowstate.v1.ScheduleDivergenceReport.seeded",
			Leading: " Seeded is the corresponding display rendering of the run produced by\n" +
				" [seed], with the same values withheld. It may contain task output and must\n" +
				" be handled with the same trust as test output.\n",
		},
		{
			Name: "flowstate.v1.CoverageReport",
			Leading: " CoverageReport is `flow test`'s branch-coverage account for one workflow:\n" +
				" which of that workflow's steps at least one case ran, and which no case ever\n" +
				" reached.\n" +
				"\n" +
				" It rides the machine report so CI reads the sets rather than scraping the\n" +
				" prose coverage line. Whether `--coverage-required` was passed is not\n" +
				" recorded here: that is the CLI's invocation mode, a property of how the\n" +
				" command was run rather than a fact about the suite, so it stays off the\n" +
				" machine output.\n",
		},
		{
			Name: "flowstate.v1.CoverageReport.workflow",
			Leading: " Workflow is the workflow this coverage accounts for, as the path the case's\n" +
				" `workflow:` resolved to. It is the identity coverage is keyed by, so a\n" +
				" reader can tell two workflows apart when a file targets more than one.\n",
		},
		{
			Name: "flowstate.v1.CoverageReport.steps_total",
			Leading: " StepsTotal is how many of the workflow's steps coverage accounts for: the\n" +
				" size of Reached plus Unreached.\n",
		},
		{
			Name: "flowstate.v1.CoverageReport.steps_reached",
			Leading: " StepsReached is how many of those steps at least one case ran: the size of\n" +
				" Reached.\n",
		},
		{
			Name:    "flowstate.v1.CoverageReport.reached",
			Leading: " Reached is every step id that ran in at least one case, sorted.\n",
		},
		{
			Name: "flowstate.v1.CoverageReport.unreached",
			Leading: " Unreached is the complement: every step id in the workflow that no case\n" +
				" ran, sorted.\n",
		},
		{
			Name: "flowstate.v1.CoverageReport.gaps",
			Leading: " Gaps is every unreached step the file did not record a reason for: the\n" +
				" holes in the suite, as opposed to the residuals it accepted. This is what\n" +
				" `--coverage-required` fails on, together with Stale.\n",
		},
		{
			Name: "flowstate.v1.CoverageReport.accepted",
			Leading: " Accepted maps an unreached step id to the reason the file recorded for it\n" +
				" under `coverage.allow_unreached`. Every key here is also in Unreached: it\n" +
				" is genuinely not reached, and Accepted is why that is a decision rather\n" +
				" than a gap. A step in Accepted does not fail `--coverage-required`.\n",
		},
		{
			Name: "flowstate.v1.CoverageReport.stale",
			Leading: " Stale is every `coverage.allow_unreached` entry that does not describe a\n" +
				" real residual of any workflow the file targets: it names a step some case\n" +
				" reached, or a step id no targeted workflow has. Such a record is a false\n" +
				" statement about the suite, so it fails `--coverage-required` the same way\n" +
				" an unrecorded gap does. Each entry is a sentence naming the step and what\n" +
				" is wrong.\n",
		},
		{
			Name: "flowstate.v1.CoverageReport.arms",
			Leading: " Arms is every arm of every `switch:` step in the workflow, and whether any\n" +
				" test case took it.\n" +
				"\n" +
				" A second coverage unit beside the step one rather than more entries in it,\n" +
				" because an arm is not a step and counting it as one would make StepsTotal a\n" +
				" number about two different things. An arm can also be empty — `steps: []` is\n" +
				" how a switch writes down deliberately ignoring a value — which is precisely\n" +
				" what the step universe cannot see: an empty body contributes no step ids, so\n" +
				" no suite could ever fail to cover it.\n",
		},
		{
			Name: "flowstate.v1.SwitchArmCoverage",
			Leading: " SwitchArmCoverage is one arm of one `switch:` step — one `case:` literal, or\n" +
				" the `default:` — and whether any test case took it.\n" +
				"\n" +
				" Read from the transcript rather than inferred from what ran: a switch records\n" +
				" which literal matched under `case` (SwitchCaseOutput), so the harness reads the\n" +
				" arm that was taken instead of deducing it from the body steps that happened to\n" +
				" appear. That is what makes an empty arm, and one member of a multi-literal `case: [a, b]`,\n" +
				" measurable at all.\n",
		},
		{
			Name: "flowstate.v1.SwitchArmCoverage.arm",
			Leading: " Arm is the coverage key: `<step>:case[<i>]` for a case holding one literal,\n" +
				" `<step>:case[<i>][<j>]` for member j of a case listing several, and\n" +
				" `<step>:default` for the default. It is what a file names under\n" +
				" `coverage.allow_unreached` to record an arm it cannot reach.\n",
		},
		{
			Name:    "flowstate.v1.SwitchArmCoverage.step",
			Leading: " Step is the id of the `switch:` step this arm belongs to.\n",
		},
		{
			Name: "flowstate.v1.SwitchArmCoverage.label",
			Leading: " Label is the arm as an author reads it: `case \"synchronize\"`, `case 3`, or\n" +
				" `default`.\n",
		},
		{
			Name:    "flowstate.v1.SwitchArmCoverage.reached",
			Leading: " Reached reports whether any test case took this arm.\n",
		},
		{
			Name: "flowstate.v1.SwitchArmCoverage.reason",
			Leading: " Reason is what the file recorded for this arm under\n" +
				" `coverage.allow_unreached`, and is empty when it recorded none. A reason is\n" +
				" only meaningful on an arm no case reached, where it makes that arm an\n" +
				" accepted residual rather than a gap.\n",
		},
		{
			Name: "flowstate.v1.SwitchArmCoverage.line",
			Leading: " Line is where the arm was written, 1-based, or zero when the workflow was\n" +
				" not parsed from a file that recorded positions — a workflow submitted as\n" +
				" bytes has no source to point at.\n" +
				"\n" +
				" Carried here and not beside Unreached, which names steps: a step id is an\n" +
				" identity every other surface already resolves, and an arm's is not. There is\n" +
				" no way to find `on_event:case[2]` in a file except by the position that says\n" +
				" where it is.\n",
		},
		{
			Name: "flowstate.v1.SwitchArmCoverage.column",
			Leading: " Column is the 1-based column the arm was written at, or zero when only the\n" +
				" line is known or no position was recorded.\n",
		},
		{
			Name: "flowstate.v1.TestReports",
			Leading: " TestReports is what `flow test` produced, across every file it discovered,\n" +
				" on the same reasoning as [FixReports].\n",
		},
		{
			Name: "flowstate.v1.TestReports.files",
			Leading: " Files is one report per test file discovered, in the order they were\n" +
				" found.\n",
		},
	})
}
