// Code generated by protoc-gen-flowstate-doc. DO NOT EDIT.
// source: flowstate/v1/trigger.proto

package protodoc

import (
	protodocimpl "github.com/picatz/flowstate/pkg/flowstate/v1/protodoc/protodocimpl"
)

func init() {
	protodocimpl.RegisterFile("flowstate/v1/trigger.proto", []protodocimpl.Comment{
		{
			Name: "flowstate.v1.Triggers",
			Leading: " Triggers is what a workflow says about starting itself.\n" +
				"\n" +
				" A message with one field per kind of trigger rather than a oneof, because these\n" +
				" are not alternatives: a workload that runs nightly *and* on a webhook is an\n" +
				" ordinary thing to want, and a oneof would make expressing it a schema change\n" +
				" rather than a second key. Adding a kind is then a new field here, which is\n" +
				" additive on the wire and additive in the grammar: `triggers:` gains a key and\n" +
				" every existing file still means what it meant.\n" +
				"\n" +
				" Its own message rather than fields on [Workflow] for the same reason the DSL\n" +
				" spells it `triggers: { schedule: ... }`: a reader meets one block that answers\n" +
				" \"how does this start\", and a second kind does not scatter a third and fourth\n" +
				" top-level key across the file.\n",
		},
		{
			Name: "flowstate.v1.Triggers.schedule",
			Leading: " Schedule is the cadence this workload is meant to run at.\n" +
				"\n" +
				" Optional and, when present, still inert until somebody creates it. See\n" +
				" `Workflow.triggers` for why the declaration and the act are separate.\n",
		},
		{
			Name: "flowstate.v1.Triggers.webhooks",
			Leading: " Webhooks are the deliveries this workload is meant to start on, one entry\n" +
				" per source.\n" +
				"\n" +
				" Repeated rather than singular because several sources starting one workload\n" +
				" is the ordinary case rather than the exotic one — a payments provider and a\n" +
				" storefront both reporting the same order — and each brings its own payload\n" +
				" shape, its own signing scheme, and therefore its own mapping into\n" +
				" `Workflow.declared_inputs`. That is what makes a webhook a *call site*\n" +
				" rather than a second declaration of the inputs: `arguments` here is the same\n" +
				" construct as `Call.arguments`, checked against the same signature, so N\n" +
				" sources are N callers instead of a keyed sub-language nobody asked for.\n" +
				"\n" +
				" Inert exactly as `schedule` is on the run path: nothing in `Run` reads\n" +
				" this, and both execution drivers ignore it. The server's webhook receiver\n" +
				" is what acts on it — serving deliveries and verifying each one against the\n" +
				" schemes declared here, through [v1.VerifyWebhookDelivery] — while\n" +
				" `flow validate` checks the declaration and `flow test` replays stored\n" +
				" deliveries against it offline. See [WebhookTrigger] for what the receiver\n" +
				" is handed.\n",
		},
		{
			Name: "flowstate.v1.Triggers.manual",
			Leading: " Manual narrows the start that already works, and is the one entry in this\n" +
				" message that does not enable anything.\n" +
				"\n" +
				" `flow run`, `flow run local`, the `Run` RPC and MCP all start a workflow\n" +
				" today with no declaration at all, so `triggers:` is deliberately *not*\n" +
				" exhaustive: adding a webhook must never silently stop `flow run` from\n" +
				" working, or authoring and testing break together the first time somebody\n" +
				" integrates a payment provider. Absent therefore means what it has always\n" +
				" meant — a human may start this — and the field exists to say something\n" +
				" narrower. See [ManualTrigger].\n",
		},
		{
			Name: "flowstate.v1.ManualTrigger",
			Leading: " ManualTrigger is what a workload says about being started by a person.\n" +
				"\n" +
				" # Narrowing, never enabling\n" +
				"\n" +
				" Every field here removes something. A workflow with no `manual:` block may be\n" +
				" started by anyone who can reach the server; declaring one requires a recorded\n" +
				" reason, or restricts who may, or refuses the start outright. There is\n" +
				" deliberately no field that *grants* a manual start, because one already\n" +
				" exists in the absence of this message, and a grant-shaped spelling would make\n" +
				" \"did somebody remember to write it\" the difference between a runnable file\n" +
				" and an unrunnable one.\n" +
				"\n" +
				" # Where it is enforced, and where it deliberately is not\n" +
				"\n" +
				" The server's Run handler enforces this, against the caller the server itself\n" +
				" attested, before Temporal sees anything — the same placement [SignalPolicy]\n" +
				" has and for the same reason. `flow run local` and `flow test` are never\n" +
				" gated: the author's machine is not a deployment, and a workflow that cannot\n" +
				" be developed locally is not one anybody will maintain. That is the rule that\n" +
				" already keeps egress policy out of the validator, applied to the one entry\n" +
				" path an author uses while writing.\n" +
				"\n" +
				" # Why this and not `if: ${trigger.principal == \"admin\"}`\n" +
				"\n" +
				" Authorization belongs on the trigger, decided when configuration loads,\n" +
				" where the validator can see it and a deployment owns it. The same test\n" +
				" written in the body is an expression a test can fake, one `flow validate`\n" +
				" cannot reason about, and one a later refactor can reorder past the step it\n" +
				" was guarding. [TriggerContext] is for behaviour; this message is for\n" +
				" authorization, and the two are kept apart on purpose.\n",
		},
		{
			Name: "flowstate.v1.ManualTrigger.denied",
			Leading: " Denied refuses manual starts outright: this workload is started by its\n" +
				" other declared triggers and by nothing else.\n" +
				"\n" +
				" Explicit and greppable, which is the whole point. \"Triggers are\n" +
				" exhaustive\" would have given the same refusal by inference — declare a\n" +
				" webhook, lose `flow run` — and nobody discovers an inferred lock until\n" +
				" they need it not to be there.\n" +
				"\n" +
				" Contradicts [allow], and the compiler refuses the combination rather than\n" +
				" resolving it by precedence: a refusal that also says who may start the\n" +
				" workload is two sentences that cannot both be true.\n",
		},
		{
			Name: "flowstate.v1.ManualTrigger.require_reason",
			Leading: " RequireReason makes a manual start carry a reason, recorded on the run\n" +
				" (`RunRequest.reason`).\n" +
				"\n" +
				" For the workload where \"who ran this, and why\" is asked after the fact —\n" +
				" a break-glass rotation, a manual refund — and where the answer being\n" +
				" absent is the failure. A start with no reason is refused while the person\n" +
				" who has one is still present to give it.\n",
		},
		{
			Name: "flowstate.v1.ManualTrigger.allow",
			Leading: " Allow is one CEL predicate deciding who may start the workload by hand,\n" +
				" written in a Flowfile as `manual: allow: ${...}`.\n" +
				"\n" +
				" The source is stored without the `${` `}` fence and evaluated by the same\n" +
				" function that decides `signals:` and `debug:` ([SignalPolicy.allow]),\n" +
				" server-side, against the server's own attestation of the caller, over a\n" +
				" closed scope: `sender.identity.{principal,subject,issuer,namespace,claims}`\n" +
				" (the caller) and `inputs` (the arguments being SUBMITTED with this start).\n" +
				" There is no run yet, so `run` is not in scope and a predicate that reads it\n" +
				" is refused when the file compiles.\n" +
				"\n" +
				" Fail closed: a result that is not a bool, an evaluation error, an exceeded\n" +
				" cost or time bound, an expression that does not compile, and a caller with\n" +
				" no authenticated principal all refuse the start; none ever allows. The\n" +
				" refusal names no input or claim value.\n" +
				"\n" +
				" A predicate that reads `inputs` must also read `sender.identity.claims`:\n" +
				" the caller chooses the inputs, and there is no run starter to compare\n" +
				" against, so a predicate over them alone would let the caller admit\n" +
				" themselves. It contradicts [denied].\n",
		},
		{
			Name: "flowstate.v1.ManualTrigger.allow_source",
			Leading: " AllowSource is `allow` as the author wrote it, set only when it differs: an\n" +
				" `allow` that calls a declared function (`FunctionDeclaration`) is stored\n" +
				" expanded in `allow`, so the server evaluates plain CEL, and written here in\n" +
				" the call form, without the `${` `}` fence, so `flow fmt` and Marshal write\n" +
				" the file back as it was authored. Never evaluated, compiled or checked; a\n" +
				" specification that carries one without a matching expansion is read by\n" +
				" `allow` alone.\n",
		},
		{
			Name: "flowstate.v1.TriggerContext",
			Leading: " TriggerContext is how a run was started, as its own steps may read it:\n" +
				" `trigger.kind`, `trigger.name`, `trigger.principal`, `trigger.delivery_id`.\n" +
				"\n" +
				" # Safe for durable execution, and why that is not obvious\n" +
				"\n" +
				" Every field is fixed when the run starts and carried in [RunState], so it is\n" +
				" the same value on every replay and across every Continue-As-New. That is what\n" +
				" separates it from the two facts this language refuses to make ambiently\n" +
				" readable — the clock and randomness — which change underneath a run and would\n" +
				" make a replayed step take a different branch than the one history recorded.\n" +
				" A trigger cannot drift, so it can be read anywhere an ordinary expression is.\n" +
				"\n" +
				" # Metadata, never data\n" +
				"\n" +
				" The set is closed at these four fields on purpose. Everything a workflow\n" +
				" *operates on* arrives through a trigger's `with:` into `Workflow.declared_inputs`,\n" +
				" checked against declarations `flow validate` can see. A payload field reachable\n" +
				" under `trigger` would be a second input path with no contract, invisible to\n" +
				" the validator — so there is no `trigger.payload`, no `trigger.headers`, and\n" +
				" none will be added.\n" +
				"\n" +
				" # Behaviour, never authorization\n" +
				"\n" +
				" `if: ${trigger.kind != \"schedule\"}` is what this is for: a nightly sweep that\n" +
				" does not page anyone, a human start that takes a second pair of eyes.\n" +
				" `if: ${trigger.principal == \"admin\"}` is the shape to refuse — see\n" +
				" [ManualTrigger] for where that decision belongs instead.\n" +
				"\n" +
				" # Nothing secret rides along\n" +
				"\n" +
				" These values are written to durable history, which is broadly readable, so\n" +
				" [principal] is an attested subject and [delivery_id] is a digest rather than\n" +
				" the idempotency key it names (a key is a value read out of the delivery, and\n" +
				" history should not restate one). Neither is material anything can\n" +
				" authenticate with.\n",
		},
		{
			Name: "flowstate.v1.TriggerContext.kind",
			Leading: " Kind is how the run started: `manual`, `webhook`, or `schedule`.\n" +
				"\n" +
				" A string rather than an enum because it is read from a CEL expression, where\n" +
				" an enum arrives as a number and `trigger.kind == 1` is not a sentence\n" +
				" anybody wants to write or review. The set is closed all the same:\n" +
				" `v1.TriggerKinds` names it, and the compiler refuses a comparison against a\n" +
				" word that is not in it, so a misspelled `\"schedual\"` is a diagnostic rather\n" +
				" than a branch that is never taken.\n" +
				"\n" +
				" Empty for a run started before this field existed, which reads as \"no\n" +
				" trigger recorded\" and is the honest answer for one: see\n" +
				" `v1.TriggerContextValue` for how that renders, and why every field is\n" +
				" rendered rather than omitted.\n",
		},
		{
			Name: "flowstate.v1.TriggerContext.name",
			Leading: " Name identifies which trigger of that kind started the run: the webhook's\n" +
				" declared name, or the schedule's. Empty for a manual start, which has no\n" +
				" name to carry — a person is not a declared source.\n",
		},
		{
			Name: "flowstate.v1.TriggerContext.principal",
			Leading: " Principal is who or what started the run, as the server attested it: a\n" +
				" caller's subject for a manual start, the trigger the delivery arrived at\n" +
				" for a webhook, the schedule's owner for a scheduled firing.\n" +
				"\n" +
				" Never taken from a request. It is the same value `RunState.identity`\n" +
				" carries, restated here because a step reading \"how was I started\" should\n" +
				" not have to know that a webhook's principal is spelled one way under `run`\n" +
				" and another under `trigger`.\n",
		},
		{
			Name: "flowstate.v1.TriggerContext.delivery_id",
			Leading: " DeliveryID names the one arrival that started this run, for correlating a\n" +
				" run against the provider's own record of what it sent.\n" +
				"\n" +
				" A digest of the trigger's evaluated `idempotency_key`, never the key: the\n" +
				" key is a value read out of the delivery, and this is written to a memo and\n" +
				" to history, both durable and broadly readable. Empty for every kind that\n" +
				" has no delivery.\n",
		},
		{
			Name: "flowstate.v1.TriggerContext.scheduled_at",
			Leading: " ScheduledAt is the moment a schedule meant this run to start, read as\n" +
				" `trigger.scheduled_at`: the slot, which differs from when the run actually\n" +
				" started under a backfill, a paused-then-resumed schedule, or a catch-up\n" +
				" window. A report about \"the hour that just closed\" is about this, not about\n" +
				" the wall clock it happened to run at.\n" +
				"\n" +
				" Read once, from the `TemporalScheduledStartTime` search attribute Temporal\n" +
				" attaches to an execution a schedule started, by the first segment, and\n" +
				" carried here in [RunState] like [delivery_id], so it is the same value on\n" +
				" every replay and across every Continue-As-New. Nothing reads a clock to\n" +
				" produce it.\n" +
				"\n" +
				" A manual `flow schedule trigger` runs the schedule's action immediately, and\n" +
				" Temporal names the moment it was asked for as its slot, so a manual fire\n" +
				" reads that moment: indistinguishable, to the run, from an on-time firing,\n" +
				" and a usable window where the epoch would not be.\n" +
				"\n" +
				" Unset for every kind that has no schedule, and for a run started before this\n" +
				" field existed; `trigger.scheduled_at` then renders as the Unix epoch, so a\n" +
				" file that reads it guards on `trigger.kind == \"schedule\"` first.\n",
		},
		{
			Name: "flowstate.v1.WebhookTrigger",
			Leading: " WebhookTrigger is one source that may start this workload by delivering to it.\n" +
				"\n" +
				" # A call site, not a second declaration of the inputs\n" +
				"\n" +
				" `arguments` is the same construct a `call:` step writes as `with:`: the\n" +
				" workflow's `inputs:` is the signature, and a trigger is another caller of it,\n" +
				" exactly as `flow run --input` and an MCP invocation are. That choice is the\n" +
				" whole reason `flow validate` can say `webhook \"stripe\" does not supply\n" +
				" required input \"amount\"` with a line and a column, which a per-input `from:`\n" +
				" or a per-trigger mapping block could never say: with a mapping block the same\n" +
				" fact is written twice, in `inputs:` and beside it, with nothing forcing the\n" +
				" two to agree.\n" +
				"\n" +
				" The expressions in `arguments` and in `idempotency_key` are evaluated against\n" +
				" one bound name, `event`, holding the delivery — its headers and its decoded\n" +
				" body. That name is bound here and nowhere else in the language: a step body\n" +
				" that wants to know how the run started reads `trigger.kind` and friends\n" +
				" ([TriggerContext]), which carry provenance and no payload, and payload data\n" +
				" must arrive through `arguments` into `inputs:` or the file has grown a second\n" +
				" input path with no contract.\n" +
				"\n" +
				" # Fail closed, declared rather than assumed\n" +
				"\n" +
				" Two fields are required by the shape of the problem rather than by taste, and\n" +
				" both are refused when the file is compiled rather than when a delivery\n" +
				" arrives:\n" +
				"\n" +
				"   - `verify` names at least one signing scheme. There is deliberately no\n" +
				"     spelling that means \"accept anything\": an unverifiable delivery is\n" +
				"     refused, never allowed because it could not be checked.\n" +
				"   - `idempotency_key` is required. Webhook delivery is at-least-once by\n" +
				"     nature, so a trigger with no dedupe key turns every retried delivery into\n" +
				"     a second run — a fact about the transport, not about this integration's\n" +
				"     luck.\n" +
				"\n" +
				" The remaining bound belongs to the readers of a delivery: a request body is\n" +
				" attacker-chosen input and gets a byte bound *before* it is read into memory.\n" +
				" `v1.MaxWebhookPayloadBytes` is that number, and both readers enforce it —\n" +
				" the receiver `flow server --webhook` serves, and `flow test` reading a\n" +
				" stored delivery off disk — so a rehearsal and a live delivery share one\n" +
				" bound.\n",
		},
		{
			Name: "flowstate.v1.WebhookTrigger.name",
			Leading: " Name identifies this source, both in a diagnostic (`webhook \"stripe\" …`)\n" +
				" and in a `flow test` case that replays a stored delivery against it. Unique\n" +
				" within a file: two sources sharing a name are two mappings a reader cannot\n" +
				" tell apart, and a test naming one of them addresses whichever came first.\n",
		},
		{
			Name: "flowstate.v1.WebhookTrigger.verify",
			Leading: " Verify names the signing schemes a delivery must satisfy, each bound to the\n" +
				" key it is checked with — written in a Flowfile as `${secret('...')}`, so the\n" +
				" material is a reference the receiver resolves rather than a value in a\n" +
				" repository.\n" +
				"\n" +
				" `jwt` is the exception to \"a secret reference\": its value is the name of an\n" +
				" entry in the deployment's trust policy, and the delivery must carry a bearer\n" +
				" token that entry's issuer vouches for. It authenticates the sender (the\n" +
				" delivery then acts as the token's principal) and covers none of the body.\n" +
				" Every scheme written must verify.\n" +
				"\n" +
				" At least one entry, and the schemes are a closed set\n" +
				" ([v1.WebhookVerificationSchemes]) checked when the file compiles: a scheme\n" +
				" nobody implements is a delivery nobody can verify, which under the rule\n" +
				" above means a delivery that is always refused — better said with a line and\n" +
				" a column than discovered in production.\n",
		},
		{
			Name: "flowstate.v1.WebhookTrigger.idempotency_key",
			Leading: " IdempotencyKey is the expression that names a delivery, so a redelivery of\n" +
				" the same event is recognized as one rather than started again.\n" +
				"\n" +
				" Evaluated against `event`, like `arguments`. Required — see the message doc\n" +
				" for why \"this integration has no stable key\" has to be something somebody\n" +
				" writes down rather than something a default quietly assumes.\n",
		},
		{
			Name: "flowstate.v1.WebhookTrigger.arguments",
			Leading: " Arguments bind this source's payload to the workflow's declared inputs, one\n" +
				" expression per input, over `event`.\n" +
				"\n" +
				" Named `arguments` rather than `with` for the reason `Call.arguments` is: the\n" +
				" schema says what the field holds and the DSL says how it is spelled, and the\n" +
				" two constructs are deliberately the same construct — checked against\n" +
				" `Workflow.declared_inputs` by the same rules, in both directions.\n",
		},
		{
			Name: "flowstate.v1.WebhookTrigger.signal",
			Leading: " Signal turns this source into an answer to a gate this workflow already\n" +
				" waits at, rather than a start: a verified delivery is carried to the named\n" +
				" `wait_for_signal:` of a run that already exists.\n" +
				"\n" +
				" Mutually exclusive with [arguments], and refused together with it rather\n" +
				" than resolved by precedence. The two say incompatible things about what a\n" +
				" delivery *is* — one binds a run's `inputs:` as it starts, the other\n" +
				" answers a run that is already parked — and one delivery cannot be both.\n" +
				" See [WebhookTrigger.Signal].\n",
		},
		{
			Name: "flowstate.v1.WebhookTrigger.when",
			Leading: " When is the admission predicate: a boolean expression over `event` that\n" +
				" decides whether a verified delivery is acted on at all, written\n" +
				" `when: ${...}` in a Flowfile. It is the one thing a trigger could not say\n" +
				" before: no.\n" +
				"\n" +
				" Evaluated at the boundary after verification and before `idempotency_key`,\n" +
				" `arguments`, and (on a bridge) `signal.correlate`, in the same environment\n" +
				" and under the same limits as those, by the same evaluator. It applies to a\n" +
				" start and to a bridge alike, and is deliberately not repeated inside\n" +
				" [Signal]: one trigger has one admission rule, and a second spelling per arm\n" +
				" would be the second mechanism.\n" +
				"\n" +
				" Only a clean `true` admits. `false` declines the delivery: it starts no\n" +
				" run, delivers no signal, records no idempotency key, and is answered `204`\n" +
				" so the provider does not retry it. An evaluation error, a result that is\n" +
				" not a bool, and an exceeded cost or time bound fail closed: the delivery is\n" +
				" refused, with a fixed sentence that echoes nothing from it, and starts\n" +
				" nothing. Absent means every verified delivery is admitted, as before.\n" +
				"\n" +
				" May not read a secret, and must read `event`: a predicate that cannot vary\n" +
				" with the delivery admits all of them or none of them.\n",
		},
		{
			Name: "flowstate.v1.WebhookTrigger.respond_within",
			Leading: " RespondWithin is how long the receiver holds a delivery open to answer with\n" +
				" the run's declared outputs, written `respond_within: 5s` in a Flowfile.\n" +
				" Absent means the receiver answers as it always has: with the run's address,\n" +
				" as soon as the run is started or joined.\n" +
				"\n" +
				" Set, the receiver waits for the run it started (or joined) for at most this\n" +
				" long and answers with `status`: `completed` with the run's declared\n" +
				" `outputs:`, `failed` with the failure's sentence, or `running` when the\n" +
				" bound passed first, in which case the run continues and the caller reads it\n" +
				" with `Get`. The HTTP status keeps its meaning (a delivery disposition), so a\n" +
				" 2xx still tells a provider the delivery landed and must not be retried\n" +
				" whatever the run did.\n" +
				"\n" +
				" The field is itself the bound, and there is no default: a wait the sender\n" +
				" chose the length of, or the author never wrote down, would hold a\n" +
				" receiver slot for as long as a run took. 100ms to 30s. A waiting delivery\n" +
				" holds its slot of the receiver's concurrency bound for the whole wait.\n" +
				"\n" +
				" The only thing a run can answer with is its declared outputs, so this is\n" +
				" refused with no `outputs:`, and refused with [signal]: a bridge starts\n" +
				" nothing and has no run of its own to wait for. Sensitive outputs are\n" +
				" withheld, and there is no way to reveal one on this surface. There is no\n" +
				" callback form: a run that must tell somebody later does it as a last step.\n",
		},
		{
			Name: "flowstate.v1.WebhookTrigger.Signal",
			Leading: " Signal is a delivery answering a declared gate instead of starting a run.\n" +
				"\n" +
				" # It reuses `signals:`, and is not a second authorization\n" +
				"\n" +
				" A delivery proves possession of the trigger's signing key, not a person,\n" +
				" so it acts as the trigger: the receiver already mints that principal for a\n" +
				" run start (issuer `flowstate://webhook`, subject `<workflow>/<trigger>`,\n" +
				" the receiver's own namespace), and the bridge carries the same principal\n" +
				" to the same [SignalPolicy] rules through the same authorization path\n" +
				" `flow signal` takes. No rule kind, no principal kind and no second policy\n" +
				" spelling: a `signals:` entry admits or refuses a delivery exactly as it\n" +
				" admits or refuses a person.\n" +
				"\n" +
				" What that principal cannot say is *who clicked*. `hmac_sha256` and\n" +
				" `stripe` attest a key holder, so an `allow:` predicate comparing `run.identity` separates\n" +
				" triggers rather than humans on this path, and a workflow that needs two\n" +
				" distinct people either side of a gate cannot get them from a webhook\n" +
				" today.\n" +
				"\n" +
				" # The zero case is closed here, and only here\n" +
				"\n" +
				" A signal name with no `signals:` entry admits any sender — the deliberate\n" +
				" zero case, argued at `SignalPolicyCheck`, and tolerable for `flow signal`\n" +
				" behind the server's own authentication. It is not tolerable for a key\n" +
				" holder on a public route, so a `signal:` naming a name with no policy is\n" +
				" refused when the file compiles; a policy whose predicate cannot admit this\n" +
				" trigger's principal denies every delivery instead, because what a\n" +
				" predicate admits is decided at delivery, over the sender. The refusal of\n" +
				" a missing policy is a property of the *file*, so `flow validate` says it with\n" +
				" a line and a column rather than a receiver discovering it at three in the\n" +
				" morning.\n",
		},
		{
			Name: "flowstate.v1.WebhookTrigger.Signal.name",
			Leading: " Name is the signal delivered, and it must be one a `wait_for_signal:` or\n" +
				" `wait_for_signals:` in this same workflow declares.\n" +
				"\n" +
				" Not a free-form routing key: a name nothing waits for is a delivery the\n" +
				" run carries forever without ever consuming, which is the same thing\n" +
				" `SignalWithStart` refuses out loud for the same reason.\n",
		},
		{
			Name: "flowstate.v1.WebhookTrigger.Signal.correlate",
			Leading: " Correlate is the expression, over `event`, that says which run this\n" +
				" delivery answers. It yields the run's *entity key* — the stable business\n" +
				" key `RunRequest.entity_key` and `SignalWithStartRequest.entity_key`\n" +
				" already address a run by — and the receiver composes the workflow id\n" +
				" from it exactly as those do.\n" +
				"\n" +
				" An entity key rather than a workflow id, and that is the load-bearing\n" +
				" choice. A payload is sender-shaped, neither verification scheme signs\n" +
				" headers, and a workflow id lifted out of one would let a key holder name\n" +
				" any run in the tenant, including runs their own trigger has nothing to\n" +
				" do with. An entity key is composed with the *receiver's* namespace by\n" +
				" `EntityWorkflowID`, under a grammar (lowercase letters, digits, dashes)\n" +
				" that cannot reach a run addressed any other way: a webhook-started run's\n" +
				" own id is `flowstate-webhook-<digest>`, a namespace this expression has\n" +
				" no spelling for.\n" +
				"\n" +
				" Required: there is no default correlation, because \"whichever run is\n" +
				" current\" is not a thing a delivery may mean.\n",
		},
		{
			Name: "flowstate.v1.WebhookTrigger.Signal.arguments",
			Leading: " Arguments are what the delivery carries into the gate, one expression\n" +
				" per name, over `event` — spelled `with:` in a Flowfile.\n" +
				"\n" +
				" Named `arguments` rather than `payload` for `WebhookTrigger.arguments`'\n" +
				" reason, and spelled `with:` for the same one: this is a *call site*, and\n" +
				" when a wait later declares what it accepts, the call-site spelling is\n" +
				" already the one triggers use. Nothing checks these names against a\n" +
				" signature today, because a wait has none — a `wait_for_signal:` accepts\n" +
				" whatever shape arrives and shapes it with its own `outputs:`. That is a\n" +
				" gap this spelling is chosen to close add-only later, not a claim the\n" +
				" shape is checked now.\n",
		},
		{
			Name: "flowstate.v1.ScheduleTrigger",
			Leading: " ScheduleTrigger says when a workload should run.\n" +
				"\n" +
				" # A projection of Temporal's ScheduleSpec, not a reimplementation\n" +
				"\n" +
				" Temporal has first-class Schedules, with a spec covering cron expressions,\n" +
				" intervals, calendars, skips, jitter, time zones, start and end bounds, and\n" +
				" policy about what to do when a firing overlaps the last one. Every field here\n" +
				" is passed to that spec unchanged; nothing in Flowstate computes a next firing\n" +
				" time, and nothing here is a second implementation of a cron parser at run time.\n" +
				" What this message is for is giving those parameters a *declarable* spelling:\n" +
				" the surface, not the mechanism.\n" +
				"\n" +
				" # What is here, and what is deliberately not yet\n" +
				"\n" +
				" Cron expressions, intervals and explicit calendars are unioned. Start/end\n" +
				" bounds constrain that union, catch-up limits automatic missed-fire recovery,\n" +
				" and overlap and pause-on-failure define how executions interact. Backfill is\n" +
				" creation-only and therefore lives on [CreateScheduleRequest], not here.\n" +
				"\n" +
				" # Where the arguments are not\n" +
				"\n" +
				" There is deliberately no `inputs:` under a schedule. What a scheduled run is\n" +
				" started with is bound at creation, from the command that creates it (see\n" +
				" `CreateScheduleRequest.inputs`), because arguments are a deployment's answer\n" +
				" (which cluster, which account, which region) while the cadence is the\n" +
				" workload's. Putting them here would also make the same values expressible in\n" +
				" two places, since an input declaration already carries a default, and a\n" +
				" precedence rule between a default and a schedule's override is a rule somebody\n" +
				" has to learn for no benefit.\n",
		},
		{
			Name: "flowstate.v1.ScheduleTrigger.cron",
			Leading: " Cron holds cron expressions, each naming a set of firing times.\n" +
				"\n" +
				" Repeated because a cadence like \"every weekday at 09:00, and at noon on\n" +
				" Sunday\" is two expressions and cannot be one: the union is what Temporal\n" +
				" takes. The DSL accepts a single string as well as a list, so the common case\n" +
				" reads as one line.\n" +
				"\n" +
				" Temporal accepts 5, 6 or 7 fields, the `@daily`-style shorthands, `@every\n" +
				" <interval>`, and an optional `CRON_TZ=`/`TZ=` prefix. `flow validate` checks\n" +
				" the shape of what is written here and reports a position; the cluster is the\n" +
				" authority on the rest, which is the standing rule for anything a deployment\n" +
				" decides.\n",
		},
		{
			Name: "flowstate.v1.ScheduleTrigger.every",
			Leading: " Every fires on a fixed interval, measured from the epoch rather than from the\n" +
				" last firing, so `every: 1h` is every hour on the hour, not an hour after\n" +
				" whenever the previous run happened to end.\n" +
				"\n" +
				" Beside `cron:` rather than instead of it because the two answer different\n" +
				" questions. An interval is what somebody means by \"every fifteen minutes\"; a\n" +
				" cron expression is what they mean by \"at 09:00 on weekdays\", and expressing\n" +
				" either in the other's notation is where the mistakes live.\n",
		},
		{
			Name: "flowstate.v1.ScheduleTrigger.time_zone",
			Leading: " TimeZone is the IANA zone a calendar-based expression is read in, for example\n" +
				" `America/New_York`. Empty means UTC.\n" +
				"\n" +
				" Resolved by the Temporal cluster from the zone database it runs with, not\n" +
				" here: a zone name is exactly the kind of thing a deployment answers, and a\n" +
				" validator running in an editor would be answering from the author's laptop.\n" +
				" What is checked here is that it is a plausible name; whether this cluster has\n" +
				" it is the cluster's to say.\n",
		},
		{
			Name: "flowstate.v1.ScheduleTrigger.jitter",
			Leading: " Jitter spreads firings over a window, so a fleet of schedules that all say\n" +
				" `0 * * * *` does not become a thundering herd on the hour.\n" +
				"\n" +
				" Each firing is delayed by a random amount between zero and this, capped by\n" +
				" the time until the next firing.\n",
		},
		{
			Name: "flowstate.v1.ScheduleTrigger.overlap",
			Leading: " Overlap is what happens when a firing comes due with the last run still\n" +
				" going. Unset takes Temporal's default, which is to skip.\n",
		},
		{
			Name: "flowstate.v1.ScheduleTrigger.calendars",
			Leading: " Calendars are unioned with cron and interval cadences: a schedule fires at\n" +
				" every time any of the three matches, so a calendar beside a cron expression\n" +
				" adds firings rather than filtering them.\n",
		},
		{
			Name: "flowstate.v1.ScheduleTrigger.start_at",
			Leading: " StartAt is the earliest moment a firing may occur, inclusive. Unset means\n" +
				" no lower bound. A start that is not before `end_at` is refused at\n" +
				" creation, because such a schedule can never fire.\n",
		},
		{
			Name: "flowstate.v1.ScheduleTrigger.end_at",
			Leading: " EndAt is the latest moment a firing may occur, inclusive. Unset means the\n" +
				" schedule fires indefinitely.\n",
		},
		{
			Name: "flowstate.v1.ScheduleTrigger.catchup_window",
			Leading: " CatchupWindow limits how late a missed firing may still be taken when the\n" +
				" Temporal service returns from an outage.\n" +
				"\n" +
				" Optional here, but never absent by the time Temporal sees it: an unset\n" +
				" window is one Temporal defaults to *one year*, so a schedule that says\n" +
				" nothing would take a year of missed firings at once. The server therefore\n" +
				" substitutes its own bounded default (`v1.DefaultScheduleCatchupWindow`) for\n" +
				" an absent value, and this field is how an operator asks for a different one,\n" +
				" up to thirty days.\n",
		},
		{
			Name: "flowstate.v1.ScheduleTrigger.pause_on_failure",
			Leading: " PauseOnFailure pauses the whole schedule after an action exhausts its\n" +
				" retries or times out, so a workload failing every hour stops at the first\n" +
				" failure rather than at the hundredth. A firing already started is not\n" +
				" recalled.\n",
		},
		{
			Name: "flowstate.v1.ScheduleTrigger.Calendar",
			Leading: " Calendar is an explicit calendar cadence, matched field by field the way a\n" +
				" cron expression is: a time matches when at least one range of every field\n" +
				" matches it. A field nobody writes takes Temporal's default for that field:\n" +
				" second, minute and hour default to zero, and the three date fields match\n" +
				" everything. That is why a calendar with no fields at all is refused rather\n" +
				" than compiled: it means 00:00:00 every day, and nobody writes that by\n" +
				" meaning it.\n",
		},
		{
			Name:    "flowstate.v1.ScheduleTrigger.Calendar.second",
			Leading: " Second matches seconds, 0 to 59. Empty means 0.\n",
		},
		{
			Name:    "flowstate.v1.ScheduleTrigger.Calendar.minute",
			Leading: " Minute matches minutes, 0 to 59. Empty means 0.\n",
		},
		{
			Name: "flowstate.v1.ScheduleTrigger.Calendar.hour",
			Leading: " Hour matches hours, 0 to 23, in the schedule's `time_zone`. Empty means\n" +
				" 0.\n",
		},
		{
			Name:    "flowstate.v1.ScheduleTrigger.Calendar.day_of_month",
			Leading: " DayOfMonth matches days of the month, 1 to 31. Empty matches every day.\n",
		},
		{
			Name:    "flowstate.v1.ScheduleTrigger.Calendar.month",
			Leading: " Month matches months, 1 (January) to 12. Empty matches every month.\n",
		},
		{
			Name:    "flowstate.v1.ScheduleTrigger.Calendar.year",
			Leading: " Year matches years, 1970 to 3000. Empty matches every year.\n",
		},
		{
			Name: "flowstate.v1.ScheduleTrigger.Calendar.day_of_week",
			Leading: " DayOfWeek matches days of the week, 0 to 6, where 0 is Sunday. Empty\n" +
				" matches every day.\n",
		},
		{
			Name: "flowstate.v1.ScheduleTrigger.Calendar.comment",
			Leading: " Comment is a note describing this calendar, at most 256 characters. It\n" +
				" does not affect when the schedule fires.\n",
		},
		{
			Name: "flowstate.v1.ScheduleTrigger.Calendar.Range",
			Leading: " Range is a low-to-high span of one field, written in a Flowfile as a whole\n" +
				" number, a list of them, or `{start: 9, end: 17, step: 2}`.\n",
		},
		{
			Name: "flowstate.v1.ScheduleTrigger.Calendar.Range.start",
			Leading: " Start is the first value the range matches. Required in a Flowfile's\n" +
				" long form, because zero is a real value in several fields.\n",
		},
		{
			Name: "flowstate.v1.ScheduleTrigger.Calendar.Range.end",
			Leading: " End is the last value, inclusive. Zero means no end was written, which\n" +
				" matches the start alone. The schema cannot distinguish an unwritten end\n" +
				" from one written as zero, and Temporal reads both the same way. An end\n" +
				" below the start is refused rather than passed on, since Temporal would\n" +
				" silently narrow it to the start.\n",
		},
		{
			Name: "flowstate.v1.ScheduleTrigger.Calendar.Range.step",
			Leading: " Step is how far apart the matched values are. Zero means no step was\n" +
				" written, which takes every value in the range.\n",
		},
		{
			Name: "flowstate.v1.ScheduleTrigger.Overlap",
			Leading: " Overlap says what happens when a firing comes due while the previous run is\n" +
				" still going.\n" +
				"\n" +
				" Mirrors Temporal's `ScheduleOverlapPolicy` value for value. Named as a\n" +
				" Flowstate enum rather than importing Temporal's because this is the schema a\n" +
				" Flowfile compiles to and a plugin compiles against, and neither should\n" +
				" acquire a dependency on the execution substrate's API to read a workflow,\n" +
				" the same reasoning that keeps [RetryPolicy] a Flowstate message.\n",
		},
		{
			Name: "flowstate.v1.ScheduleTrigger.OVERLAP_UNSPECIFIED",
			Leading: " Unspecified takes Temporal's own default, which is SKIP.\n" +
				"\n" +
				" Left as a real arm rather than defaulted here so that \"the author said\n" +
				" nothing\" and \"the author wrote skip\" stay distinguishable in the\n" +
				" specification. They behave identically; only one of them changes if\n" +
				" Temporal's default ever does, and that is the correct one to move.\n",
		},
		{
			Name: "flowstate.v1.ScheduleTrigger.OVERLAP_SKIP",
			Leading: " Skip drops the new firing entirely. The safe default: a nightly job that\n" +
				" takes longer than a day does not pile up.\n",
		},
		{
			Name: "flowstate.v1.ScheduleTrigger.OVERLAP_BUFFER_ONE",
			Leading: " BufferOne runs the new firing after the current one finishes, keeping at\n" +
				" most one waiting.\n",
		},
		{
			Name: "flowstate.v1.ScheduleTrigger.OVERLAP_BUFFER_ALL",
			Leading: " BufferAll queues every firing, running them one after another. A backlog\n" +
				" is bounded only by how long the runs take, so this is the arm to think\n" +
				" twice about.\n",
		},
		{
			Name: "flowstate.v1.ScheduleTrigger.OVERLAP_CANCEL_OTHER",
			Leading: " CancelOther cancels the running one and starts the new one once it has\n" +
				" stopped, letting the old run clean up on the way out.\n",
		},
		{
			Name: "flowstate.v1.ScheduleTrigger.OVERLAP_TERMINATE_OTHER",
			Leading: " TerminateOther stops the running one immediately and starts the new one.\n" +
				" Nothing the old run would have done on its way out is done.\n",
		},
		{
			Name: "flowstate.v1.ScheduleTrigger.OVERLAP_ALLOW_ALL",
			Leading: " AllowAll starts the new firing regardless, so several runs of the workload\n" +
				" are in flight at once.\n",
		},
		{
			Name: "flowstate.v1.ScheduleBackfill",
			Leading: " ScheduleBackfill asks creation to evaluate the declared cadence over a\n" +
				" historical interval, taking the actions it would have taken then, now.\n" +
				"\n" +
				" The interval is half-open: Temporal evaluates times *after* start_at and up\n" +
				" to and including end_at, so a start written at exactly the first firing time\n" +
				" wanted excludes it. Write the start a moment earlier.\n" +
				"\n" +
				" The server bounds both how many intervals are accepted and their total span,\n" +
				" because a backfill is the one place where a single request decides how many\n" +
				" executions a cluster starts at once.\n",
		},
		{
			Name: "flowstate.v1.ScheduleBackfill.start_at",
			Leading: " StartAt begins the interval, exclusive: a firing due exactly at this\n" +
				" moment is not taken. Required.\n",
		},
		{
			Name:    "flowstate.v1.ScheduleBackfill.end_at",
			Leading: " EndAt ends the interval, inclusive. Required.\n",
		},
		{
			Name: "flowstate.v1.ScheduleBackfill.overlap",
			Leading: " Overlap is what happens when a backfilled firing comes due while an\n" +
				" earlier run is still going. Unset takes the schedule's own `overlap`.\n",
		},
	})
}
