// Code generated by protoc-gen-flowstate-doc. DO NOT EDIT.
// source: flowstate/v1/policy_suite.proto

package protodoc

import (
	protodocimpl "github.com/picatz/flowstate/pkg/flowstate/v1/protodoc/protodocimpl"
)

func init() {
	protodocimpl.RegisterFile("flowstate/v1/policy_suite.proto", []protodocimpl.Comment{
		{
			Name: "flowstate.v1.PolicyTestSuite",
			Leading: " PolicyTestSuite is the file `flow policy test` reads: cases to put to one\n" +
				" deployment policy, each saying whether the policy must allow or deny and,\n" +
				" for a denial, optionally which rule must be the one that denies.\n" +
				"\n" +
				" # Why the file is a message\n" +
				"\n" +
				" For the reason [PolicyCheckMatrix] is: an author writes it, more than one tool\n" +
				" may read it, and this schema is the one place its shape, bounds and\n" +
				" documentation are written. Nothing is sent anywhere.\n" +
				"\n" +
				" # One suite, one policy surface\n" +
				"\n" +
				" A suite names the surface its policy file is, once, because a policy file is\n" +
				" one surface and a case that belonged to a different one could only ever be a\n" +
				" mistake. The surfaces are the deployment policies whose decision needs no\n" +
				" server: egress (`--egress-policy`), task shape (`--task-policy`) and exec\n" +
				" (`--exec-policy`). Each case is decided by the evaluator the engine enforces\n" +
				" that policy with, not by a copy of it.\n" +
				"\n" +
				" # Nothing here is attested\n" +
				"\n" +
				" Every identity in this file is an assertion the author makes. The suite says\n" +
				" what the policy would answer for it, not whether a deployment's authenticator\n" +
				" would let that identity through.\n",
		},
		{
			Name:    "flowstate.v1.PolicyTestSuite.surface",
			Leading: " Surface is which policy the file under test is: `egress`, `task` or `exec`.\n",
		},
		{
			Name: "flowstate.v1.PolicyTestSuite.cases",
			Leading: " Cases are put to the policy in order. At least one, and no more than 512,\n" +
				" because every case is a full evaluation of the policy.\n",
		},
		{
			Name:    "flowstate.v1.PolicyTestCase",
			Leading: " PolicyTestCase is one request put to the policy, and what the policy must say.\n",
		},
		{
			Name: "flowstate.v1.PolicyTestCase.name",
			Leading: " Name labels the case in the output. Unique across the file (checked by the\n" +
				" reader), at most 128 characters, and free of control characters (C0, DEL and\n" +
				" C1) and Unicode format characters (category Cf), since it is printed.\n",
		},
		{
			Name: "flowstate.v1.PolicyTestCase.identity",
			Leading: " Identity is who the request is made as. Absent is no attested caller, which\n" +
				" a rule that scopes by tenant declines to match.\n",
		},
		{
			Name: "flowstate.v1.PolicyTestCase.request",
			Leading: " Request is what is asked of the policy; which fields it may carry depends\n" +
				" on the suite's surface, and one that carries another surface's is refused.\n",
		},
		{
			Name: "flowstate.v1.PolicyTestCase.expect",
			Leading: " Expect is the outcome the policy must give: `allow` or `deny`. Required: a\n" +
				" case that asserted nothing would read as if it asserted something.\n",
		},
		{
			Name: "flowstate.v1.PolicyTestCase.rule",
			Leading: " Rule asserts which rule denies, and is allowed only with `expect: deny`. For\n" +
				" a deny rule it is the rule's source text exactly as the policy file writes\n" +
				" it; for any other denial it is the reason the policy gives (`allow rules`\n" +
				" when no allow rule matched, `rule error`, and for egress and exec the\n" +
				" category: `scheme`, `port`, `address`, `executable`, `argv`, `dir`, `env`).\n" +
				" A policy that denies for a different reason fails the case.\n",
		},
		{
			Name: "flowstate.v1.PolicyTestIdentity",
			Leading: " PolicyTestIdentity is the identity a case is made as: the fields every policy\n" +
				" surface reads as `identity.<field>`.\n",
		},
		{
			Name:    "flowstate.v1.PolicyTestRequest",
			Leading: " PolicyTestRequest is the request a case puts to the policy.\n",
		},
		{
			Name: "flowstate.v1.PolicyTestRequest.url",
			Leading: " Url and Method are an egress request. Url is required for `egress`; Method\n" +
				" defaults to GET.\n",
		},
		{
			Name: "flowstate.v1.PolicyTestRequest.ip",
			Leading: " Ip is the address an egress request is said to resolve to, for the\n" +
				" address checks a hostname cannot exercise without DNS (loopback, private\n" +
				" ranges, link-local and metadata). Absent, a host that is itself an IP\n" +
				" literal is checked as that address and any other host is not address-checked.\n",
		},
		{
			Name: "flowstate.v1.PolicyTestRequest.task",
			Leading: " Task is the qualified task name dispatched, such as `http` or `codex.exec`.\n" +
				" Required for `task`.\n",
		},
		{
			Name: "flowstate.v1.PolicyTestRequest.argv",
			Leading: " Argv, Dir and Env are an exec request: the program name and its arguments,\n" +
				" the working directory and the step's environment. Argv is required for\n" +
				" `exec`.\n",
		},
	})
}
