// Code generated by protoc-gen-flowstate-doc. DO NOT EDIT.
// source: flowstate/v1/signal.proto

package protodoc

import (
	protodocimpl "github.com/picatz/flowstate/pkg/flowstate/v1/protodoc/protodocimpl"
)

func init() {
	protodocimpl.RegisterFile("flowstate/v1/signal.proto", []protodocimpl.Comment{
		{
			Name: "flowstate.v1.SignalPolicy",
			Leading: " SignalPolicy constrains who may deliver one named signal to a run.\n" +
				"\n" +
				" A sender is authorized when the one CEL predicate in [allow] is true. The\n" +
				" same message carries the `debug:` stanza's policy, and `manual:` has the same\n" +
				" shape in `ManualTrigger.allow`.\n" +
				"\n" +
				" Field 1 (the `allow` rule list of `SignalPolicyRule` messages), field 2\n" +
				" (`distinct_from_starter`) and the rule message itself were retired in favor\n" +
				" of the predicate: every rule list is a disjunction of conjunctions over the\n" +
				" sender, and `flow fix` rewrites each one into the predicate that says the\n" +
				" same. Their numbers are reserved so a policy frozen in an older run's memo\n" +
				" decodes as a policy with no predicate, which authorizes nobody, never as one\n" +
				" that reads a stale field as something else.\n",
		},
		{
			Name: "flowstate.v1.SignalPolicy.allow",
			Leading: " Allow is one CEL predicate that decides the whole policy, written in a\n" +
				" Flowfile as `allow: ${...}`. A policy with none authorizes nobody, which\n" +
				" is indistinguishable from a typo and is refused by the compiler\n" +
				" (`CheckPolicyShape`) rather than accepted as (probably unintended)\n" +
				" lockout.\n" +
				"\n" +
				" The source is stored without the `${` `}` fence. It is evaluated\n" +
				" server-side, against the server's own attestation, over a closed scope:\n" +
				" `sender.identity.{principal,subject,issuer,namespace,claims}`,\n" +
				" `run.identity` (the starter, with the same shape; unbound when the run\n" +
				" has no recorded starter, so a predicate that reads it errors), and\n" +
				" `inputs` (the run's bound arguments). Nothing else is in scope.\n" +
				"\n" +
				" Fail closed: a result that is not a bool, an evaluation error, an unbound\n" +
				" starter that is read, an exceeded cost bound, or an expression that does\n" +
				" not compile all refuse the sender; none ever allows. The refusal names no\n" +
				" input or claim value.\n" +
				"\n" +
				" A predicate that reads `inputs` must also read `sender.identity.claims` or\n" +
				" `run.identity`: whoever started the run chose the inputs, so a predicate\n" +
				" over them alone would let the starter name their own approver. This is a\n" +
				" syntactic rule, so authors should write the narrowing as a conjunction.\n" +
				"\n" +
				" This field was `allow_expr` at the same number before the rule list was\n" +
				" retired; the wire encoding is unchanged and only the JSON name differs.\n",
		},
		{
			Name: "flowstate.v1.Signal",
			Leading: " Signal names something a workload waits to be told.\n" +
				"\n" +
				" The payload a signal carries becomes the waiting step's outputs, which is what\n" +
				" makes a gate compose with everything else: `${steps.approval.payload.approved}`\n" +
				" resolves the way any other step reference does, so it works in an `if:`, in a\n" +
				" task input, and in a later expression, with no special form for signals.\n",
		},
		{
			Name: "flowstate.v1.Signal.name",
			Leading: " Name is what a sender addresses. It is part of the workload's contract with\n" +
				" whatever approves it, so it is written by the author rather than generated.\n",
		},
		{
			Name: "flowstate.v1.Signal.outputs",
			Leading: " Outputs shapes what the waiting step produces, the way the http task's own\n" +
				" `outputs:` shapes what a request produces.\n" +
				"\n" +
				" Each value is evaluated once, at the moment the wait resolves, against the\n" +
				" wait's own result: `payload`, `sender` and `timed_out` are bound bare, and\n" +
				" so is `now`: every expression a wait holds sees the driver's clock (see\n" +
				" [NowIdentifier]). The enclosing scope is underneath, so `steps.*`,\n" +
				" `inputs.*` and `vars.*` read here exactly as they do in an `if:`.\n" +
				"\n" +
				"     wait_for_signal:\n" +
				"       name: deploy-approved\n" +
				"       timeout: 1h\n" +
				"       outputs:\n" +
				"         approved: ${has(payload.approved) && payload.approved}\n" +
				"         timed_out: ${timed_out}\n" +
				"\n" +
				" # Replace, not extend\n" +
				"\n" +
				" The shaped names become the step's outputs, and the defaults are gone:\n" +
				" one key with one meaning, matching `Task.HTTP.Inputs.outputs` exactly. An\n" +
				" author who still needs `payload` or `timed_out` re-exposes it in a line,\n" +
				" and reading one that was dropped is an ordinary \"step has no output\"\n" +
				" diagnostic rather than an empty value that branches the wrong way.\n" +
				"\n" +
				" # Why this exists\n" +
				"\n" +
				" A condition derived from a step's own result had nowhere to be named, so\n" +
				" real workflows wrote it once per reader: in an `if:`, negated in the\n" +
				" sibling's `if:`, and re-derived in the workflow's `outputs:`. Nothing kept\n" +
				" the copies in agreement, and the report could disagree with the branch that\n" +
				" ran. Shaped here, the gate is stated once on the step that produced the data\n" +
				" and every later reader reads the same recorded output.\n" +
				"\n" +
				" # Why it is on Signal rather than on Wait\n" +
				"\n" +
				" Two of the three names these expressions see (`payload` and `sender`) do\n" +
				" not exist on the other arms, and the third, `timed_out`, is a constant\n" +
				" `false` for a `sleep:` and a `wait_until:`. Shaping a constant is what\n" +
				" `vars:` is for. Putting the field here rather than on [Wait] makes the\n" +
				" refusal structural instead of reported: `timeout` sits on [Wait] and is\n" +
				" meaningless on two of its arms, which is exactly why [ValidateWait] has to\n" +
				" exist. The placement also matches the precedent it copies: http's\n" +
				" `outputs:` sits on that task's own inputs, not on a generic step wrapper.\n" +
				"\n" +
				" Carriage across Continue-As-New is unaffected either way, which is what\n" +
				" frees the decision to be made on meaning: the whole node travels inside the\n" +
				" spec, and a shaped value is recorded in `Workflow_StepOutputs` like any\n" +
				" other step output. What compaction *does* need is that the references these\n" +
				" expressions make are collected. See `CollectNodeRefs`.\n",
		},
		{
			Name: "flowstate.v1.Signal.prompt",
			Leading: " Prompt is what this gate is asking for, in the author's own words, carried\n" +
				" to whoever is being asked.\n" +
				"\n" +
				" A gate could say which signal releases it and could not say what agreeing\n" +
				" to it means. `deploy-approved` is a routing key, not a question: an\n" +
				" operator holding a run id learned the name to send and nothing about what\n" +
				" they would be approving. This is the sentence that was missing, and it\n" +
				" travels on `PendingWait.prompt` so every surface that reports a parked gate\n" +
				" reports it.\n" +
				"\n" +
				" An expression rather than a literal string, because the interesting part of\n" +
				" an approval is the particulars: `${\"deploy %s to %s?\".format([inputs.version,\n" +
				" inputs.environment])}` says which build and which environment, and a fixed\n" +
				" string cannot. A plain unfenced string is still a plain string, exactly as\n" +
				" it is in every other input position.\n" +
				"\n" +
				" # When it is evaluated, and what it sees\n" +
				"\n" +
				" Once, at the moment the wait begins parking, on both drivers - the same\n" +
				" point the wait announces itself to the reporting registry, and after both\n" +
				" ways a wait can resolve without parking at all (a signal that arrived\n" +
				" early, a bound that had already lapsed). A gate the run walks straight\n" +
				" through evaluates no prompt, because it never asks anybody anything.\n" +
				"\n" +
				" It sees the enclosing scope and [NowIdentifier], the same names\n" +
				" `timeout:` sees. It does *not* see `payload`, `sender` or `timed_out`:\n" +
				" those are the wait's result, and the result does not exist yet when the\n" +
				" question is asked. That asymmetry with `outputs:` is the honest one, and\n" +
				" it is why this is a sibling of that key rather than an entry in it.\n" +
				"\n" +
				" A prompt that fails to evaluate fails the step, exactly as a `timeout:`\n" +
				" that fails to evaluate does. Silently parking with no question is the one\n" +
				" outcome worth refusing: nobody would learn the gate had asked anything, and\n" +
				" an approver would be shown a blank where the decision was supposed to be.\n" +
				"\n" +
				" # Sensitivity, which is why this field is not simply a string\n" +
				"\n" +
				" The evaluated text is rendered into *other people's* clients - an approver\n" +
				" who is not the run's author, and who was given a run id rather than the\n" +
				" file. So the rule the `log:` lint draws at direct surfacing is drawn wider\n" +
				" here: a prompt may not *reach* an input declared `sensitive:` at all, by any\n" +
				" spelling, and may not hold a `${secret(...)}` reference. Both are refused at\n" +
				" compile where they are statically knowable, and refused again fail-closed at\n" +
				" submit by [CheckWaitPromptsAreAskable]. A prompt that still holds a secret\n" +
				" reference when it is evaluated - a specification built in process, never\n" +
				" parsed and never submitted - renders as a refusal rather than as the secret.\n" +
				"\n" +
				" # Bounded\n" +
				"\n" +
				" The evaluated text is bounded by [MaxWaitPromptBytes], read by both drivers\n" +
				" from the package both import. Text past the bound is cut and\n" +
				" `PendingWait.prompt_truncated` says so, because a question a reader cannot\n" +
				" tell was cut short is a question they may answer having read half of it.\n",
		},
		{
			Name: "flowstate.v1.SignalBatch",
			Leading: " SignalBatch names something a workload waits to be told *repeatedly*, and\n" +
				" takes every delivery already buffered in one step.\n" +
				"\n" +
				" # The shape it replaces, and what batching actually saves\n" +
				"\n" +
				" The event-accumulator shape today is `loop:` around `wait_for_signal:`: one\n" +
				" signal per iteration, appended to the loop's `results`. A burst of fifty\n" +
				" orders costs fifty iterations of that loop.\n" +
				"\n" +
				" It is worth being exact about the saving, because the obvious reading is\n" +
				" wrong. A signal costs one `WorkflowExecutionSignaled` event in history\n" +
				" whether it is drained in a batch or consumed one at a time — batching does\n" +
				" *not* remove those, and nothing can: the event is written when the sender's\n" +
				" RPC is accepted, long before any workflow code decides how to read it. What\n" +
				" the per-iteration shape pays *on top* of that is what a batch removes:\n" +
				"\n" +
				"   - a workflow task per iteration (Scheduled/Started/Completed, three events),\n" +
				"     plus the body's own activity events, where a burst drained in one step\n" +
				"     coalesces into a handful of workflow tasks — a burst arriving while a task\n" +
				"     is already pending is delivered into that same task;\n" +
				"   - one `Workflow.StepOutputs` entry per iteration, weighed against\n" +
				"     [MaxLoopResultsBytes] by `AccumulateLoopResult`, where a batch records one.\n" +
				"\n" +
				" So the honest headline is \"fewer workflow tasks and one results entry instead\n" +
				" of N\", not \"fewer signal events\".\n" +
				"\n" +
				" # A separate message from Signal, rather than a drain flag on it\n" +
				"\n" +
				" By exactly the argument `Signal.outputs` makes for sitting on [Signal] rather\n" +
				" than on [Wait]: a drain binds `deliveries` and `count`, and does *not* bind\n" +
				" `payload` or `sender`. A flag inside [Signal] would make every `outputs:`\n" +
				" expression's validity depend on the value of a sibling key — the reported\n" +
				" refusal that comment rejects in favour of a structural one.\n" +
				"\n" +
				" # Admission is unaffected, and deliberately so\n" +
				"\n" +
				" `SignalPolicyCheck` and `CheckSignalPayloadSize` run at the `Signal` RPC,\n" +
				" before a delivery ever reaches a channel. Every delivery in a batch was\n" +
				" individually admitted by the same policy, against the sender the server\n" +
				" attested for it. A batch therefore cannot route around per-sender policy,\n" +
				" because the policy is not at receive time — there is nothing new to enforce\n" +
				" here, only something to keep true.\n",
		},
		{
			Name: "flowstate.v1.SignalBatch.name",
			Leading: " Name is what a sender addresses, under exactly `Signal.name`'s rules — the\n" +
				" same channel, read a different way.\n",
		},
		{
			Name: "flowstate.v1.SignalBatch.max_batch",
			Leading: " MaxBatch bounds how many deliveries one drain takes. Zero means\n" +
				" [MaxPendingSignals], which is also the ceiling.\n" +
				"\n" +
				" Bounded here rather than trusted, because a signal burst is peer-controlled\n" +
				" input and the batch is the multiplication: the count is what the far side\n" +
				" chooses, and bytes follow from it — each delivery is already bounded by\n" +
				" [MaxSignalPayloadBytes] at admission, so a bounded count bounds the whole.\n" +
				" A bounded `int32` in the manner of `ForEach.max_parallel`, for the same\n" +
				" reason: bound the resource the peer controls.\n" +
				"\n" +
				" Deliveries past the bound are *not* dropped and *not* re-buffered — they\n" +
				" are simply left on the channel, so the next drain takes them. That is what\n" +
				" a `loop:` around this already wants, and it means a bound being reached\n" +
				" costs an iteration rather than an approval.\n",
		},
		{
			Name: "flowstate.v1.SignalBatch.outputs",
			Leading: " Outputs shapes what the waiting step produces, exactly as `Signal.outputs`\n" +
				" does — same evaluator, same single moment, same replace-not-extend rule.\n" +
				"\n" +
				" What differs is the names it binds, and that difference is why this is a\n" +
				" separate message: `deliveries` (a list of `{payload, sender}` maps, oldest\n" +
				" first), `count`, and `timed_out`, plus `now`. There is no `payload` and no\n" +
				" `sender`, because a batch has many of each.\n",
		},
		{
			Name: "flowstate.v1.SignalBatch.prompt",
			Leading: " Prompt is what this gate is asking for, under `Signal.prompt`'s whole\n" +
				" contract: evaluated once at the moment the wait parks, seeing the enclosing\n" +
				" scope and `now` and not the wait's result, bounded by [MaxWaitPromptBytes],\n" +
				" and refused any reach to a `sensitive:` input or a `${secret(...)}` by\n" +
				" [CheckWaitPromptsAreAskable].\n",
		},
		{
			Name: "flowstate.v1.SignalBatch.quorum",
			Leading: " Quorum turns the wait into a decision: \"two of these three must approve\",\n" +
				" with distinct approvers, a veto, and a record of who approved.\n" +
				"\n" +
				" Absent, the wait is the burst drain above and nothing about it changes.\n" +
				" Present, it *replaces* the drain's shape (a first delivery and then\n" +
				" whatever is already queued) with a loop that takes one delivery at a time\n" +
				" until the quorum is decided or the wait's `timeout:` lapses; see\n" +
				" [SignalQuorum] for how a delivery counts. Deliveries after the decision are\n" +
				" not taken by this wait and stay on the channel for a later one, exactly as a\n" +
				" delivery beyond `max_batch` does.\n" +
				"\n" +
				" A quorum wait's outputs are the batch's three (`deliveries`, `count`,\n" +
				" `timed_out`) plus `decision`, `approvals` and `vetoed_by`; `outputs:` shapes\n" +
				" them and sees all six. `max_batch` is the bound on `approve`.\n",
		},
		{
			Name: "flowstate.v1.SignalQuorum",
			Leading: " SignalQuorum says how many approvals decide a `wait_for_signals:`, who may\n" +
				" count toward them, and what ends the wait early.\n" +
				"\n" +
				" # What counts\n" +
				"\n" +
				" A delivery is an *approval* when its payload's `approved` is boolean true,\n" +
				" which is exactly what the browser gate page sends. It is a *veto* when\n" +
				" [veto] is true for it (by default, when its payload's `approved` is boolean\n" +
				" false). A delivery that is neither is ignored: it is consumed by the wait and\n" +
				" reported in `deliveries`, but it moves nothing.\n" +
				"\n" +
				" A veto is checked first and ends the wait at once, whatever the count, so a\n" +
				" delivery that is both a veto and an approval vetoes. Admission is not\n" +
				" repeated here: the `signals:` policy refuses a sender before a delivery ever\n" +
				" reaches a wait, on both drivers, so a refused sender can neither approve nor\n" +
				" veto, and everything this message decides is about deliveries the policy\n" +
				" already let through.\n" +
				"\n" +
				" # Evaluated the same on both drivers\n" +
				"\n" +
				" The decision is one pure tally in `pkg/flowstate/v1` that both drivers call\n" +
				" as each delivery is taken, with [exclude] and [veto] evaluated by the same\n" +
				" evaluator that evaluates the batch's own `prompt:` and `outputs:`. Each sees\n" +
				" the enclosing scope (`run`, `inputs`, `steps`, ...), `now`, and the delivery\n" +
				" bound bare as `payload` and `sender`, as `outputs:` binds a single wait's.\n",
		},
		{
			Name: "flowstate.v1.SignalQuorum.approve",
			Leading: " Approve is how many counted approvals complete the wait. At least one, and\n" +
				" no more than the batch's bound (a quorum is counted among at most that many\n" +
				" deliveries), which the enclosing [SignalBatch]'s own constraint checks.\n",
		},
		{
			Name: "flowstate.v1.SignalQuorum.distinct",
			Leading: " Distinct requires each counted approval to come from a different sender.\n" +
				" Unset means true: a quorum that one person could meet by approving twice is\n" +
				" almost never what was meant, so the safe reading is the default and\n" +
				" `distinct: false` is the spelling that opts out.\n" +
				"\n" +
				" A sender is the verified identity's subject qualified by its issuer (see\n" +
				" `QualifiedSubject`), the same comparison the `signals:` policy uses. A\n" +
				" delivery with no identity subject (a local or unattested one) has nothing\n" +
				" to be distinct by, so under a distinct quorum it never counts as an approval\n" +
				" and is ignored: it fails closed rather than being counted as an anonymous\n" +
				" somebody. A repeat approval from an already-counted sender is ignored too,\n" +
				" and a later delivery from that sender is still considered for a veto.\n",
		},
		{
			Name: "flowstate.v1.SignalQuorum.exclude",
			Leading: " Exclude lists expressions naming subjects whose approvals do not count, the\n" +
				" way four-eyes is spelled: `${run.identity.subject}` ignores the run\n" +
				" starter's own approval. Each is evaluated for every delivery and must\n" +
				" produce a string or a list of strings; a delivery whose identity subject\n" +
				" equals any of them is not counted as an approval. It still can veto.\n" +
				"\n" +
				" An expression that does not evaluate, or produces anything else, fails the\n" +
				" step: silently counting an approval an author asked to exclude is the\n" +
				" direction this must not fail in. A delivery with an empty subject matches an\n" +
				" empty excluded subject, so an unattested sender never slips past a run whose\n" +
				" own starter is anonymous.\n",
		},
		{
			Name: "flowstate.v1.SignalQuorum.veto",
			Leading: " Veto is one boolean expression over the delivery that ends the wait with\n" +
				" decision `vetoed` when it is true. Omitted, a delivery whose payload\n" +
				" `approved` is boolean false vetoes. A delivery is checked for a veto before\n" +
				" it is considered an approval, whatever its subject.\n",
		},
		{
			Name: "flowstate.v1.SignalSender",
			Leading: " SignalSender is who the server attests sent a signal, never what the\n" +
				" sender's own payload claims.\n" +
				"\n" +
				" Two separate things travel with every signal, and they must never merge into\n" +
				" one map: `payload` is what the sender chose to send, unchanged and untrusted;\n" +
				" `sender` is what the server itself established about the caller before it\n" +
				" ever looked at the payload. A workflow author writes conditions against\n" +
				" `sender` (`sender.identity.subject != inputs.requested_by` for separation of\n" +
				" duties) and treats `payload` as evidence rather than identity.\n" +
				"\n" +
				" Identity reuses [WorkloadIdentity] rather than a parallel type: a signal's\n" +
				" sender and a run's own caller are the same kind of fact (someone acting,\n" +
				" established by authentication rather than self-report), and a run's identity\n" +
				" is already this message. Two messages for one shape is exactly the drift\n" +
				" ARCHITECTURE.md invariant 1 (proto-first) exists to prevent.\n" +
				"\n" +
				" Absent entirely on a signal that predates this field (identity unset,\n" +
				" accepted_at unset, local false), which reads as unattested. That is correct,\n" +
				" because no signal recorded before this field existed could have carried one.\n" +
				" There is no compatibility arm: an old signal simply has nothing here.\n",
		},
		{
			Name: "flowstate.v1.SignalSender.identity",
			Leading: " Identity is the authenticated caller the server established for this\n" +
				" signal, by the same path a run's own identity is established\n" +
				" (`FlowstateServer.identityFor`, via `authorizeRun`). Never taken from the\n" +
				" request: a caller who could name their own identity could name anyone\n" +
				" else's, which is the exact defect this message exists to close.\n",
		},
		{
			Name: "flowstate.v1.SignalSender.accepted_at",
			Leading: " AcceptedAt is when the server accepted the signal, from the server's own\n" +
				" clock, never the sender's. A self-reported time is exactly the kind of\n" +
				" claim this field replaces with something attested.\n",
		},
		{
			Name: "flowstate.v1.SignalSender.local",
			Leading: " Local marks a signal delivered to a local run (`flow run local --signal`\n" +
				" or `flow test`'s scripted signals), which has no authenticated caller at\n" +
				" all: there is no server in front of it to attest anything. Set only by\n" +
				" [LocalSignalSender]; the durable driver never sets it true.\n" +
				"\n" +
				" A wait's rendered `sender.local` output (see wait.go's signalSenderValue)\n" +
				" is `true` for this case *and* for every other case where nothing was\n" +
				" attested at all: this message absent entirely, which covers a signal\n" +
				" that predates this field, a timed-out wait with nothing pending, and the\n" +
				" engine's own compatibility fallback for a signal that arrived in the\n" +
				" older wire shape (engine/signal_compat.go). All of those are the same\n" +
				" fact from a workflow author's point of view (nobody attested this), and\n" +
				" must read the same way, distinct from an attested-but-anonymous caller\n" +
				" (this message present, Local false, Identity.Subject merely empty because\n" +
				" no identity provider is configured). This field's own wire value only\n" +
				" ever means \"the local driver,\" never \"nothing was attested\"; the broader\n" +
				" reading exists solely in the rendered output, precisely so a workflow\n" +
				" author can trust `!sender.local` as \"the server accepted this.\"\n",
		},
		{
			Name: "flowstate.v1.SignalSender.delivery_id",
			Leading: " DeliveryID names the webhook delivery this signal came from, empty for\n" +
				" every sender that is not one.\n" +
				"\n" +
				" The digest `WebhookDeliveryID` computes over the trigger's evaluated\n" +
				" `idempotency_key:`, never the key itself: the usual key is a signature\n" +
				" header, and this value is written into durable run state, where\n" +
				" credential-shaped material may not go (ARCHITECTURE.md invariant 7). A digest is fixed-length,\n" +
				" alphabet-safe, and says nothing about the key it names.\n" +
				"\n" +
				" It is here rather than in `Principal.claims` because it is not a\n" +
				" claim about a principal — every delivery from one trigger attests the same\n" +
				" principal and carries a different one of these. What it is for is the\n" +
				" engine's own dedupe: a run records the ids it has consumed\n" +
				" (`RunState.consumed_delivery_ids`) so that a redelivery after the gate has\n" +
				" already been answered is dropped rather than taken by the next\n" +
				" `wait_for_signal:` a `loop:` comes back around to.\n",
		},
	})
}
