// Code generated by protoc-gen-flowstate-doc. DO NOT EDIT.
// source: flowstate/v1/service.proto

package protodoc

import (
	registry "github.com/picatz/flowstate/pkg/flowstate/v1/protodoc/registry"
)

func init() {
	registry.RegisterFile("flowstate/v1/service.proto", []registry.Comment{
		{
			Name:    "flowstate.v1.RunRequest",
			Leading: " RunRequest is the request message for running a workflow.\n",
		},
		{
			Name: "flowstate.v1.RunRequest.workflow",
			Leading: " Workflow is the compiled specification to run: the `workflow` a\n" +
				" [CompileResponse] carries, passed unchanged. Flowfile source is not\n" +
				" accepted here; compile it first.\n",
		},
		{
			Name: "flowstate.v1.RunRequest.inputs",
			Leading: " Inputs are the arguments this run is started with, keyed by the name an\n" +
				" [InputDeclaration] on the workflow gave. At most 64.\n" +
				"\n" +
				" Every [Value] must be a `literal`. An `expr` or a `secret_ref` is refused:\n" +
				" these arrive from the caller, and a caller must not choose code the server\n" +
				" evaluates or which credential a run resolves.\n" +
				"\n" +
				" The server checks the inputs against the workflow's declarations before\n" +
				" the run starts and refuses the request if any check fails: every required\n" +
				" input present, no undeclared name, every value of the declared type.\n" +
				" Defaults are filled in for inputs left out.\n" +
				"\n" +
				" Inputs become part of the run's state and count toward its size bound\n" +
				" (ARCHITECTURE.md invariant 9: a run that cannot continue must fail, not\n" +
				" hang).\n",
		},
		{
			Name: "flowstate.v1.RunRequest.entity_key",
			Leading: " EntityKey addresses the run by a stable business key, such as an order id\n" +
				" or a subscription id, instead of a generated id.\n" +
				"\n" +
				" Set, the run's workflow id is `flowstate-entity-<namespace>_<entity_key>`,\n" +
				" so the workload can be found again by what it is. While a run under that\n" +
				" id is still running, another Run with the same key in the same tenant is\n" +
				" refused: there is at most one live workload per key per tenant. Unset, the\n" +
				" server generates a `flowstate-workflow-<uuid>` id.\n" +
				"\n" +
				" The namespace half always comes from the caller's authenticated identity,\n" +
				" never from the request, so a caller cannot address or collide with\n" +
				" another tenant's entity.\n" +
				"\n" +
				" Lowercase ASCII letters, digits and `-`, not starting with `-`, 1 to 128\n" +
				" characters. The namespace grammar is the same and permits no `_`, so the\n" +
				" `_` joining the two halves is unambiguous.\n" +
				"\n" +
				" The key is plaintext metadata, never a secret: a workflow id is indexed\n" +
				" and shown in every listing and is not covered by payload encryption.\n",
		},
		{
			Name: "flowstate.v1.RunRequest.reason",
			Leading: " Reason is why a person is starting this run, recorded on it. Free text, at\n" +
				" most 512 characters.\n" +
				"\n" +
				" Required when the workflow declares `manual: {require_reason: true}` (see\n" +
				" `ManualTrigger.require_reason`) and ignored otherwise. It is recorded for\n" +
				" whoever reads the run later and is not visible to expressions; a value the\n" +
				" workflow computes with belongs in `inputs`.\n",
		},
		{
			Name: "flowstate.v1.RunRequest.request_id",
			Leading: " RequestId makes this submission idempotent: two Run calls carrying the same\n" +
				" value in the same namespace produce one run, and the second is answered\n" +
				" with the run the first started, `RunResponse.reused` set.\n" +
				"\n" +
				" Use it whenever a submission may be retried: a caller whose request timed\n" +
				" out cannot tell \"never started\" from \"started and the answer was lost\", and\n" +
				" a retry without this field starts the workload a second time. `flow run`\n" +
				" sends a fresh value on every invocation and reuses it across its own\n" +
				" retries; `--request-id` supplies a caller's own, such as a CI job's run id.\n" +
				"\n" +
				" Unset, the run gets a generated `flowstate-workflow-<uuid>` id. Set, the\n" +
				" workflow id is `flowstate-request-<hex>`, derived by digest from the\n" +
				" caller's authenticated namespace and this value, and the cluster's own\n" +
				" uniqueness on that id is the deduplication. A request id names one\n" +
				" submission forever: a retry that arrives after the run finished is answered\n" +
				" with the finished run.\n" +
				"\n" +
				" When the request also names an `entity_key`, or the workflow declares a\n" +
				" `concurrency:` block, that address decides the run's id. This field then\n" +
				" decides only whether a submission colliding with a live run is a retry of\n" +
				" the submission that started it (answered with that run, `reused` set) or a\n" +
				" new submission, which the address's own rule handles.\n" +
				"\n" +
				" A reused value with a different submission is refused with\n" +
				" `AlreadyExists`, naming the run. The run records a digest of the\n" +
				" specification and bound inputs it started with, and a later request whose\n" +
				" digest differs is not treated as a retry. Choose a new value for a new\n" +
				" submission.\n" +
				"\n" +
				" Under `on_conflict: terminate_other`, two identical submissions racing each\n" +
				" other are deduplicated by the cluster rather than terminating each other's\n" +
				" run. This requires Temporal Server 1.24 or later and a server whose\n" +
				" Temporal client applies Flowstate's start interceptor; otherwise such a\n" +
				" replacement is refused with `FailedPrecondition` before anything is\n" +
				" terminated.\n" +
				"\n" +
				" A UUID or a string of 1 to 128 ASCII letters, digits and `.`, `_`, `:`,\n" +
				" `/` or `-`, starting with a letter or digit. The value is digested, never\n" +
				" interpolated into an id, and is recorded on the run only as that digest.\n",
		},
		{
			Name:    "flowstate.v1.RunResponse",
			Leading: " RunResponse is the response message for a workflow run.\n",
		},
		{
			Name: "flowstate.v1.RunResponse.workflow_id",
			Leading: " WorkflowId is the durable handle for the workload, which every other RPC\n" +
				" addressing a run takes. It is `flowstate-workflow-<uuid>` for an ordinary\n" +
				" run, `flowstate-request-<hex>` for one started with\n" +
				" `RunRequest.request_id`, and `flowstate-entity-<namespace>_<entity_key>`\n" +
				" for one started with `RunRequest.entity_key`. At most 256 bytes, the\n" +
				" bound every request addressing a run holds its `workflow_id` to.\n",
		},
		{
			Name: "flowstate.v1.RunResponse.run_id",
			Leading: " RunId is the UUID of this execution of the workload. A workload that\n" +
				" continues as new gets a new run id per segment, so address a workload by\n" +
				" `workflow_id` and use a run id only to name one segment.\n",
		},
		{
			Name: "flowstate.v1.RunResponse.status",
			Leading: " Status is the run's status when this response was produced. Run answers\n" +
				" without waiting, so a newly started run reports STATUS_RUNNING; a reused\n" +
				" or joined run reports its current status, which may already be final.\n",
		},
		{
			Name:    "flowstate.v1.RunResponse.error",
			Leading: " Error is why the run failed.\n",
		},
		{
			Name:    "flowstate.v1.RunResponse.outputs",
			Leading: " Outputs are the outputs of the steps that have run, keyed by step id.\n",
		},
		{
			Name: "flowstate.v1.RunResponse.specification_as_submitted",
			Leading: " SpecificationAsSubmitted is the server saying whether the run it just\n" +
				" started executes the specification this caller sent, unchanged.\n" +
				"\n" +
				" It may not: a deployment can register its own trusted workflow under the\n" +
				" name a caller submits and run that copy instead, and the server writes its\n" +
				" plugin version selection onto what it runs. A client renders a run's\n" +
				" outputs against its own copy's `sensitive: true` declarations, which is\n" +
				" safe only when its copy is the one that ran. The comparison ignores\n" +
				" `resolved_task_capabilities` when the caller omitted it.\n" +
				"\n" +
				" True means the executed specification is the submitted one. False means\n" +
				" it is not. Unset means the server did not say (an older server); treat it\n" +
				" exactly like false. The executed specification itself is never returned.\n",
		},
		{
			Name: "flowstate.v1.RunResponse.joined",
			Leading: " Joined is true when this response describes a run that was already going\n" +
				" rather than one this request started.\n" +
				"\n" +
				" Only `on_conflict: join` produces it: the workflow declared a\n" +
				" `concurrency:` key, another run already held that key in this tenant, and\n" +
				" the workflow asked for that run to be returned instead of a refusal.\n" +
				" `workflow_id` and `run_id` then name a run this caller did not start,\n" +
				" possibly with other inputs, and `specification_as_submitted` describes\n" +
				" that run's specification. False when this request started the run.\n",
		},
		{
			Name: "flowstate.v1.RunResponse.reused",
			Leading: " Reused is true when this response describes the run an earlier request\n" +
				" carrying the same `RunRequest.request_id` already started, rather than one\n" +
				" this request started.\n" +
				"\n" +
				" On a reused run, `status` is the run's current status, which may already\n" +
				" be final, and `specification_as_submitted` is false because the\n" +
				" specification that ran is the one the earlier attempt sent. Unlike\n" +
				" `joined`, a reused run is this caller's own submission, checked to be the\n" +
				" same one by digest.\n",
		},
		{
			Name:    "flowstate.v1.RunResponse.kind",
			Leading: " Kind is the run's result: `error` for a failed run, otherwise `outputs`.\n",
		},
		{
			Name:    "flowstate.v1.RunResponse.Error",
			Leading: " Error describes why a run failed.\n",
		},
		{
			Name:    "flowstate.v1.RunResponse.Error.message",
			Leading: " Message is the failure in words, for a person to read. Always set.\n",
		},
		{
			Name: "flowstate.v1.RunResponse.Error.kind",
			Leading: " Kind classifies the failure so a program can decide what to do without\n" +
				" parsing `message`. One of:\n" +
				"\n" +
				"   - `InvalidInput`: inputs do not satisfy a task's schema. Fix the\n" +
				"     workflow or its inputs; retrying cannot help.\n" +
				"   - `UnknownTask`: the workflow names a task no worker provides.\n" +
				"   - `Expression`: an expression failed to parse, exceeded its cost\n" +
				"     budget, or referenced something that does not exist.\n" +
				"   - `PolicyDenied`: a policy refused the operation, such as an egress\n" +
				"     rule. Do not retry.\n" +
				"   - `LimitExceeded`: a resource bound was hit, such as a response larger\n" +
				"     than the configured maximum.\n" +
				"   - `UpstreamUnknown`: a request was sent and no answer came back, so the\n" +
				"     dependency may or may not have applied it. Check before resubmitting.\n" +
				"   - `Upstream`: a dependency failed in a way that may be transient.\n" +
				"   - `Timeout`: a step's time budget expired.\n" +
				"   - `RunTimeout`: the whole run's time budget expired. Earlier steps may\n" +
				"     already have had effects, so decide before starting it again.\n" +
				"   - `RateLimited`: a dependency refused the request as too frequent.\n" +
				"   - `Internal`: a defect in Flowstate, or a failure it could not\n" +
				"     otherwise classify.\n" +
				"\n" +
				" `Upstream`, `Timeout`, `RateLimited` and `Internal` are the retryable\n" +
				" kinds; the rest are permanent. Always set alongside `message`.\n",
		},
		{
			Name:    "flowstate.v1.RunResponse.Status",
			Leading: " Status is where a run is in its lifecycle.\n",
		},
		{
			Name:    "flowstate.v1.RunResponse.STATUS_UNSPECIFIED",
			Leading: " STATUS_UNSPECIFIED is never sent.\n",
		},
		{
			Name: "flowstate.v1.RunResponse.STATUS_RUNNING",
			Leading: " STATUS_RUNNING means the run has started and not finished, including\n" +
				" while it waits for a signal or a timer.\n",
		},
		{
			Name:    "flowstate.v1.RunResponse.STATUS_COMPLETED",
			Leading: " STATUS_COMPLETED means every step finished and the run succeeded.\n",
		},
		{
			Name:    "flowstate.v1.RunResponse.STATUS_FAILED",
			Leading: " STATUS_FAILED means the run ended with an error; `error` says why.\n",
		},
		{
			Name:    "flowstate.v1.RunResponse.STATUS_CANCELED",
			Leading: " STATUS_CANCELED means the run stopped in response to a Cancel request.\n",
		},
		{
			Name: "flowstate.v1.RunResponse.STATUS_TERMINATED",
			Leading: " STATUS_TERMINATED means the run was stopped by Terminate, without\n" +
				" cleanup.\n",
		},
		{
			Name:    "flowstate.v1.RunResponse.STATUS_TIMED_OUT",
			Leading: " STATUS_TIMED_OUT means the run's overall time budget expired.\n",
		},
		{
			Name:    "flowstate.v1.GetRequest",
			Leading: " GetRequest is the request message for getting a workflow run.\n",
		},
		{
			Name: "flowstate.v1.GetRequest.workflow_id",
			Leading: " WorkflowId identifies the workload, as Run's `workflow_id` reports it.\n" +
				" 1 to 256 bytes. The caller may read only runs in its own tenant.\n",
		},
		{
			Name: "flowstate.v1.GetRequest.run_id",
			Leading: " RunId optionally pins the read to one run of the workload, as a UUID.\n" +
				" Unset reads the latest run, which is what a caller holding only a\n" +
				" workflow id wants.\n",
		},
		{
			Name:    "flowstate.v1.GetResponse",
			Leading: " GetResponse is the response message for getting a workflow run.\n",
		},
		{
			Name:    "flowstate.v1.GetResponse.workflow_id",
			Leading: " WorkflowId is the workload this describes.\n",
		},
		{
			Name:    "flowstate.v1.GetResponse.run_id",
			Leading: " RunId is the run this describes: the one requested, or the latest.\n",
		},
		{
			Name:    "flowstate.v1.GetResponse.status",
			Leading: " Status is the run's current status.\n",
		},
		{
			Name:    "flowstate.v1.GetResponse.error",
			Leading: " Error is why the run failed.\n",
		},
		{
			Name:    "flowstate.v1.GetResponse.outputs",
			Leading: " Outputs are the outputs of the steps that have run, keyed by step id.\n",
		},
		{
			Name: "flowstate.v1.GetResponse.start_time",
			Leading: " StartTime is when the workload began. For a workload that continued as\n" +
				" new, this is the first segment's start.\n",
		},
		{
			Name: "flowstate.v1.GetResponse.close_time",
			Leading: " CloseTime is when the run finished. Unset while it is still running, so\n" +
				" \"has not finished\" is never confused with a real time.\n",
		},
		{
			Name: "flowstate.v1.GetResponse.progress",
			Leading: " Progress is where a running run has got to. Unset for any other status, since a\n" +
				" finished run's position is its outputs.\n" +
				"\n" +
				" Unset does not mean \"at the beginning\". It also means no worker answered, or\n" +
				" that the run is on an interpreter built before this existed: facts about the\n" +
				" deployment rather than about the workload. A reader that rendered an unanswered\n" +
				" query as \"step 1 of 5\" would be inventing one.\n",
		},
		{
			Name: "flowstate.v1.GetResponse.pending_activities",
			Leading: " PendingActivities are the steps Temporal is retrying right now, with why the\n" +
				" last attempt failed and when the next one is due.\n" +
				"\n" +
				" This answers \"why has this been RUNNING for so long\". Set only for a\n" +
				" RUNNING run. Empty for a running run means nothing is mid-retry: the run is\n" +
				" waiting or between steps, not stuck.\n",
		},
		{
			Name: "flowstate.v1.GetResponse.pending_activities_truncated",
			Leading: " PendingActivitiesTruncated is true when this run is retrying more steps\n" +
				" than `pending_activities` reports.\n" +
				"\n" +
				" The list and each entry's message are bounded, and this flag says the\n" +
				" bound was reached, so a reader never mistakes some of the retrying steps\n" +
				" for all of them.\n",
		},
		{
			Name: "flowstate.v1.GetResponse.run_outputs",
			Leading: " RunOutputs are the values the workflow declared under `outputs:`, computed\n" +
				" by this run: the answer, as against the per-step transcript in `outputs`.\n" +
				"\n" +
				" Unset when the workflow declares no outputs, when the run has not\n" +
				" finished, or when the run was started by a build that did not record them.\n",
		},
		{
			Name: "flowstate.v1.GetResponse.entity_state",
			Leading: " EntityState is a bounded snapshot of a RUNNING run's carried state: its\n" +
				" top-level `vars:` and the value each active `loop:` carries between\n" +
				" iterations, read from the worker by a query.\n" +
				"\n" +
				" This is how to read the state of an entity (a `loop:` with a\n" +
				" `wait_for_signal:` that is never meant to finish), which is always\n" +
				" RUNNING and so never has outputs. Set only for a RUNNING run; a finished\n" +
				" run's state is its outputs.\n",
		},
		{
			Name: "flowstate.v1.GetResponse.starter",
			Leading: " Starter is who submitted this run, as the qualified `issuer#subject` string\n" +
				" the server recorded on it at submit.\n" +
				"\n" +
				" The raw qualified form, because that is what a signal policy rule's\n" +
				" `subject` names: compare it to a rule or to a caller's identity with string\n" +
				" equality. A display form that drops the issuer would compare equal to a\n" +
				" subject from a different identity provider.\n" +
				"\n" +
				" Empty when the run's starter was never recorded or could not be read.\n" +
				" Empty is \"unknown\", never an identity. Authorization does not read this\n" +
				" field; a `distinct_from_starter` signal policy denies when the starter is\n" +
				" unknown.\n",
		},
		{
			Name: "flowstate.v1.GetResponse.first_run_id",
			Leading: " FirstRunId is the segment the workload began at. Equal to run_id for a run\n" +
				" that never continued as new; where it differs, run_id names the segment\n" +
				" this response reports and first_run_id is where to start reading the\n" +
				" workload's whole timeline.\n",
		},
		{
			Name: "flowstate.v1.GetResponse.segments",
			Leading: " Segments is how many Continue-As-New segments the workload has run as,\n" +
				" this one included, with RunSummary.segments' meaning: two or more when\n" +
				" the interpreter recorded the chain, and zero when it recorded none —\n" +
				" which is every run that never continued as new, since a first segment\n" +
				" writes no count, as well as a chain whose first segment predates the\n" +
				" count. A client must not assume it is at least one; first_run_id against\n" +
				" run_id says whether a run with no count continued at all.\n",
		},
		{
			Name:    "flowstate.v1.GetResponse.kind",
			Leading: " Kind is the run's result: `error` for a failed run, otherwise `outputs`.\n",
		},
		{
			Name:    "flowstate.v1.SignalRequest",
			Leading: " SignalRequest delivers a signal to a waiting run.\n",
		},
		{
			Name: "flowstate.v1.SignalRequest.workflow_id",
			Leading: " WorkflowId identifies the workload to signal, as Run's `workflow_id`\n" +
				" reports it. 1 to 256 bytes.\n" +
				"\n" +
				" A caller may address only runs in its own tenant. The namespace always\n" +
				" comes from the caller's authenticated identity, never from the request.\n",
		},
		{
			Name: "flowstate.v1.SignalRequest.run_id",
			Leading: " RunId optionally pins the signal to one run of the workload, as a UUID.\n" +
				" Leave it empty: empty addresses whichever run is current, and a pinned run\n" +
				" id is refused once the workload has continued as new.\n",
		},
		{
			Name: "flowstate.v1.SignalRequest.name",
			Leading: " Name is the signal being sent: the `name:` the waiting `wait_for_signal:`\n" +
				" step declared, which Get reports as each open gate's signal name.\n" +
				" Letters, digits, `-` and `_`, starting with a letter or digit, at most 128\n" +
				" characters.\n",
		},
		{
			Name: "flowstate.v1.SignalRequest.payload",
			Leading: " Payload is the data delivered with the signal: named values the waiting\n" +
				" step reads as `${steps.<id>.payload.<key>}`, where `<id>` is that step's\n" +
				" id (a step with its own `outputs:` shaping exposes only what that shaping\n" +
				" selects). Each value is a [Value] holding a `literal`; in JSON, an approval is\n" +
				" `{\"namedValues\": {\"approved\": {\"literal\": {\"boolValue\": true}}}}`. It is\n" +
				" untrusted input to the workflow and never carries the sender's identity.\n",
		},
		{
			Name: "flowstate.v1.SignalResponse",
			Leading: " SignalResponse is empty: a delivered signal has nothing to report.\n" +
				"\n" +
				" It says the cluster accepted the signal for the workload, not that a waiting\n" +
				" step consumed it or that whatever the payload asks for has happened. To learn\n" +
				" what the run did with it, read the run back with the Get RPC.\n",
		},
		{
			Name: "flowstate.v1.SignalWithStartRequest",
			Leading: " SignalWithStartRequest delivers a signal to an entity, creating it first if it\n" +
				" does not yet exist.\n" +
				"\n" +
				" Atomic: two callers racing on the same key produce one entity, and the\n" +
				" signal that created an entity is part of its starting state, so it is never\n" +
				" lost. A separate check-then-Run-or-Signal can always be beaten between the\n" +
				" two calls.\n" +
				"\n" +
				" Two authorization decisions, both fail-closed. Delivering the signal is\n" +
				" authorized by the signal policy the existing entity declared, exactly as\n" +
				" the Signal RPC authorizes it. Creating the entity is authorized exactly as\n" +
				" the Run RPC authorizes a run: every check Run performs on `workflow` and\n" +
				" `inputs` runs here before either branch is taken.\n" +
				"\n" +
				" `workflow` and `inputs` are used only when this call creates the entity;\n" +
				" see [SignalWithStartResponse.Created]. When the entity already exists they\n" +
				" are ignored.\n",
		},
		{
			Name: "flowstate.v1.SignalWithStartRequest.entity_key",
			Leading: " EntityKey addresses the entity, composed with the caller's own namespace\n" +
				" exactly as `RunRequest.entity_key` is: same grammar, same workflow id.\n",
		},
		{
			Name: "flowstate.v1.SignalWithStartRequest.workflow",
			Leading: " Workflow is the specification to start the entity from if it does not\n" +
				" already exist. Checked exactly as `RunRequest.workflow` is (the same\n" +
				" validation, the same signal-policy shape check, the same size bound)\n" +
				" and ignored entirely if the entity is already running.\n",
		},
		{
			Name: "flowstate.v1.SignalWithStartRequest.inputs",
			Leading: " Inputs seed the entity's arguments if it does not already exist. Checked\n" +
				" exactly as `RunRequest.inputs` is, and ignored if the entity is already\n" +
				" running: an existing entity's inputs were bound once, at its own\n" +
				" creation, and this call cannot rebind them.\n",
		},
		{
			Name: "flowstate.v1.SignalWithStartRequest.name",
			Leading: " Name is the signal to deliver, matching what a waiting step declared:\n" +
				" the same field, the same grammar, as `SignalRequest.name`.\n",
		},
		{
			Name:    "flowstate.v1.SignalWithStartRequest.payload",
			Leading: " Payload becomes the waiting step's outputs, exactly as `SignalRequest.payload`.\n",
		},
		{
			Name: "flowstate.v1.SignalWithStartResponse",
			Leading: " SignalWithStartResponse identifies the entity the signal reached, and says\n" +
				" whether this call is what brought it into existence.\n",
		},
		{
			Name: "flowstate.v1.SignalWithStartResponse.workflow_id",
			Leading: " WorkflowId is the entity's workflow id,\n" +
				" `flowstate-entity-<namespace>_<entity_key>`.\n",
		},
		{
			Name:    "flowstate.v1.SignalWithStartResponse.run_id",
			Leading: " RunId is the entity's current run.\n",
		},
		{
			Name: "flowstate.v1.SignalWithStartResponse.created",
			Leading: " Created is true when this call is what brought the entity into existence,\n" +
				" and false when the signal went to an entity that was already running.\n" +
				" `workflow_id` and `run_id` are set the same way in both cases, so this is\n" +
				" the only place the difference is reported.\n",
		},
		{
			Name: "flowstate.v1.SignalWithStartResponse.specification_as_submitted",
			Leading: " SpecificationAsSubmitted is `RunResponse.specification_as_submitted` for\n" +
				" this RPC: the same question and the same three answers.\n" +
				"\n" +
				" When this call created the entity, it says whether the specification the\n" +
				" engine runs is the one sent. When the entity already existed, it is false:\n" +
				" the running entity's specification was not compared against anything.\n",
		},
		{
			Name:    "flowstate.v1.CancelRequest",
			Leading: " CancelRequest asks a run to stop, letting it clean up on the way out.\n",
		},
		{
			Name: "flowstate.v1.CancelRequest.workflow_id",
			Leading: " WorkflowId identifies the workload to cancel, as Run's `workflow_id`\n" +
				" reports it. 1 to 256 bytes. The caller may address only runs in its\n" +
				" own tenant.\n",
		},
		{
			Name: "flowstate.v1.CancelRequest.run_id",
			Leading: " RunId optionally pins the request to one run of the workload, as a UUID.\n" +
				" Empty addresses whichever run is current, which is usually what is wanted.\n",
		},
		{
			Name: "flowstate.v1.CancelResponse",
			Leading: " CancelResponse is empty: the request to stop was accepted, and that is all it\n" +
				" claims.\n" +
				"\n" +
				" Cancellation is cooperative, so this answers that the run has been asked to\n" +
				" stop rather than that it has stopped. Cleanup runs after this returns; poll\n" +
				" the Get RPC for the run's final status.\n",
		},
		{
			Name:    "flowstate.v1.TerminateRequest",
			Leading: " TerminateRequest stops a run immediately, without letting it clean up.\n",
		},
		{
			Name: "flowstate.v1.TerminateRequest.workflow_id",
			Leading: " WorkflowId identifies the workload to terminate, as Run's `workflow_id`\n" +
				" reports it. 1 to 256 bytes. The caller may address only runs in its\n" +
				" own tenant.\n",
		},
		{
			Name: "flowstate.v1.TerminateRequest.run_id",
			Leading: " RunId optionally pins the request to one run of the workload, as a UUID.\n" +
				" Empty addresses whichever run is current.\n",
		},
		{
			Name: "flowstate.v1.TerminateRequest.reason",
			Leading: " Reason is recorded on the terminated execution, at most 1024 characters.\n" +
				" A terminated run records nothing else about why it stopped, so this is the\n" +
				" only account of the decision.\n",
		},
		{
			Name: "flowstate.v1.TerminateResponse",
			Leading: " TerminateResponse is empty: the run is stopped, and there was no cleanup to\n" +
				" report on.\n" +
				"\n" +
				" Unlike [CancelResponse] this is not an acceptance that something will happen\n" +
				" later. Termination is immediate, so the absence of a body here is the absence\n" +
				" of anything further to say, and the account of why it was stopped is the\n" +
				" reason recorded on the execution rather than anything returned to the caller.\n",
		},
		{
			Name:    "flowstate.v1.ListRequest",
			Leading: " ListRequest asks for the caller's runs.\n",
		},
		{
			Name: "flowstate.v1.ListRequest.page_size",
			Leading: " PageSize is the most runs one page returns: 0 (the default) means 50,\n" +
				" and at most 1000.\n" +
				"\n" +
				" It bounds the answer, not the work: a page may come back short, or empty,\n" +
				" with `next_page_token` set. See `ListResponse.next_page_token`.\n",
		},
		{
			Name: "flowstate.v1.ListRequest.page_token",
			Leading: " PageToken continues a previous List: pass the previous response's\n" +
				" `next_page_token`, with the same `filter` and `page_size`. Opaque.\n" +
				"\n" +
				" A token is refused when it comes from another server process, another\n" +
				" tenant, a different `filter` or `page_size`, or is more than a day old;\n" +
				" the refusal says which.\n",
		},
		{
			Name: "flowstate.v1.ListRequest.filter",
			Leading: " Filter keeps only the runs a CEL expression answers true for. Empty keeps\n" +
				" every run. At most 4096 characters.\n" +
				"\n" +
				" The expression can read each run's `workflow_id`, `run_id`, `status`,\n" +
				" `start_time`, `close_time`, `finished`, `name` (the workflow's declared\n" +
				" name), `labels` (a map of the workflow's declared labels), `starter`\n" +
				" (`issuer#subject`) and `worker_version`. `status` is the short name\n" +
				" (`FAILED`, not `STATUS_FAILED`); comparing it to a name no status has is\n" +
				" refused.\n" +
				"\n" +
				"     status == \"FAILED\"\n" +
				"     name == \"nightly-etl\" && status == \"RUNNING\"\n" +
				"     \"team\" in labels && labels[\"team\"] == \"payments\"\n" +
				"     finished && close_time - start_time > duration(\"1h\")\n" +
				"\n" +
				" `close_time` is null while a run is going, and comparing null is an\n" +
				" error; guard it with `finished &&`. Likewise guard a label with\n" +
				" `\"key\" in labels &&`. A run the filter cannot be evaluated for is left\n" +
				" out and counted in `ListResponse.excluded_by_error`.\n" +
				"\n" +
				" A filter narrows the answer, not the scan: the server reads the same\n" +
				" bounded number of runs per call and applies the filter to each, with a\n" +
				" per-run cost limit.\n",
		},
		{
			Name: "flowstate.v1.RunSummary",
			Leading: " RunSummary describes one run in a listing.\n" +
				"\n" +
				" Deliberately not a run's outputs. A listing is about which workloads exist and\n" +
				" what they are doing; reading what one produced is Get, which is one run and one\n" +
				" authorization decision. A list that returned outputs would make \"show me my\n" +
				" runs\" the cheapest way to read every workload's data at once.\n",
		},
		{
			Name: "flowstate.v1.RunSummary.workflow_id",
			Leading: " WorkflowId is the workload's durable handle, which Get and the other run\n" +
				" verbs take.\n",
		},
		{
			Name:    "flowstate.v1.RunSummary.run_id",
			Leading: " RunId is the listed run: the workload's current segment.\n",
		},
		{
			Name:    "flowstate.v1.RunSummary.status",
			Leading: " Status is the run's current status.\n",
		},
		{
			Name: "flowstate.v1.RunSummary.start_time",
			Leading: " StartTime is when the workload began.\n" +
				" For a workload that continued as new, the workload's start rather than the\n" +
				" listed segment's — see segment_start_time.\n",
		},
		{
			Name:    "flowstate.v1.RunSummary.close_time",
			Leading: " CloseTime is when it finished, unset while it is still running.\n",
		},
		{
			Name: "flowstate.v1.RunSummary.name",
			Leading: " Name is the workflow's own declared `name:`, recorded on the run when it\n" +
				" started. Empty only for a run started before names were recorded; a\n" +
				" filter comparing `name` does not match such a run.\n",
		},
		{
			Name: "flowstate.v1.RunSummary.labels",
			Leading: " Labels are the workflow's own declared `labels:`, recorded on the run when\n" +
				" it started.\n" +
				"\n" +
				" Empty for a workflow that declared none and for a run started before\n" +
				" labels were recorded; the two are not distinguished. A filter\n" +
				" `labels[\"team\"] == \"payments\"` does not match such a run, and\n" +
				" `!(\"team\" in labels)` does.\n",
		},
		{
			Name: "flowstate.v1.RunSummary.starter",
			Leading: " Starter is who submitted this run, as the qualified `issuer#subject`\n" +
				" string: the same value, with the same meaning, as `GetResponse.starter`.\n" +
				" Empty when the starter is unknown.\n",
		},
		{
			Name: "flowstate.v1.RunSummary.worker_version",
			Leading: " WorkerVersion is the Worker Deployment version this run is pinned to, as\n" +
				" `deployment-name.build-id`: the pair `flow worker --temporal-deployment-name`\n" +
				" and `--build-id` configure.\n" +
				"\n" +
				" Empty when the run is not pinned to a version, including every run on a\n" +
				" deployment that does not use Worker Deployment Versioning. It can change\n" +
				" at Continue-As-New, when a run moves to the deployment's current version.\n",
		},
		{
			Name: "flowstate.v1.RunSummary.segment_start_time",
			Leading: " SegmentStartTime is when the listed segment itself started. For a\n" +
				" workload that continued as new, this is later than `start_time`, which is\n" +
				" the workload's start. Equal to `start_time` wherever no chain was\n" +
				" recorded (a run that never continued, or a chain whose first segment\n" +
				" predates the record); `segments` is zero in both cases.\n",
		},
		{
			Name: "flowstate.v1.RunSummary.segments",
			Leading: " Segments is how many Continue-As-New segments the workload has run as,\n" +
				" this one included: two or more when the interpreter recorded the chain,\n" +
				" and zero when it recorded none. A first segment writes no count, so a run\n" +
				" that never continued as new reports zero, not one; so does a chain whose\n" +
				" first segment predates the count, whose start_time is then the listed\n" +
				" segment's rather than the workload's. A listing cannot tell those two\n" +
				" apart; a Get can, by first_run_id.\n",
		},
		{
			Name:    "flowstate.v1.ListResponse",
			Leading: " ListResponse returns a page of the caller's runs.\n",
		},
		{
			Name: "flowstate.v1.ListResponse.next_page_token",
			Leading: " NextPageToken continues the listing. Empty means the listing is done.\n" +
				"\n" +
				" Set whenever the scan stopped with more to look at, including when this\n" +
				" page came back short or empty: the server reads a bounded number of runs\n" +
				" per call and keeps the caller's, so in a namespace shared by several\n" +
				" tenants a scan can end with few matches or none while more remain. Keep\n" +
				" calling with this as `ListRequest.page_token` until it is empty.\n",
		},
		{
			Name: "flowstate.v1.ListResponse.excluded_by_error",
			Leading: " ExcludedByError is how many of the caller's runs this page's scan reached\n" +
				" and left out because the filter could not be evaluated over them: an\n" +
				" index into a label the run does not carry, or a comparison against a\n" +
				" close time the run does not have yet.\n" +
				"\n" +
				" Such a run is treated as not matching. The count lets a caller tell\n" +
				" \"nothing matched\" from \"nothing could be asked\". Zero when no filter was\n" +
				" given.\n",
		},
		{
			Name: "flowstate.v1.ListResponse.filter_diagnostic",
			Leading: " FilterDiagnostic says why the filter could not be evaluated, set only when\n" +
				" it could not be evaluated over any of the runs this page reached (usually\n" +
				" a typo). It is the first error the scan met, with the spelling that would\n" +
				" have avoided it when there is one. Empty otherwise.\n",
		},
		{
			Name: "flowstate.v1.ListCursor",
			Leading: " ListCursor is what a page token carries, and is never sent as-is.\n" +
				"\n" +
				" A token is this message serialized, followed by an HMAC-SHA256 over those\n" +
				" bytes under a key the server process derived at startup, base64url-encoded.\n" +
				" The server refuses a token whose authentication code it did not produce, so\n" +
				" a caller cannot construct one and its layout is not a contract. The key is\n" +
				" per process, so a token issued by one server replica is refused by another.\n",
		},
		{
			Name: "flowstate.v1.ListCursor.position",
			Leading: " Position is where the scan stopped, in the visibility store's own words:\n" +
				" the page token Temporal handed back, carried intact and never inspected.\n",
		},
		{
			Name: "flowstate.v1.ListCursor.namespace",
			Leading: " Namespace is the tenant the token was issued to. A token presented by a\n" +
				" caller in another namespace is refused, whatever its position: a cursor\n" +
				" is a place in one tenant's listing and means nothing in another's.\n",
		},
		{
			Name: "flowstate.v1.ListCursor.query_digest",
			Leading: " QueryDigest is a SHA-256 over the filter and the effective page size the\n" +
				" token was issued for. The same cursor under a different filter names a\n" +
				" page that need not exist, which would come back as a silently empty page\n" +
				" rather than an error, so a token whose digest differs from the request's\n" +
				" is refused instead.\n",
		},
		{
			Name: "flowstate.v1.ListCursor.issued_at",
			Leading: " IssuedAt is when the server issued the token. A token older than a day is\n" +
				" refused, so a stored cursor cannot resume a listing whose visibility has\n" +
				" since changed.\n",
		},
		{
			Name:    "flowstate.v1.ValidateRequest",
			Leading: " ValidateRequest is one or more files to check.\n",
		},
		{
			Name: "flowstate.v1.ValidateRequest.files",
			Leading: " Files are the files to check, in the order the report should list them:\n" +
				" 1 to 64 files, each at most 1 MiB.\n",
		},
		{
			Name:    "flowstate.v1.ValidateResponse",
			Leading: " ValidateResponse is what the check found.\n",
		},
		{
			Name:    "flowstate.v1.ValidateResponse.report",
			Leading: " Report is one entry per file, including the files that were clean.\n",
		},
		{
			Name:    "flowstate.v1.GetTimelineRequest",
			Leading: " GetTimelineRequest addresses one run and asks for a page of its account.\n",
		},
		{
			Name: "flowstate.v1.GetTimelineRequest.workflow_id",
			Leading: " WorkflowId is the workload to read, as Run's `workflow_id` reports it. 1 to\n" +
				" 256 bytes. The caller may read only runs in its own tenant.\n",
		},
		{
			Name: "flowstate.v1.GetTimelineRequest.run_id",
			Leading: " RunId names one segment of the workload, as a UUID. Empty reads the\n" +
				" latest segment.\n" +
				"\n" +
				" A workload that continued as new has a timeline per segment; walk the\n" +
				" chain with the answer's `first_run_id`, `next_run_id` and\n" +
				" `previous_run_id`. Required when `after_event_id` is set.\n",
		},
		{
			Name: "flowstate.v1.GetTimelineRequest.max_entries",
			Leading: " MaxEntries is the most entries one answer returns: 0 (the default) means\n" +
				" 500, and at most 5000.\n",
		},
		{
			Name: "flowstate.v1.GetTimelineRequest.after_event_id",
			Leading: " AfterEventId resumes an account past the last entry a caller already read:\n" +
				" pass `TimelineEntry.event_id` from the last row of the previous answer.\n" +
				" Zero starts at the beginning.\n" +
				"\n" +
				" Requires `run_id`, and is refused without it. Event ids restart at 1 in\n" +
				" every segment, and an empty `run_id` means the latest segment, which\n" +
				" changes if the workload continues as new between two calls. Pass the\n" +
				" previous answer's `GetTimelineResponse.run_id`.\n" +
				"\n" +
				" Each request reads the segment's history from the start, so resuming\n" +
				" re-reads what it skips; that work is bounded by the server's scan budget.\n",
		},
		{
			Name:    "flowstate.v1.GetTimelineResponse",
			Leading: " GetTimelineResponse is what one run did.\n",
		},
		{
			Name: "flowstate.v1.GetTimelineResponse.entries",
			Leading: " Entries are in the order they happened, oldest first, which is the order a\n" +
				" history is written and the order an account is read.\n",
		},
		{
			Name: "flowstate.v1.GetTimelineResponse.run_id",
			Leading: " RunId is the segment this account was read from, always set, including\n" +
				" when the request named none and the server resolved the latest. Pass it\n" +
				" back as `GetTimelineRequest.run_id` when resuming.\n",
		},
		{
			Name: "flowstate.v1.GetTimelineResponse.truncated",
			Leading: " Truncated is true when this is not the whole of this run's account.\n" +
				"\n" +
				" Resume with `GetTimelineRequest.after_event_id` set to the last entry's\n" +
				" `TimelineEntry.event_id`. Raising `GetTimelineRequest.max_entries` is not\n" +
				" the way past it: a segment can hold several times the largest answer.\n" +
				"\n" +
				" Set when the answer hit its entry ceiling, when the read hit its scan\n" +
				" budget, or when the account of a closed run does not reach the event that\n" +
				" ended it. An answer that exactly filled its ceiling is reported as\n" +
				" truncated even if nothing follows, so a walk can end with one request that\n" +
				" returns nothing and is not truncated.\n" +
				"\n" +
				" Truncated with no entries means the scan budget was spent before reaching\n" +
				" the cursor, on a history larger than this server will walk. Stop there:\n" +
				" the same request will do the same thing.\n",
		},
		{
			Name: "flowstate.v1.GetTimelineResponse.next_run_id",
			Leading: " NextRunId is the segment this one handed over to, set when this run\n" +
				" continued as new.\n" +
				"\n" +
				" Because a timeline is per run and a workload is not: a long-lived entity is\n" +
				" a chain of segments, and a caller reading its whole account follows this.\n",
		},
		{
			Name: "flowstate.v1.GetTimelineResponse.previous_run_id",
			Leading: " PreviousRunId is the segment that handed over to this one, empty on the\n" +
				" first. A caller holding only a workflow id reads the latest segment first\n" +
				" and walks back through this.\n",
		},
		{
			Name: "flowstate.v1.GetTimelineResponse.first_run_id",
			Leading: " FirstRunId is the segment the workload began at, which is where a caller\n" +
				" reading the whole of a long-lived entity should start.\n" +
				"\n" +
				" Both this and previous_run_id come off the history's own first event, which\n" +
				" this read has in hand either way, so neither costs a round trip.\n",
		},
		{
			Name:    "flowstate.v1.CompileRequest",
			Leading: " CompileRequest is one Flowfile to compile.\n",
		},
		{
			Name: "flowstate.v1.CompileRequest.file",
			Leading: " File is the Flowfile to compile: a `name` used in diagnostics and its\n" +
				" `source` bytes, at most 1 MiB (base64 in JSON).\n",
		},
		{
			Name:    "flowstate.v1.CompileResponse",
			Leading: " CompileResponse is the specification, or the reasons there is not one.\n",
		},
		{
			Name: "flowstate.v1.CompileResponse.workflow",
			Leading: " Workflow is the compiled specification, set only when the file compiled\n" +
				" clean. Pass it unchanged as Run's or CreateSchedule's `workflow`.\n",
		},
		{
			Name: "flowstate.v1.CompileResponse.report",
			Leading: " Report carries the diagnostics for the file, present even when empty so\n" +
				" \"compiled clean\" is stated rather than inferred from absence.\n",
		},
		{
			Name:    "flowstate.v1.GetCatalogRequest",
			Leading: " GetCatalogRequest asks what this deployment can execute. It has no fields.\n",
		},
		{
			Name:    "flowstate.v1.GetCatalogResponse",
			Leading: " GetCatalogResponse is the deployment's capability.\n",
		},
		{
			Name: "flowstate.v1.GetCatalogResponse.catalog",
			Leading: " Catalog lists every task a step may name, with its typed inputs and\n" +
				" outputs, and the CEL functions the language profile's extension libraries\n" +
				" add. The same document `flow tasks --output json` prints.\n",
		},
		{
			Name: "flowstate.v1.GetCatalogResponse.plugins",
			Leading: " Plugins lists the plugins the deployment brought up and the directories it\n" +
				" searched for them.\n",
		},
		{
			Name: "flowstate.v1.MutationResult",
			Leading: " MutationResult is the answer a mutation gives to a program.\n" +
				"\n" +
				" It is the CLI's machine-readable answer for every mutation verb (cancel,\n" +
				" terminate, signal, and the schedule verbs), whose RPC responses are empty, so\n" +
				" a script has one shape to read. It carries only what the calling process knows for certain: what it\n" +
				" asked and that the server accepted it. It never claims the resulting state of\n" +
				" a run or schedule.\n",
		},
		{
			Name: "flowstate.v1.MutationResult.verb",
			Leading: " Verb is the act that produced this result, spelled the way a caller asked\n" +
				" for it and without the binary name: \"cancel\", \"terminate\", \"signal\",\n" +
				" \"schedule pause\".\n" +
				"\n" +
				" Carried so that a log of these documents, or a pipeline handling several,\n" +
				" says what each one was. Read out of its invocation, a result is otherwise\n" +
				" an identifier and a word with no verb attached to either.\n",
		},
		{
			Name:    "flowstate.v1.MutationResult.workflow_id",
			Leading: " WorkflowId names the workload acted on, and is empty on the schedule verbs.\n",
		},
		{
			Name: "flowstate.v1.MutationResult.run_id",
			Leading: " RunId is the attempt the request was pinned to, and is empty when the\n" +
				" caller pinned none.\n" +
				"\n" +
				" Empty is the usual case and means the request addressed whichever run of\n" +
				" the workload is current. This is the run id that was sent rather than the\n" +
				" one the server resolved, which is the point of reporting it: a caller can\n" +
				" tell a request that named an attempt from one that took the current attempt\n" +
				" without knowing which attempt that turned out to be.\n",
		},
		{
			Name: "flowstate.v1.MutationResult.schedule_name",
			Leading: " ScheduleName names the schedule acted on, and is empty on the run verbs.\n" +
				"\n" +
				" A name rather than an id, because that is what the schema calls it\n" +
				" (`ScheduleDescription.name`) and a schedule has no other identity. Spelling\n" +
				" it \"schedule_id\" here would invent a second word for one concept.\n",
		},
		{
			Name: "flowstate.v1.MutationResult.signal_name",
			Leading: " SignalName is the signal that was sent, and is empty on every other verb.\n" +
				"\n" +
				" Part of what was done rather than only of what was addressed: two signals\n" +
				" to one run are two different acts, and a result naming neither leaves a\n" +
				" reader unable to tell them apart afterwards.\n",
		},
		{
			Name: "flowstate.v1.MutationResult.result",
			Leading: " Result is how far the act got, which is the distinction these verbs turn on\n" +
				" and the one that decides whether a caller may build on the answer.\n" +
				"\n" +
				" Three words, and the differences between them are load bearing.\n" +
				"\n" +
				" \"applied\" is an act that is true once the server has answered: terminating\n" +
				" a run, and deleting, pausing or resuming a schedule. The new state is in\n" +
				" effect at that point, so a caller may act on it directly.\n" +
				"\n" +
				" \"requested\" is an act the server has accepted and has not yet performed.\n" +
				" Cancellation is cooperative, so the run has been told and is still finishing\n" +
				" its response; a triggered schedule fires after the answer, which is also why\n" +
				" there is no run id to report alongside it. A caller that needs the outcome\n" +
				" has to go and read it.\n" +
				"\n" +
				" \"delivered\" belongs to the signal verb, and it is neither of the other two\n" +
				" on purpose. The server has taken the signal, either into the gate that was\n" +
				" waiting or into the bounded pending set for a gate the run has not reached\n" +
				" yet, and that is the whole of what anything on this side can claim. A signal\n" +
				" still pending when the run continues as new is dropped once the carry limit\n" +
				" is full, so a workflow that never observes it is a possible ending of a\n" +
				" delivery that succeeded. \"applied\" would promise that the workflow acted on\n" +
				" it, which no surface here is in a position to know.\n" +
				"\n" +
				" A string rather than an enum, because this reports how far the calling\n" +
				" process's own request got rather than a state the server models, and the\n" +
				" vocabulary may grow.\n",
		},
		{
			Name:    "flowstate.v1.WorkflowService",
			Leading: " WorkflowService is the service that provides operations for managing and running workflows.\n",
		},
		{
			Name: "flowstate.v1.WorkflowService.Run",
			Leading: " Run submits a compiled workflow specification and starts it running durably.\n" +
				"\n" +
				" It answers with the ids to follow the run by and does not wait for the run\n" +
				" to finish; a workload may take a week. Follow the run with [Get], using the\n" +
				" `workflow_id` this returns.\n" +
				"\n" +
				" `workflow` is the specification [Compile] returns, not Flowfile source, so\n" +
				" the path from a file is [Validate], [Compile], then Run. `inputs` are\n" +
				" literal values for the workflow's declared inputs. Set `request_id` when a\n" +
				" submission may be retried, so a retry cannot start the workload twice.\n",
		},
		{
			Name: "flowstate.v1.WorkflowService.Get",
			Leading: " Get reports one run: its status, its timing, where it has reached, its\n" +
				" outputs once it has finished, who started it, and every approval gate it is\n" +
				" parked on right now.\n" +
				"\n" +
				" For each open gate the answer carries the question the gate asks, the signal\n" +
				" name that releases it, whether a deadline lapses it, and whether the workflow\n" +
				" declares a policy over who may answer. That set is what an approval surface\n" +
				" has to render, and it is what a `distinct_from_starter` policy is compared\n" +
				" against.\n" +
				"\n" +
				" To answer a gate, call [Signal] with the gate's signal name and a payload\n" +
				" carrying the decision. Address the workflow rather than a run: a run id pins\n" +
				" delivery to one attempt, and a workload that has been continued as new since\n" +
				" the gate opened will refuse it.\n",
		},
		{
			Name: "flowstate.v1.WorkflowService.Signal",
			Leading: " Signal delivers a signal to a run waiting for one, which is how a human\n" +
				" approval reaches a workload.\n" +
				"\n" +
				" `name` is the signal name the waiting `wait_for_signal:` step declared,\n" +
				" which [Get] reports for each open gate. `payload` is a map of named values\n" +
				" the waiting step reads as `${steps.<id>.payload.<key>}`; an approval is\n" +
				" typically `approved` set to a boolean literal. Leave `run_id` unset so the\n" +
				" signal reaches whichever run of the workload is current.\n" +
				"\n" +
				" This addresses a durable run. `flow run local` answers its gates from flags\n" +
				" instead, with the same signal names and payload shape.\n" +
				"\n" +
				" [SignalResponse] is empty: it says the signal was accepted, not what the run\n" +
				" did with it. Call [Get] afterward to see whether a waiting step consumed it.\n",
		},
		{
			Name: "flowstate.v1.WorkflowService.SignalWithStart",
			Leading: " SignalWithStart delivers a signal to the entity holding a business key, an\n" +
				" order id or a subscription id, creating that entity if this is the first\n" +
				" event for the key.\n" +
				"\n" +
				" Use this rather than [Run] whenever the key, and not a run id, is what a\n" +
				" caller has. It is atomic, so two callers racing on the same key produce one\n" +
				" entity rather than two. The entity is created from `workflow` and `inputs`\n" +
				" when nothing is running under `entity_key` yet; otherwise those are ignored\n" +
				" and only the signal is delivered. `created` in the answer says which\n" +
				" happened.\n",
		},
		{
			Name: "flowstate.v1.WorkflowService.List",
			Leading: " List returns a page of the runs belonging to the caller's tenant.\n" +
				"\n" +
				" `filter` is an optional CEL expression over each run's `workflow_id`,\n" +
				" `run_id`, `status` (short names such as `FAILED`), `name`, `labels`,\n" +
				" `starter`, `start_time`, `close_time`, `finished` and `worker_version`,\n" +
				" such as `status == \"FAILED\" && name == \"nightly-etl\"`. `page_size`\n" +
				" defaults to 50 and is at most 1000.\n" +
				"\n" +
				" Keep calling with `page_token` set to the previous `next_page_token` until\n" +
				" `next_page_token` comes back empty. A short or even empty page with a\n" +
				" token set is not the end of the listing.\n" +
				"\n" +
				" # Why pages can be short\n" +
				"\n" +
				" A run's tenant is recorded as a memo, which works against a stock\n" +
				" `temporal server start-dev` with nothing registered but cannot be queried\n" +
				" by Temporal. So the server reads a bounded number of runs per call and\n" +
				" keeps the caller's, and a caller cannot make one call walk a whole\n" +
				" namespace.\n",
		},
		{
			Name: "flowstate.v1.WorkflowService.GetTimeline",
			Leading: " GetTimeline reports what a run did, event by event, read back from its own\n" +
				" durable history.\n" +
				"\n" +
				" [Get] answers what a run is now; this answers what happened, which is what\n" +
				" to read for a run that has already failed: which step, on which attempt,\n" +
				" with what error, and what it was waiting for before that. It starts,\n" +
				" signals and changes nothing. Authorized like every other verb addressing a\n" +
				" run.\n" +
				"\n" +
				" `max_entries` defaults to 500 and is at most 5000. When `truncated` is set,\n" +
				" call again with `run_id` set to the answer's `run_id` and `after_event_id`\n" +
				" set to the last entry's `event_id`; repeat until `truncated` is false. A\n" +
				" workload that continued as new has one timeline per segment: start at\n" +
				" `first_run_id` and follow `next_run_id`, or walk back with\n" +
				" `previous_run_id`.\n",
		},
		{
			Name: "flowstate.v1.WorkflowService.Cancel",
			Leading: " Cancel asks a run to stop and lets it clean up on the way out.\n" +
				"\n" +
				" Prefer Cancel to [Terminate]: a cancelled run still releases what it holds,\n" +
				" rolls back, or reports that it gave up. A run blocked on something that\n" +
				" never returns may not stop; that is when to terminate it.\n" +
				"\n" +
				" [CancelResponse] is empty: it says the stop request was accepted, not that\n" +
				" the run has stopped. Call [Get] afterward to see the run's final status.\n",
		},
		{
			Name: "flowstate.v1.WorkflowService.Terminate",
			Leading: " Terminate stops a run immediately, running none of its cleanup.\n" +
				"\n" +
				" Use it only when a run must stop now or [Cancel] has not stopped it:\n" +
				" nothing the workload would do on the way out is done, so any resource it\n" +
				" was responsible for releasing is leaked. Give a `reason`; it is the only\n" +
				" record of why the run stopped.\n" +
				"\n" +
				" [TerminateResponse] is empty: the run is already stopped by the time this\n" +
				" returns, so a follow-up call to [Get] confirms status rather than awaiting it.\n",
		},
		{
			Name: "flowstate.v1.WorkflowService.Validate",
			Leading: " Validate checks Flowfiles and returns their diagnostics, executing nothing.\n" +
				"\n" +
				" The same checks and the same [ValidationReport] as `flow validate`: one\n" +
				" entry per file, clean files included. Send 1 to 64 files; each file's\n" +
				" `source` is its bytes, at most 1 MiB, base64-encoded in JSON. It reads,\n" +
				" writes and starts nothing, so it is safe to call repeatedly while editing.\n",
		},
		{
			Name: "flowstate.v1.WorkflowService.Compile",
			Leading: " Compile turns one Flowfile into the workflow specification that [Run]\n" +
				" takes, executing nothing.\n" +
				"\n" +
				" `file.source` is the Flowfile's bytes, at most 1 MiB, base64-encoded in\n" +
				" JSON. A file that does not compile is not an RPC error: the answer carries\n" +
				" its diagnostics in `report` and no `workflow`. On success, pass `workflow`\n" +
				" unchanged to [Run] or [CreateSchedule]. The same compiler as the CLI.\n",
		},
		{
			Name: "flowstate.v1.WorkflowService.GetCatalog",
			Leading: " GetCatalog returns what this deployment can execute: every task with its\n" +
				" typed inputs and outputs, and the CEL functions its language profile's\n" +
				" extension libraries add.\n" +
				"\n" +
				" Read it before writing a workflow. A step may name only a task listed here,\n" +
				" including tasks from plugins the deployment loaded, so the answer can\n" +
				" differ from a local `flow tasks`. Expressions may call the listed\n" +
				" functions plus CEL's standard functions and macros (`size`, `has`,\n" +
				" `filter`, and so on) and the duration constructors (`days(3)`), which are\n" +
				" not listed.\n",
		},
		{
			Name: "flowstate.v1.WorkflowService.CreateSchedule",
			Leading: " CreateSchedule arranges for a workflow to run on a cadence.\n" +
				"\n" +
				" The cadence is the workflow's own `triggers.schedule` block (`cron:`,\n" +
				" `every:` or `calendars:`); a workflow without one is refused. Declaring it\n" +
				" in a Flowfile does nothing until this is called. `workflow` is a compiled\n" +
				" specification, as for [Run].\n" +
				"\n" +
				" Everything is checked now, while the caller is present: the specification\n" +
				" is validated and size-checked as Run does, and `inputs` are checked against\n" +
				" the workflow's declared inputs and stored for every firing.\n" +
				"\n" +
				" Create it paused when the cadence is the part in doubt: a paused schedule\n" +
				" reports the times it would fire without taking any of them.\n",
		},
		{
			Name: "flowstate.v1.WorkflowService.ListSchedules",
			Leading: " ListSchedules returns the schedules belonging to the caller's tenant, each\n" +
				" with whether it is live and when it next fires.\n" +
				"\n" +
				" Not paged. The scan is bounded, and `truncated` in the answer says when\n" +
				" the bound stopped it with schedules unexamined.\n",
		},
		{
			Name: "flowstate.v1.WorkflowService.DescribeSchedule",
			Leading: " DescribeSchedule reports one schedule: its cadence, its arguments, when it\n" +
				" next fires and what it has done lately.\n",
		},
		{
			Name: "flowstate.v1.WorkflowService.DeleteSchedule",
			Leading: " DeleteSchedule removes a schedule, so that it fires no more.\n" +
				"\n" +
				" Runs it already started are unaffected. They are ordinary workloads, and\n" +
				" stopping one is [Cancel].\n",
		},
		{
			Name: "flowstate.v1.WorkflowService.PauseSchedule",
			Leading: " PauseSchedule stops a schedule firing without removing it, which is what an\n" +
				" incident wants: the arrangement is still there, still reviewable, and not\n" +
				" running.\n" +
				"\n" +
				" The `note` it records is what the next person to find it paused will read.\n",
		},
		{
			Name: "flowstate.v1.WorkflowService.ResumeSchedule",
			Leading: " ResumeSchedule lets a paused schedule fire again.\n" +
				"\n" +
				" Firings missed while it was paused are not made up: resuming starts the\n" +
				" schedule from now.\n",
		},
		{
			Name: "flowstate.v1.WorkflowService.TriggerSchedule",
			Leading: " TriggerSchedule fires a schedule now, without waiting for its cadence.\n" +
				"\n" +
				" It uses the schedule's stored arguments, tenant and queue, so it tests the\n" +
				" schedule rather than only the workflow. It fires even a paused schedule:\n" +
				" create paused, trigger once to see what happens, then resume.\n" +
				"\n" +
				" It answers with no run id. The cluster takes the action after answering, so\n" +
				" what the firing started is read back with [DescribeSchedule].\n",
		},
	})
}
