// Code generated by protoc-gen-flowstate-doc. DO NOT EDIT.
// source: flowstate/v1/task.proto

package protodoc

import (
	protodocimpl "github.com/picatz/flowstate/pkg/flowstate/v1/protodoc/protodocimpl"
)

func init() {
	protodocimpl.RegisterFile("flowstate/v1/task.proto", []protodocimpl.Comment{
		{
			Name: "flowstate.v1.Task",
			Leading: " Task is the unit of work a step dispatches: a name saying which task, and the\n" +
				" inputs that task takes.\n" +
				"\n" +
				" The inputs are a map of [Value] rather than a per-task message, because the\n" +
				" set of tasks is open. A plugin adds one at run time, and a wire shape holding\n" +
				" a closed union of every task's arguments could not carry a task this build has\n" +
				" never heard of. What keeps that from being untyped is [TaskCatalog]: each task\n" +
				" declares its fields and their constraints there, the registry checks a step's\n" +
				" inputs against that declaration before anything runs, and the nested Inputs\n" +
				" and Outputs messages below give the built-in tasks the same shapes in Go that\n" +
				" a plugin's manifest gives its own.\n",
		},
		{
			Name: "flowstate.v1.Task.name",
			Leading: " Tasks have specific names that identify the type of task being performed,\n" +
				" such as \"log\" or \"http\". The name is used to determine which task\n" +
				" implementation to execute when the workflow is run.\n" +
				"\n" +
				" # A dot means a plugin, and its absence means the engine\n" +
				"\n" +
				" A built-in task is one bare word. A plugin's task is two, joined by a dot\n" +
				" (`slack.post` is the `post` task of the plugin discovered as\n" +
				" `flowstate-plugin-slack`), and the dot is provenance rather than decoration:\n" +
				" it tells a reviewer that this line leaves the engine's code and enters code\n" +
				" somebody installed, at the step, where that fact is needed. It also makes\n" +
				" collision unrepresentable in both directions. A plugin task cannot shadow a\n" +
				" built-in because a plugin's tasks all carry a dot and no built-in does; two\n" +
				" plugins cannot fight over one name because each one's tasks are prefixed\n" +
				" with a name discovery established from the binary, not self-reported.\n" +
				"\n" +
				" At most one dot, by the pattern below. The first segment is a plugin name\n" +
				" (`^[a-z0-9][a-z0-9-]*$`, from the executable's own name) and the second a\n" +
				" task name (`^[a-z][a-z0-9_]*$`, from its manifest); the pattern here is the\n" +
				" permissive union rather than that concatenation, because this field also\n" +
				" spells built-in names with their historical uppercase-and-dash latitude, and\n" +
				" the registry enforces the sharper per-segment rules at registration.\n",
		},
		{
			Name:    "flowstate.v1.Task.inputs",
			Leading: " Inputs are the parameters that the task requires to perform its operation.\n",
		},
		{
			Name: "flowstate.v1.Task.Log",
			Leading: " Log is a task that emits a message for a person to read.\n" +
				"\n" +
				" It exists because `echo` was doing this job under a name that describes the\n" +
				" wrong thing: echo *returns* a value, and the two uses that survived `vars:`\n" +
				" (hello-world scaffolding and \"this branch ran\" markers) were never about the\n" +
				" return. They were about someone seeing it. Naming the capability after what it\n" +
				" is for is what lets the surfaces that show it (a `flow run` transcript, the\n" +
				" watch view, the run record) treat it as a message rather than as a value that\n" +
				" happens to be printed.\n" +
				"\n" +
				" # It has no outputs, deliberately\n" +
				"\n" +
				" A log line is an effect on a reader, not a value for a later step. Offering\n" +
				" `result` would make `${steps.announce.result}` legal, which is the `vars:` use\n" +
				" case sneaking back in through the one task that has no business carrying data,\n" +
				" and it would give a step two reasons to exist, so the file could no longer say\n" +
				" which one was meant. A capability that emits nothing is how this language says\n" +
				" \"this produces nothing you can read\".\n",
		},
		{
			Name: "flowstate.v1.Task.Log.Inputs",
			Leading: " Inputs describes one message written to the run's durable log. Omitting\n" +
				" level records the message at info level, and fields may be absent when the\n" +
				" message has no structured attributes.\n",
		},
		{
			Name: "flowstate.v1.Task.Log.Inputs.message",
			Leading: " Message is the line a person reads. It is the whole point, so it is the\n" +
				" only required input.\n",
		},
		{
			Name: "flowstate.v1.Task.Log.Inputs.level",
			Leading: " Level says how much it matters, and defaults to LEVEL_INFO.\n" +
				"\n" +
				" An enum rather than a free string, because a sink has to map it onto\n" +
				" something (a terminal colour, a severity field, a filter), and a set that\n" +
				" an author can extend by typo is a set nothing downstream can switch on.\n",
		},
		{
			Name: "flowstate.v1.Task.Log.Inputs.fields",
			Leading: " Fields carry structure for a sink that has somewhere to put it, and are\n" +
				" ignored by one that does not.\n" +
				"\n" +
				" String-valued rather than Value-valued, and that is a real limit rather\n" +
				" than an oversight: every sink this can reach (a terminal line, a logging\n" +
				" backend's attributes, a run record) renders to text in the end, and a\n" +
				" nested value would render differently at each of them. Compose the string\n" +
				" in the expression, where the author can see what it will say.\n" +
				"\n" +
				" Bounded because a workflow chooses both the count and the size, and a log\n" +
				" line is written to durable history.\n",
		},
		{
			Name: "flowstate.v1.Task.Log.Outputs",
			Leading: " Outputs is empty and stays empty.\n" +
				"\n" +
				" Present rather than absent because every task's shape is described from a\n" +
				" descriptor (`flow tasks` and the language server both read one), and a task\n" +
				" with no message at all would have to be a special case in each of them. An\n" +
				" empty message says \"nothing\" in the same vocabulary everything else uses.\n",
		},
		{
			Name: "flowstate.v1.Task.Log.Level",
			Leading: " Level is how much a message matters.\n" +
				"\n" +
				" Three, and no more without a reason: `debug` is a *deployment* concern rather\n" +
				" than an authoring one (a workflow author cannot know what a given operator\n" +
				" wants filtered), and `fatal` is a claim about control flow that a task has no\n" +
				" way to honour, since emitting a line does not stop the run.\n",
		},
		{
			Name: "flowstate.v1.Task.Log.LEVEL_UNSPECIFIED",
			Leading: " Unspecified reads as LEVEL_INFO, so a `log:` that says nothing about level\n" +
				" is the ordinary case rather than an error.\n",
		},
		{
			Name:    "flowstate.v1.Task.Log.LEVEL_INFO",
			Leading: " Info records ordinary progress or operational context.\n",
		},
		{
			Name:    "flowstate.v1.Task.Log.LEVEL_WARN",
			Leading: " Warn records a condition worth attention without changing task success.\n",
		},
		{
			Name:    "flowstate.v1.Task.Log.LEVEL_ERROR",
			Leading: " Error records an error condition but does not itself fail the task or run.\n",
		},
		{
			Name: "flowstate.v1.Task.HTTP",
			Leading: " HTTP is a task that performs an HTTP request to a specified URL with optional method, headers, and body.\n" +
				" It returns the HTTP response status code, headers, and body as outputs.\n" +
				"\n" +
				" Every request is subject to the deployment's egress policy; a workflow\n" +
				" reaches only hosts that policy allows.\n",
		},
		{
			Name: "flowstate.v1.Task.HTTP.Inputs",
			Leading: " Inputs describes the outbound request and how its response is accepted and\n" +
				" shaped. Secret references remain unresolved until worker-side use; absent\n" +
				" optional controls use the defaults documented on their fields.\n",
		},
		{
			Name: "flowstate.v1.Task.HTTP.Inputs.url",
			Leading: " Url is where the request goes, written as an absolute URI.\n" +
				"\n" +
				" Absolute because there is nothing for a relative one to be relative to:\n" +
				" a workflow runs on a worker, not in a browser holding the page it came\n" +
				" from. The scheme and host are also what a deployment's egress policy is\n" +
				" written against, so a request that does not name them is a request\n" +
				" nobody can decide about.\n",
		},
		{
			Name: "flowstate.v1.Task.HTTP.Inputs.method",
			Leading: " Method is the HTTP method, and is GET where a step does not write one.\n" +
				"\n" +
				" GET, POST, PUT, PATCH or DELETE, in any case. The set is closed rather\n" +
				" than free text because retry behaviour hangs off it: a request whose\n" +
				" outcome is unknown is retried by what its method promises (see\n" +
				" `retry_on_unknown_outcome`), so a method nothing knows the idempotency\n" +
				" of is a request nothing can safely repeat.\n",
		},
		{
			Name: "flowstate.v1.Task.HTTP.Inputs.headers",
			Leading: " Request headers, by name.\n" +
				"\n" +
				" A header value may be a secret reference; such a mapping is carried as\n" +
				" a structure among the task's inputs instead of this field, and each\n" +
				" reference is resolved inside the activity only as its header is set.\n",
		},
		{
			Name: "flowstate.v1.Task.HTTP.Inputs.body",
			Leading: " A raw request body, sent as written.\n" +
				"\n" +
				" A string, and so unable to carry a secret reference: there is nothing\n" +
				" between the field and the wire that could resolve one. A body that needs\n" +
				" a credential in it is a `json` or a `form` body, both of which the task\n" +
				" encodes itself and can therefore resolve into.\n",
		},
		{
			Name: "flowstate.v1.Task.HTTP.Inputs.bearer",
			Leading: " Bearer is the credential for an Authorization header, and it is the\n" +
				" first task input built to take a secret reference.\n" +
				"\n" +
				" A `Value` rather than a string, deliberately: a field declared as Value\n" +
				" receives the author's value whole (reference included) where a string\n" +
				" field can only hold what the workflow already evaluated, and evaluating\n" +
				" a secret is what would put it in history.\n" +
				"\n" +
				" A reference can also sit inside `headers` now, as one entry of a\n" +
				" [Value.Structure], which is what makes `Authorization` writable by hand.\n" +
				" This field stays, and stays the recommended spelling: it says what the\n" +
				" credential *is*, so the worker renders the header and an author cannot\n" +
				" get the scheme wrong, and it leaves the rest of `headers` free to hold\n" +
				" expressions, which a structure carrying a reference deliberately cannot.\n" +
				"\n" +
				" The worker resolves it inside the activity and sends\n" +
				" `Authorization: Bearer <value>`. The name says the scheme so the field\n" +
				" cannot quietly become a junk drawer: a future credential shape gets its\n" +
				" own field, named for what it is.\n",
		},
		{
			Name: "flowstate.v1.Task.HTTP.Inputs.credential",
			Leading: " Credential names an outbound federation target configured by the\n" +
				" deployment, such as \"aws-prod\" or \"partner-api\". The worker authorizes\n" +
				" the exact workload and step, mints a short-lived assertion, exchanges it,\n" +
				" and applies the resulting bearer credential inside the activity. No\n" +
				" credential material crosses workflow history.\n" +
				"\n" +
				" AWS session targets are deliberately refused by the generic HTTP task:\n" +
				" they require SigV4 request signing and belong in an AWS-aware task.\n",
		},
		{
			Name: "flowstate.v1.Task.HTTP.Inputs.outputs",
			Leading: " Outputs selects what the step returns. When set, the step's outputs are\n" +
				" exactly these named values instead of `status_code`, `body`, `headers`\n" +
				" and `json`, so a large response is not carried into the run's history.\n" +
				"\n" +
				" Each value is a literal or a CEL expression over the response, which is\n" +
				" bound as the single root `response`:\n" +
				"   - response.status_code (int)\n" +
				"   - response.body (string)\n" +
				"   - response.headers (map<string, list<string>>: every value of each\n" +
				"     header; the default outputs flatten each to one string)\n" +
				"   - response.json (the parsed body, when `parse_json` asked for it)\n" +
				" An expression that fails to evaluate fails the step without a retry.\n",
		},
		{
			Name: "flowstate.v1.Task.HTTP.Inputs.query",
			Leading: " Query parameters, escaped and appended to the URL.\n" +
				"\n" +
				" Building a query string by hand is where escaping bugs live, and they are\n" +
				" the kind that work until a value contains an ampersand.\n" +
				"\n" +
				" A secret reference here is refused rather than resolved, and it is the one\n" +
				" input of this task where that is a decision about the *destination* rather\n" +
				" than about the mechanism: query strings are written to access logs, kept in\n" +
				" browser history, and forwarded in Referer headers by anything that follows\n" +
				" a redirect. `form` is the same kind of map, encoded by the same function a\n" +
				" few lines away, and accepts one, so the refusal is stated twice on\n" +
				" purpose, once in the compiler where an author can see it and once in\n" +
				" `valueToQueryString` for a specification that never met the compiler.\n",
		},
		{
			Name: "flowstate.v1.Task.HTTP.Inputs.json",
			Leading: " A structured request body, serialized as JSON and sent with\n" +
				" `Content-Type: application/json` unless `headers` sets one. Mutually\n" +
				" exclusive with `body` and `form`.\n" +
				"\n" +
				" Fields may hold secret references at any depth: the task serializes the\n" +
				" body inside the activity, so a reference is resolved only as the bytes\n" +
				" are written.\n",
		},
		{
			Name: "flowstate.v1.Task.HTTP.Inputs.form",
			Leading: " A form body, url-encoded with a matching Content-Type. Mutually exclusive\n" +
				" with `body` and `json`.\n" +
				"\n" +
				" An entry may be a secret reference (an OAuth `client_secret` is the case),\n" +
				" and it is resolved as the body is encoded, inside the activity. The\n" +
				" difference from `query`, which is the same kind of map encoded by the same\n" +
				" function, is entirely the destination: a form body is sent in the request,\n" +
				" where a query string is written down by everything it passes.\n",
		},
		{
			Name: "flowstate.v1.Task.HTTP.Inputs.expect",
			Leading: " Which responses count as success, as a CEL expression over the same\n" +
				" `response` root `outputs` sees.\n" +
				"\n" +
				" The default is unchanged and needs no expression: 2xx succeeds, 4xx fails\n" +
				" permanently, and repeat-safe 5xx responses are retried. This expression\n" +
				" changes only whether the response satisfies the step's contract; it does\n" +
				" not replace status classification or make an ambiguous mutation safe to\n" +
				" repeat. This is for the cases that default cannot express: a 404 that\n" +
				" means \"not there yet, and that is fine\", or an API that answers 200 with\n" +
				" an error in the body (read with `parse_json: true`):\n" +
				"\n" +
				"   expect: ${response.status_code == 200 || response.status_code == 404}\n" +
				"   expect: ${response.status_code == 200 && !response.json.?error.orValue(false)}\n" +
				"\n" +
				" One expression rather than a status list plus a predicate, because a list\n" +
				" is the expression `response.status_code in [200, 404]` and two spellings\n" +
				" of one idea is two things to keep in agreement.\n",
		},
		{
			Name: "flowstate.v1.Task.HTTP.Inputs.parse_json",
			Leading: " Parse the response body as JSON into the `json` output.\n" +
				"\n" +
				" Off by default, and deliberately not inferred from Content-Type: parsing an\n" +
				" untrusted body is work an attacker chooses, so it happens when an author\n" +
				" asked for it. A body that is not JSON is an error naming the offset, not a\n" +
				" silently empty value.\n",
		},
		{
			Name: "flowstate.v1.Task.HTTP.Inputs.retry_on_unknown_outcome",
			Leading: " Retry a non-idempotent request whose outcome is unknown.\n" +
				"\n" +
				" A POST that reached the server and then failed before answering may have\n" +
				" taken effect, so by default it is not retried: doing the operation twice is\n" +
				" worse than surfacing a failure that might have resolved on its own. Set\n" +
				" this when the endpoint is idempotency-keyed and a retry is therefore safe.\n" +
				"\n" +
				" The same rule applies when a 502, 503, or 504 response cannot establish\n" +
				" whether the mutation reached or committed at the origin. `expect:` and\n" +
				" `parse_json:` do not override it.\n" +
				"\n" +
				" It does not affect a request that never connected, which is retried for any\n" +
				" method because it cannot have taken effect.\n",
		},
		{
			Name: "flowstate.v1.Task.HTTP.Outputs",
			Leading: " Outputs contains response data only after the response is accepted as\n" +
				" successful. Json is absent unless parsing was requested, and output shaping\n" +
				" may replace these defaults with the selected values.\n",
		},
		{
			Name: "flowstate.v1.Task.HTTP.Outputs.status_code",
			Leading: " StatusCode is the status the response carried.\n" +
				"\n" +
				" Reported rather than judged here, but not unjudged: a status outside\n" +
				" 2xx fails the step by default, and `expect:` is where a workflow widens\n" +
				" what it accepts. So a file that means to branch on a 404 says so in\n" +
				" `expect:` and reads the number here; without that the step never\n" +
				" produces outputs to read.\n",
		},
		{
			Name: "flowstate.v1.Task.HTTP.Outputs.headers",
			Leading: " Headers are the response's headers, one value per name, read as\n" +
				" `${steps.<id>.headers['Content-Type']}`.\n" +
				"\n" +
				" A header sent more than once keeps its first value, because this is a\n" +
				" mapping of strings and there is no second value to put anywhere. Every\n" +
				" value of a repeated header is reachable through the `outputs` input,\n" +
				" where the response's headers are exposed as lists.\n",
		},
		{
			Name: "flowstate.v1.Task.HTTP.Outputs.body",
			Leading: " Response body, returned by default so a step can be referenced as\n" +
				" ${steps.<id>.body}. Large responses are better trimmed with the `outputs`\n" +
				" input above, which keeps workflow payloads small.\n",
		},
		{
			Name: "flowstate.v1.Task.HTTP.Outputs.json",
			Leading: " The response body parsed as JSON, present when `parse_json` asked for it,\n" +
				" so ${steps.<id>.json.items[0].id} works without a second step to parse it.\n" +
				"\n" +
				" Deliberately a single value rather than a repeated one, and it should stay\n" +
				" that way. A streaming response is not a unary response with more elements:\n" +
				" it is a different interaction shape with a different execution model, since\n" +
				" a long-lived stream cannot live inside one activity at all. When streaming\n" +
				" arrives it gets its own field, which costs nothing because adding a field is\n" +
				" additive. Widening this one to repeated would break every workflow that\n" +
				" reads it, and would make every author write [0] forever to accommodate a\n" +
				" shape their request does not have.\n" +
				"\n" +
				" Carried as a CEL value rather than google.protobuf.Value because that is\n" +
				" already how this schema represents a literal, so the conversions an\n" +
				" expression needs to read it exist rather than being a third value type to\n" +
				" translate between.\n" +
				"\n" +
				" A JSON number arrives as a double, so `{\"id\":7}` reads as 7.0 rather than\n" +
				" 7. That is what encoding/json produces for an untyped number and what the\n" +
				" `json_parse` CEL function already does, and one rule that surprises is\n" +
				" better than two that disagree. It matters when comparing: write\n" +
				" `${call.json.id == 7}` and CEL will compare numerically, but do not expect\n" +
				" `string(call.json.id)` to read as \"7\".\n",
		},
		{
			Name: "flowstate.v1.Task.Exec",
			Leading: " Exec is a task that runs one local program to completion and returns what it\n" +
				" did: its exit code, the bytes it printed, and whether those were cut short.\n" +
				"\n" +
				" It is built in and denied by default. A worker with no `--exec-policy`\n" +
				" refuses every `exec:` step as a policy denial that names the flag, because\n" +
				" process execution is the one capability whose blast radius is the worker\n" +
				" itself, and a deployment has to say yes before a workflow can ask. The\n" +
				" policy file (see [ExecPolicy]) decides which programs exist, which\n" +
				" directories they may run in, which environment they see, and how long and\n" +
				" how loud they may be; the step supplies only a name, arguments, a\n" +
				" directory, and whatever environment the operator let it set.\n" +
				"\n" +
				" # It is not a sandbox\n" +
				"\n" +
				" The child runs as the worker's user with the worker's privileges.\n" +
				" Nothing here applies a namespace, a cgroup, a seccomp filter, a filesystem\n" +
				" confinement, or a network restriction, and the deployment's egress policy\n" +
				" does not govern what the child connects to. The policy decides what may be\n" +
				" *started*; it does not decide what the started program does. A deployment\n" +
				" that needs the second guarantee runs the worker (or a dedicated worker\n" +
				" queue) inside the isolation boundary it trusts.\n" +
				"\n" +
				" # Argv, never a shell string\n" +
				"\n" +
				" The command is a list. There is no field that is parsed into words, so a\n" +
				" value spliced into an argument stays one argument. A workflow that wants\n" +
				" shell semantics names a shell as the program and owns that choice\n" +
				" visibly, and the operator's policy decides whether a shell is a program\n" +
				" this deployment has.\n" +
				"\n" +
				" # A nonzero exit is output, not failure\n" +
				"\n" +
				" The way an HTTP status code is output: the program ran, and what it\n" +
				" concluded is data the workflow branches on. A step fails only when the\n" +
				" policy denies it, the program could not be started, it exceeded the\n" +
				" policy's time bound, or the run was cancelled. A workflow that wants a\n" +
				" nonzero exit to stop the run says so with an `if:` on the next step.\n",
		},
		{
			Name: "flowstate.v1.Task.Exec.Inputs",
			Leading: " Inputs describes one program invocation. The program is named, not\n" +
				" located: argv[0] is a name the operator's policy maps to an absolute\n" +
				" path, and a path written by a workflow is refused.\n",
		},
		{
			Name: "flowstate.v1.Task.Exec.Inputs.argv",
			Leading: " Argv is the command as a list of words, program name first.\n" +
				"\n" +
				" The first word is a bare name looked up in the policy's `executables`\n" +
				" table; it is never searched for on PATH, and a path (anything with a\n" +
				" slash) is refused. The rest are passed to the program verbatim. No word\n" +
				" is split, expanded, globbed or unquoted, which is the property that makes\n" +
				" a value inside an argument safe to splice.\n" +
				"\n" +
				" Bounded because the workflow chooses both the count and the length, and\n" +
				" the product is what the kernel's argument limit refuses. A word may not\n" +
				" contain a NUL byte, which no operating system can pass.\n",
		},
		{
			Name: "flowstate.v1.Task.Exec.Inputs.dir",
			Leading: " Dir is the working directory, written as an absolute path.\n" +
				"\n" +
				" Required, because the worker's own working directory is never used: it\n" +
				" is wherever the operator started the process, which is not something a\n" +
				" workflow can reason about. The policy admits only directories under\n" +
				" one of its configured roots, after symbolic links are resolved, so a\n" +
				" path that lexically begins under a root but leaves it through a link is\n" +
				" refused. A policy that configures no roots admits no directory, which\n" +
				" makes the task unusable rather than unconfined.\n",
		},
		{
			Name: "flowstate.v1.Task.Exec.Inputs.env",
			Leading: " Env sets environment variables for the child, and is a request, not a\n" +
				" grant.\n" +
				"\n" +
				" The child's environment is built from nothing: first the operator's own\n" +
				" literal values, then the worker variables the operator listed for\n" +
				" passthrough, and only then the entries here, each of which is accepted\n" +
				" only if the policy lists its name as one a step may set. A key the\n" +
				" policy does not list is a policy denial, and a key the operator already\n" +
				" set cannot be overridden from here. Values are literal text: a secret\n" +
				" reference is not accepted, so no credential reaches a child through this\n" +
				" input.\n",
		},
		{
			Name: "flowstate.v1.Task.Exec.Outputs",
			Leading: " Outputs is what the invocation did. It is present for every program that\n" +
				" started and finished under its own power, whatever the exit code was.\n",
		},
		{
			Name: "flowstate.v1.Task.Exec.Outputs.exit_code",
			Leading: " ExitCode is the status the program exited with, or -1 when it was\n" +
				" ended by a signal and so never exited (see [signal]).\n" +
				"\n" +
				" Data, not a verdict: a workflow reads it the way it reads an HTTP status\n" +
				" code. Zero is success by convention only, and some programs use nonzero\n" +
				" codes for outcomes that are not failures (`diff`, `grep`).\n",
		},
		{
			Name: "flowstate.v1.Task.Exec.Outputs.stdout",
			Leading: " Stdout is the program's standard output: at most the policy's byte bound,\n" +
				" keeping the first bytes written, with invalid UTF-8 replaced by U+FFFD\n" +
				" because a string output must be text.\n",
		},
		{
			Name: "flowstate.v1.Task.Exec.Outputs.stderr",
			Leading: " Stderr is the program's standard error, bounded and sanitized exactly as\n" +
				" [stdout] is. Standard output and error are captured separately and are not\n" +
				" interleaved.\n",
		},
		{
			Name: "flowstate.v1.Task.Exec.Outputs.stdout_truncated",
			Leading: " StdoutTruncated is true when the program wrote more to standard output\n" +
				" than the policy's bound and the excess was discarded. The program was not\n" +
				" stopped for it: bytes past the bound are read and dropped so a chatty\n" +
				" program is not blocked on a full pipe.\n",
		},
		{
			Name: "flowstate.v1.Task.Exec.Outputs.stderr_truncated",
			Leading: " StderrTruncated is true when standard error exceeded the bound; see\n" +
				" [stdout_truncated].\n",
		},
		{
			Name: "flowstate.v1.Task.Exec.Outputs.signal",
			Leading: " Signal names the signal that ended the program (such as \"killed\" or\n" +
				" \"segmentation fault\"), and is empty when it exited by itself.\n",
		},
		{
			Name: "flowstate.v1.Task.Exec.Outputs.duration_ms",
			Leading: " DurationMs is how long the program ran, in whole milliseconds, measured\n" +
				" by the worker from start to reap.\n",
		},
		{
			Name: "flowstate.v1.Task.Exec.Outputs.outcome",
			Leading: " Outcome says how the invocation ended: \"ran\" when the program started\n" +
				" and finished (whatever its exit code), \"did_not_start\" when the worker\n" +
				" could not start it, \"timed_out\" when the policy's time bound ended it,\n" +
				" and \"cancelled\" when the run was cancelled around it.\n" +
				"\n" +
				" A step produces outputs only in the \"ran\" case; the other three are\n" +
				" failures, and name themselves as `outcome=<value>` in the failure's text\n" +
				" so a log and a run record say the same word.\n",
		},
	})
}
