// Code generated by protoc-gen-flowstate-doc. DO NOT EDIT.
// source: flowstate/v1/exec_policy.proto

package protodoc

import (
	protodocimpl "github.com/picatz/flowstate/pkg/flowstate/v1/protodoc/protodocimpl"
)

func init() {
	protodocimpl.RegisterFile("flowstate/v1/exec_policy.proto", []protodocimpl.Comment{
		{
			Name: "flowstate.v1.ExecPolicy",
			Leading: " ExecPolicy is the deployment's answer to \"which programs may a workflow\n" +
				" start here\", written as YAML (or JSON) and passed as `--exec-policy` or\n" +
				" `FLOWSTATE_EXEC_POLICY`.\n" +
				"\n" +
				" # Why the file is a message\n" +
				"\n" +
				" The policy is read by the process that will run programs and is never sent\n" +
				" anywhere, so it is not a wire shape in the usual sense. It is defined here\n" +
				" anyway because it is a shape an operator authors and several tools read (the\n" +
				" worker, `flow run local`, `flow task run`, the MCP and debug servers), and\n" +
				" this schema is the one place where a shape gets one definition, its rules,\n" +
				" and its documentation together.\n" +
				"\n" +
				" # What it is, and what it is not\n" +
				"\n" +
				" It is an allowlist of *what may be started*: which names map to which\n" +
				" executables, which directories they may run in, which environment they see,\n" +
				" and how long and how loud they may be. It is not a sandbox. The child runs\n" +
				" with the worker's privileges, and nothing in this file restricts what it\n" +
				" does afterwards (see Task.Exec).\n" +
				"\n" +
				" Without this file the built-in `exec` task is denied. There is no default\n" +
				" policy and no way to enable the task from a workflow.\n",
		},
		{
			Name:    "flowstate.v1.ExecPolicy.exec",
			Leading: " Exec configures the built-in `exec` task. See [Exec].\n",
		},
		{
			Name: "flowstate.v1.ExecPolicy.Exec",
			Leading: " Exec is the one section of the file today. It sits under a key of its own\n" +
				" so that a later section (a second execution tier, for instance) is an\n" +
				" addition and not a reshaping of every deployed file.\n",
		},
		{
			Name: "flowstate.v1.ExecPolicy.Exec.executables",
			Leading: " Executables maps the program names a workflow may write as `argv[0]` to\n" +
				" the absolute path of the file that runs.\n" +
				"\n" +
				" A workflow names programs; only the operator locates them. The table is\n" +
				" the whole lookup: there is no search of PATH, and a name that is not a\n" +
				" key is refused. Every path is checked when the policy loads: absolute,\n" +
				" present, a regular file, executable, not writable by everyone, and\n" +
				" resolved through symbolic links to the file that will actually run.\n" +
				" Names are bare (no slash, no leading dash) so they cannot be mistaken for\n" +
				" paths or options.\n",
		},
		{
			Name: "flowstate.v1.ExecPolicy.Exec.executable_sha256",
			Leading: " ExecutableSha256 optionally pins an entry of [executables] to the SHA-256\n" +
				" of the file it resolves to, as 64 lowercase hex digits, keyed by the same\n" +
				" name.\n" +
				"\n" +
				" Checked at load against the resolved file, and again against the very\n" +
				" file descriptor that is executed where the platform allows it, so a file\n" +
				" swapped after the check does not run. A name with no pin is trusted by\n" +
				" path alone, which is the operator's decision to make per program. A pin\n" +
				" for a name that is not in [executables] is an error, not an ignored line.\n",
		},
		{
			Name: "flowstate.v1.ExecPolicy.Exec.roots",
			Leading: " Roots are the absolute directories under which a step's `dir` must fall.\n" +
				"\n" +
				" Compared component by component after symbolic links are resolved on both\n" +
				" sides, so `/srv/work-evil` is not under `/srv/work` and a link inside a\n" +
				" root that points outside it does not admit the target. A policy with no\n" +
				" roots admits no directory, so the task cannot run: the worker's own\n" +
				" working directory is never a fallback.\n",
		},
		{
			Name: "flowstate.v1.ExecPolicy.Exec.env_passthrough",
			Leading: " EnvPassthrough lists worker environment variables copied into the child\n" +
				" when they are set in the worker, and skipped when they are not.\n" +
				"\n" +
				" The child never inherits the worker's environment wholesale, because the\n" +
				" worker's environment is where its credentials live. Loader-injection\n" +
				" variables (`LD_PRELOAD`, `LD_LIBRARY_PATH`, `LD_AUDIT`, and anything\n" +
				" starting `DYLD_`) are refused at load even if listed.\n",
		},
		{
			Name: "flowstate.v1.ExecPolicy.Exec.env",
			Leading: " Env holds literal variables the operator sets for every child. A step\n" +
				" cannot override them. Values are text in the policy file, so they are\n" +
				" not the place for a credential: secret-valued environment is deliberately\n" +
				" not offered yet.\n",
		},
		{
			Name: "flowstate.v1.ExecPolicy.Exec.env_authored",
			Leading: " EnvAuthored lists the variable names a *step* may set through its `env`\n" +
				" input. Empty means none: a workflow adds nothing to the environment unless\n" +
				" the operator named the key.\n",
		},
		{
			Name: "flowstate.v1.ExecPolicy.Exec.timeout",
			Leading: " Timeout bounds how long one program may run, written as a duration such\n" +
				" as \"10m\". Required, positive, and at most one hour: there is no policy\n" +
				" spelling for \"unbounded\", and a file that asks for more than the ceiling\n" +
				" is refused at load rather than clamped, so the file says what is enforced.\n",
		},
		{
			Name: "flowstate.v1.ExecPolicy.Exec.max_output_bytes",
			Leading: " MaxOutputBytes bounds what is kept of each output stream (standard output\n" +
				" and standard error separately), written the way sizes are said: \"1MiB\",\n" +
				" \"10MB\", or a bare count of bytes. Required, positive, and at most 16 MiB.\n" +
				" Bytes past the bound are read and discarded and the step reports the\n" +
				" stream as truncated.\n",
		},
		{
			Name: "flowstate.v1.ExecPolicy.Exec.allow",
			Leading: " Allow holds CEL allow rules. Configuring any turns the policy into an\n" +
				" allowlist: an invocation must match at least one. Rules read `argv`\n" +
				" (list of string), `executable` (the resolved absolute path), `name`\n" +
				" (argv[0] as written), `dir` (the cleaned absolute directory), `env_keys`\n" +
				" (the sorted names of the final environment, never its values) and\n" +
				" `identity` (subject, issuer, namespace, claims of the run's attested\n" +
				" workload). A policy with no allow rules permits what its other checks\n" +
				" admit.\n",
		},
		{
			Name: "flowstate.v1.ExecPolicy.Exec.deny",
			Leading: " Deny holds CEL deny rules, which run first and win. A rule that fails to\n" +
				" evaluate denies the invocation. Same variables as [allow].\n",
		},
	})
}
