package main

import (
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"sort"
	"strings"

	"github.com/spf13/cobra"
	"github.com/spf13/pflag"

	v1 "github.com/picatz/flowstate/pkg/flowstate/v1"
)

// Reference documentation, generated from the things that cannot drift.
//
// Four tables in this repository's prose were hand-maintained beside a registry
// that already knew the answer, and each one drifted the same silent way: the
// env-var table shipped ten variables short, the task table sent readers to a
// summary the schema had already outgrown, and a command added without a row was
// a capability nobody found. A table beside a source of truth is a second source
// of truth, and the second one is always the stale one.
//
// So these are derived, and pinned in CI with `git diff --exit-code` — the same
// mechanism that keeps committed generated code honest against `buf generate`. A
// change that adds a task, a flag, an RPC or a variable and does not regenerate
// fails in CI rather than in somebody's afternoon six weeks later.
//
// # Why live Go values rather than compiled descriptors
//
// docs/VISION.md warns that SourceCodeInfo — the leading comments a `.proto`
// carries — does not survive into the descriptors compiled into the binary:
// protoc-gen-go strips them, so a generator reading `protoregistry` finds field
// names and types and no prose. That is true and it is why nothing here reads a
// descriptor for documentation *text*.
//
// This generator runs inside the binary instead, over the same live values the
// running program uses: [v1.Catalog] (the registry, which is also what the
// GetCatalog RPC answers with), [newRootCommand] (the cobra tree, whose Short,
// Long and Example fields are Go string literals and so are present at runtime),
// and the MCP tool table. Prose written in Go is prose a generator can read, and
// the derivation is from the *same object the code dispatches on* rather than
// from a parallel artifact — which is the stronger property anyway. Descriptors
// still supply everything structural, by way of the catalog: a task's field
// names, types, and required-ness come from protovalidate rules on the schema.
//
// The one thing that could change this is a custom protoc option carrying
// documentation into the descriptor set. That would be worth it only for prose
// that has nowhere else to live; today every sentence a reader needs is already
// a Go value.
//
// # Determinism
//
// Every listing here sorts, and the environment is cleared before the cobra tree
// is built — flag defaults are read from the environment at construction, so a
// developer with FLOWSTATE_ADDRESS set would otherwise generate a diff. Running
// the generator twice must produce identical bytes; TestGeneratedDocsAreStable
// is that assertion.

// docsReferenceDir is where the generated reference lives, relative to the
// repository root.
const docsReferenceDir = "docs/reference"

// generatedNotice heads every generated file.
//
// Written into the file rather than left to a reviewer's memory: the first
// instinct on finding a wrong sentence in a document is to edit that document,
// and here that is the one action guaranteed not to work.
const generatedNotice = "<!-- Generated by `flow docs generate`. Do not edit; edit the source it is derived from. -->"

// newDocsCommand builds the hidden `docs` command.
//
// Hidden and registered beside `flow man` in execute.go rather than in
// [newRootCommand], for the same reason that one is: it is a build step, not
// something a user types. Keeping it out of the root constructor also keeps it
// out of the command tree the README's pin tests and the generated CLI reference
// walk, which is correct — `flow docs generate` documents the product, and is
// not part of it.
func newDocsCommand() *cobra.Command {
	docs := &cobra.Command{
		Use:                   "docs",
		Short:                 "Generate reference documentation",
		Hidden:                true,
		SilenceUsage:          true,
		DisableFlagsInUseLine: true,
	}

	generate := &cobra.Command{
		Use:          "generate",
		Short:        "Write the generated reference into docs/reference/",
		Args:         cobra.NoArgs,
		SilenceUsage: true,
		RunE: func(cmd *cobra.Command, _ []string) error {
			dir, err := cmd.Flags().GetString("dir")
			if err != nil {
				return err
			}

			written, err := generateReference(dir)
			if err != nil {
				return err
			}

			for _, path := range written {
				fmt.Fprintln(cmd.OutOrStdout(), path)
			}

			return nil
		},
	}
	generate.Flags().String("dir", docsReferenceDir, "directory to write the generated reference into")

	docs.AddCommand(generate)

	return docs
}

// generateReference writes every generated document, returning their paths.
func generateReference(dir string) ([]string, error) {
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return nil, fmt.Errorf("creating %s: %w", dir, err)
	}

	var paths []string
	for _, doc := range referenceDocuments() {
		path := filepath.Join(dir, doc.name)
		if err := os.WriteFile(path, []byte(doc.render()), 0o644); err != nil {
			return nil, fmt.Errorf("writing %s: %w", path, err)
		}
		paths = append(paths, path)
	}

	return paths, nil
}

// referenceDocument is one generated file.
type referenceDocument struct {
	name   string
	render func() string
}

// referenceDocuments is the whole set, in a fixed order.
func referenceDocuments() []referenceDocument {
	return []referenceDocument{
		{name: "tasks.md", render: renderTaskReference},
		{name: "cli.md", render: renderCLIReference},
		{name: "mcp.md", render: renderMCPReference},
		{name: "envvars.md", render: renderEnvVarReference},
		{name: "diagnostics.md", render: renderDiagnosticCodeReference},
	}
}

// renderTaskReference documents what this build can execute.
//
// Derived from [v1.Catalog], which is the message the GetCatalog RPC returns
// unchanged — so the document and the RPC cannot describe different tasks. That
// is the point of going through the catalog rather than walking the registry
// here: a second traversal of the registry would be a second answer to "what can
// this build run", and the two would eventually differ in some detail nobody
// compares.
//
// Built-ins only. A plugin's tasks are a property of a deployment, not of this
// binary, and `flow plugins` is the command that asks a deployment.
func renderTaskReference() string {
	catalog := v1.Catalog()

	var b strings.Builder

	b.WriteString(generatedNotice + "\n\n")
	b.WriteString("# Task reference\n\n")
	b.WriteString("Every task this build can execute, with the inputs it takes and the outputs it\n")
	b.WriteString("produces. Derived from the task registry (the same `TaskCatalog` the `GetCatalog`\n")
	b.WriteString("RPC and `flow tasks` answer with), so a task cannot behave one way and document\n")
	b.WriteString("another.\n\n")
	b.WriteString("A plugin's tasks are not here: what a plugin adds is a property of a deployment\n")
	b.WriteString("rather than of this binary, and `flow plugins` is what asks a deployment.\n\n")

	b.WriteString("## Tasks\n\n")
	for _, task := range catalog.GetTasks() {
		fmt.Fprintf(&b, "### `%s`\n\n", task.GetName())
		if summary := task.GetSummary(); summary != "" {
			fmt.Fprintf(&b, "%s\n\n", summary)
		}

		writeTaskFields(&b, "Inputs", task.GetInputs(), true)
		writeTaskFields(&b, "Outputs", task.GetOutputs(), false)
	}

	b.WriteString("## Expressions\n\n")
	fmt.Fprintf(&b, "Values are reached through these roots: %s.\n\n", codeList(catalog.GetValueRoots()))
	fmt.Fprintf(&b, "Duration constructors, available to every expression: %s.\n\n", codeList(catalog.GetDurationUnits()))
	fmt.Fprintf(&b, "Inside a wait's own expressions (`sleep:`, `wait_until:`, and a signal's\n"+
		"`timeout:`) and nowhere else, `%s` is bound to the evaluation moment.\n\n",
		catalog.GetNowIdentifier())
	fmt.Fprintf(&b, "CEL libraries every expression reaches: %s.\n\n", codeList(catalog.GetCelLibraries()))

	b.WriteString("### Functions\n\n")
	b.WriteString("What those libraries add. A macro is expanded by the parser rather than called by\n")
	b.WriteString("the evaluator, so its name is not its whole call form; the example is.\n\n")
	b.WriteString("| Function | Library | Kind | Example |\n|---|---|---|---|\n")
	for _, fn := range catalog.GetCelFunctions() {
		kind := "function"
		if fn.GetMacro() {
			kind = "macro"
		}
		example := "—"
		if fn.GetExample() != "" {
			example = "`" + cell(fn.GetExample()) + "`"
		}
		fmt.Fprintf(&b, "| `%s` | `%s` | %s | %s |\n",
			cell(fn.GetName()), cell(fn.GetLibrary()), kind, example)
	}

	return b.String()
}

// writeTaskFields renders one task's inputs or outputs.
func writeTaskFields(b *strings.Builder, heading string, fields []*v1.TaskField, required bool) {
	fmt.Fprintf(b, "**%s**\n\n", heading)

	if len(fields) == 0 {
		b.WriteString("None.\n\n")

		return
	}

	if required {
		b.WriteString("| Name | Type | Required | Deferred | Bounds |\n|---|---|---|---|---|\n")
	} else {
		b.WriteString("| Name | Type | Bounds |\n|---|---|---|\n")
	}

	for _, field := range fields {
		// The bounds the schema and the task already carry, the same phrases `flow
		// tasks <name>` prints, because they come from the same field on the same
		// message. A reference that omitted them would send a reader who wants to
		// know how long a `credential:` may be to the proto, which is the drift this
		// document exists to prevent.
		bounds := "none"
		if constraints := field.GetConstraints(); len(constraints) > 0 {
			bounds = cell(strings.Join(constraints, "; "))
		}

		if !required {
			fmt.Fprintf(b, "| `%s` | `%s` | %s |\n",
				cell(field.GetName()), cell(field.GetType()), bounds)

			continue
		}

		fmt.Fprintf(b, "| `%s` | `%s` | %s | %s | %s |\n",
			cell(field.GetName()), cell(field.GetType()),
			yesNo(field.GetRequired()), yesNo(field.GetDeferred()), bounds)
	}
	b.WriteString("\n")
}

// renderCLIReference documents the command line, from the cobra tree.
//
// `newRootCommand` exists to be asked — the README's command pin tests already
// walk it — and this is the deeper form of the same question: not only which
// commands exist but what each one takes. Hidden commands are left out on the
// grounds that a hidden command is a build step rather than a capability.
func renderCLIReference() string {
	var commands []cliCommand
	var mirrors map[string]string

	withCleanEnvironment(func() {
		commands = describeCommands(newRootCommand())
		mirrors = environmentMirrors()
	})

	var b strings.Builder

	b.WriteString(generatedNotice + "\n\n")
	b.WriteString("# CLI reference\n\n")
	b.WriteString("Every command and flag `flow` has, derived from the cobra tree the binary builds\n")
	b.WriteString("at startup. [docs/CLI.md](../CLI.md) is the philosophy this surface holds itself\n")
	b.WriteString("to; this is the enumeration.\n\n")
	b.WriteString("A flag whose default comes from an environment variable says so. Those defaults\n")
	b.WriteString("are read when the command tree is built, which is why the generator clears the\n")
	b.WriteString("environment first: otherwise this document would record whoever ran it.\n\n")

	for _, cmd := range commands {
		fmt.Fprintf(&b, "## `%s`\n\n", cmd.path)
		if cmd.short != "" {
			fmt.Fprintf(&b, "%s\n\n", cmd.short)
		}
		fmt.Fprintf(&b, "```\n%s\n```\n\n", cmd.use)
		if cmd.long != "" && cmd.long != cmd.short {
			fmt.Fprintf(&b, "%s\n\n", cmd.long)
		}
		if cmd.example != "" {
			b.WriteString("Examples:\n\n")
			fmt.Fprintf(&b, "```sh\n%s\n```\n\n", cmd.example)
		}

		if len(cmd.flags) == 0 {
			continue
		}

		b.WriteString("| Flag | Type | Default | Environment | Description |\n|---|---|---|---|---|\n")
		for _, flag := range cmd.flags {
			fmt.Fprintf(&b, "| `%s` | `%s` | %s | %s | %s |\n",
				cell(flag.spelling), cell(flag.kind), orDash(codeOrEmpty(flag.defValue)),
				orDash(codeOrEmpty(mirrors[cmd.path+" "+flag.name])), cell(flag.usage))
		}
		b.WriteString("\n")
	}

	return b.String()
}

// cliCommand is one command, as the reference needs it.
type cliCommand struct {
	path    string
	use     string
	short   string
	long    string
	example string
	flags   []cliFlag
}

// cliFlag is one flag of one command.
type cliFlag struct {
	name     string
	spelling string
	kind     string
	defValue string
	usage    string
}

// describeCommands walks the tree, parents before children and siblings by name.
//
// cobra's own `help` and `completion` are left out for the reason the README's
// pin test leaves them out: they are the framework's commands rather than this
// tool's, and documenting them here would be describing cobra.
func describeCommands(root *cobra.Command) []cliCommand {
	out := []cliCommand{describeCommand(root)}

	children := slices.Clone(root.Commands())
	sort.Slice(children, func(i, j int) bool { return children[i].Name() < children[j].Name() })

	for _, child := range children {
		switch {
		case child.Hidden, child.Name() == "help", child.Name() == "completion":
			continue
		}
		out = append(out, describeCommands(child)...)
	}

	return out
}

// describeCommand reads one command's own documentation.
func describeCommand(cmd *cobra.Command) cliCommand {
	described := cliCommand{
		path:    cmd.CommandPath(),
		use:     useLine(cmd),
		short:   strings.TrimSpace(cmd.Short),
		long:    strings.TrimSpace(cmd.Long),
		example: strings.TrimSpace(cmd.Example),
	}

	seen := map[string]bool{}
	add := func(f *pflag.Flag) {
		if f.Hidden || seen[f.Name] {
			return
		}
		seen[f.Name] = true

		described.flags = append(described.flags, cliFlag{
			name:     f.Name,
			spelling: flagName(f),
			kind:     f.Value.Type(),
			defValue: f.DefValue,
			usage:    strings.TrimSpace(f.Usage),
		})
	}

	// Local flags only. An inherited flag is documented on the command that
	// declares it, and repeating `--verbose` on all twenty-two commands is a page
	// nobody reads twice.
	cmd.LocalFlags().VisitAll(add)

	sort.Slice(described.flags, func(i, j int) bool { return described.flags[i].name < described.flags[j].name })

	return described
}

// environmentMirrors reports which flag defaults come from which variable, keyed
// by "<command path> <flag>".
//
// Derived rather than declared, because pflag has nowhere to record it: a flag
// whose default is `os.Getenv("FLOWSTATE_ADDRESS")` looks exactly like one whose
// default is a constant. So each documented variable is set to a value nothing
// else could produce, the whole command tree is rebuilt, and any flag defaulting
// to that value is the flag that variable feeds.
//
// It answers for the mirrors and nothing else. A variable read as a *condition*
// rather than as a default — `FLOWSTATE_VERBOSE_LOGGING == "true"`, which yields
// a bool — cannot be seen this way, and the env-var reference says where those
// are read in prose. This finds every one that is genuinely a default, including
// one added tomorrow to a flag nobody remembers to document.
func environmentMirrors() map[string]string {
	mirrors := map[string]string{}

	for i, variable := range documentedEnvironmentVariables() {
		if variable.family {
			continue
		}

		sentinel := fmt.Sprintf("flowstate-docsgen-sentinel-%d", i)
		if err := os.Setenv(variable.name, sentinel); err != nil {
			continue
		}

		for _, cmd := range describeCommands(newRootCommand()) {
			for _, flag := range cmd.flags {
				if strings.Contains(flag.defValue, sentinel) {
					mirrors[cmd.path+" "+flag.name] = variable.name
				}
			}
		}

		_ = os.Unsetenv(variable.name)
	}

	return mirrors
}

// withCleanEnvironment runs f with every variable this reference documents
// removed, and puts the environment back afterwards.
//
// Both halves matter. Without the clearing, the generated CLI reference records
// the machine it ran on and CI's pin fails for the wrong reason. Without the
// restoring, the generator would be a command that quietly unconfigures the
// process it runs in.
func withCleanEnvironment(f func()) {
	saved := map[string]string{}
	for _, variable := range documentedEnvironmentVariables() {
		if value, found := os.LookupEnv(variable.name); found {
			saved[variable.name] = value
			_ = os.Unsetenv(variable.name)
		}
	}

	defer func() {
		for name, value := range saved {
			_ = os.Setenv(name, value)
		}
	}()

	f()
}

// renderMCPReference documents the agent surface.
//
// The tool set is derived: [workflowServiceMethods] is what `flow mcp` registers,
// asserted against the service descriptor in both directions by its own tests, so
// walking it here documents exactly what an agent connects to.
func renderMCPReference() string {
	var b strings.Builder

	b.WriteString(generatedNotice + "\n\n")
	b.WriteString("# MCP tool reference\n\n")
	b.WriteString("`flow mcp` serves the control plane to an agent over stdio. Every WorkflowService\n")
	b.WriteString("RPC becomes one tool, discovered by walking the service descriptor rather than\n")
	b.WriteString("kept in a list, so an RPC added to the schema is a tool the day the code is\n")
	b.WriteString("regenerated.\n\n")
	b.WriteString("**Answers locally** means the tool needs no server and no Temporal: authoring\n")
	b.WriteString("(validate, compile, read the catalog, rehearse a run) works with nothing else\n")
	b.WriteString("stood up. The rest address durable runs, which only a server has, and say so\n")
	b.WriteString("rather than failing opaquely when `--address` was not given.\n\n")

	b.WriteString("| Tool | Answers | Request message |\n|---|---|---|\n")
	for _, tool := range mcpTools() {
		fmt.Fprintf(&b, "| `%s` | %s | %s |\n", cell(tool.name), tool.reach(), orDash(codeOrEmpty(tool.request)))
	}
	b.WriteString("\n")

	for _, tool := range mcpTools() {
		fmt.Fprintf(&b, "## `%s`\n\n", tool.name)
		fmt.Fprintf(&b, "%s\n\n", tool.description)
	}

	return b.String()
}

// mcpTool is one tool as the reference describes it.
type mcpTool struct {
	name        string
	description string
	request     string
	local       bool
}

func (t mcpTool) reach() string {
	if t.local {
		return "locally"
	}

	return "via a server"
}

// mcpLocalTools names the tools that answer in this process.
//
// Hand-kept, and deliberately hard to add to. Which side a tool answers on is
// carried by the dispatch closure in mcp.go — a Go func value, which nothing can
// inspect from outside — so it is written down once here rather than guessed
// from a description's wording. [TestEveryMCPToolHasALocality] holds this to the
// registered tool set in both directions, so a tool added without a decision
// about where it answers fails rather than being documented wrong.
var mcpLocalTools = map[string]bool{
	"Validate":   true,
	"Compile":    true,
	"GetCatalog": true,
}

// mcpTools describes every tool `flow mcp` registers, in the order it registers
// them.
func mcpTools() []mcpTool {
	var tools []mcpTool
	for _, method := range workflowServiceMethods() {
		tools = append(tools, mcpTool{
			name:        mcpToolName(method.name),
			description: mcpToolDescription(method.name),
			request:     string(method.input.FullName()),
			local:       mcpLocalTools[method.name],
		})
	}

	tools = append(tools, mcpTool{
		name:        runLocalToolName,
		description: runLocalToolDescription,
		local:       true,
	})
	tools = append(tools, mcpTool{
		name:        testToolName,
		description: testToolDescription,
		local:       true,
	})

	return tools
}

// environmentVariable is one variable this build reads.
type environmentVariable struct {
	// name is the variable, or the family's spelling where family is set.
	name string

	// value is what happens when it is unset.
	value string

	// purpose is what setting it does.
	purpose string

	// read is where the process reads it, as a package path or file — so a reader
	// who doubts the sentence can go and check it.
	read string

	// family marks an entry that stands for a *set* of variables rather than one
	// name: `FLOWSTATE_SECRET_<NAME>`, the OTLP exporter's own configuration. The
	// drift test does not require a literal for these, and the mirror probe skips
	// them, because there is no single name to set.
	family bool
}

// documentedEnvironmentVariables is the one place this repository says which
// variables it reads.
//
// Hand-kept, because there is no registration point to derive it from: a variable
// is read wherever it is needed — a flag default here, a condition there, a size
// ceiling in the server — and inventing a registry every read site had to call
// would be a fifth thing to forget rather than a first thing to derive.
//
// What makes it honest is [TestEveryEnvironmentReadIsDocumented], which parses
// every non-test file under cmd/ and pkg/, collects the variable names they
// mention and every os.Getenv/os.LookupEnv call site, and fails on one this list
// does not carry — and fails the other way too, on an entry nothing reads any
// more. This table drifting is therefore a red test rather than a wrong document,
// which is the whole reason it is allowed to be written by hand.
func documentedEnvironmentVariables() []environmentVariable {
	return []environmentVariable{
		{
			name:    "FLOWSTATE_ADDRESS",
			value:   defaultServerAddress,
			purpose: "Address the API server listens on, and that the client commands connect to.",
			read:    "cmd/flow/client.go, cmd/flow/main.go",
		},
		{
			name:    "FLOWSTATE_ALLOW_LOOPBACK_EGRESS",
			value:   "unset",
			purpose: "Permit the `http` task to reach loopback addresses. Ignored while an `--egress-policy` file is in force: a policy that wants loopback says `allow_loopback: true`.",
			read:    "pkg/flowstate/v1/eval_task_library.go",
		},
		{
			name:    "FLOWSTATE_AUTH_POLICY",
			value:   "unset",
			purpose: "Default for `--auth-policy`: on `flow server` the trust policy naming which issuers and claims to accept; on `flow worker`, `flow run local` and `flow mcp` the same file's secrets rules, authorizing worker-side resolution.",
			read:    "cmd/flow/main.go, cmd/flow/mcp.go",
		},
		{
			name:    "FLOWSTATE_BACKGROUND",
			value:   "unset",
			purpose: "Declare the terminal background (`dark`/`light`) instead of querying for it. Also the way out of the four-second wait on a terminal that never answers the query.",
			read:    "cmd/flow/internal/ui/ui.go",
		},
		{
			name:    "FLOWSTATE_BUILD_ID",
			value:   "unset",
			purpose: "Default for `--build-id`: this worker binary's version identifier, unique per build. Required alongside the deployment name.",
			read:    "cmd/flow/main.go",
		},
		{
			name:    "FLOWSTATE_DEPLOYMENT_NAME",
			value:   "unset",
			purpose: "Default for `--deployment-name`: the Worker Deployment this worker belongs to. A worker refuses to start without both halves of a version unless `--allow-unversioned-interpreter` accepts the risk.",
			read:    "cmd/flow/main.go",
		},
		{
			name:    "FLOWSTATE_EGRESS_POLICY",
			value:   "unset",
			purpose: "Default for `--egress-policy`: a YAML policy governing the `http` task. When set it replaces the built-in policy entirely rather than merging with it.",
			read:    "cmd/flow/egress.go",
		},
		{
			name:    "FLOWSTATE_TASK_POLICY",
			value:   "unset",
			purpose: "Default for `--task-policy`: a YAML task-shape policy (#187) governing which identities may dispatch which tasks. When set it replaces the built-in policy (no restriction) entirely rather than merging with it.",
			read:    "cmd/flow/taskpolicy.go",
		},
		{
			name:    "FLOWSTATE_IDENTITY_KEY",
			value:   "unset",
			purpose: "Default for `--identity-key`: the PKCS#8 PEM key Flowstate signs its own short-lived assertions with, required when the trust policy configures federation.",
			read:    "cmd/flow/main.go, cmd/flow/mcp.go",
		},
		{
			name:    "FLOWSTATE_INSECURE_PLAINTEXT_TOKEN",
			value:   "false",
			purpose: "Set to `true` to permit sending a bearer token over plain HTTP to somewhere that is not loopback. A refusal by default, because a token on the wire in the clear belongs to whatever is between here and there.",
			read:    "cmd/flow/credentials.go",
		},
		{
			name:    "FLOWSTATE_MAX_STEPS_PER_RUN",
			value:   "unset",
			purpose: "Server-side ceiling on the steps one run may submit. An unparseable or non-positive value is ignored rather than lowering the bound.",
			read:    "pkg/flowstate/v1/server/server.go",
		},
		{
			name:    "FLOWSTATE_PLUGIN_DIR",
			value:   "unset",
			purpose: "Default for `--plugin-dir`: directories to discover plugins in, separated the way `$PATH` is, the form an image bakes in rather than repeating on every command line.",
			read:    "cmd/flow/plugins.go",
		},
		{
			name:    "FLOWSTATE_PLUGIN_HOST_FD",
			value:   "unset",
			purpose: "Handshake: the descriptor a plugin watches to learn its host has gone. Set by the host on the child process; never configured by an operator.",
			read:    "pkg/flowstate/v1/plugin/internal/protocol",
		},
		{
			name:    "FLOWSTATE_PLUGIN_MAGIC_COOKIE",
			value:   "unset",
			purpose: "Handshake: refuses to serve a plugin protocol to a process that did not mean to launch one. Set by the host on the child process.",
			read:    "pkg/flowstate/v1/plugin/internal/protocol",
		},
		{
			name:    "FLOWSTATE_PLUGIN_PROTOCOL_VERSIONS",
			value:   "unset",
			purpose: "Handshake: the protocol versions the host offers. Set by the host on the child process.",
			read:    "pkg/flowstate/v1/plugin/internal/protocol",
		},
		{
			name:    "FLOWSTATE_PLUGIN_SOCKET",
			value:   "unset",
			purpose: "Handshake: the socket path a plugin serves on. Set by the host on the child process.",
			read:    "pkg/flowstate/v1/plugin/internal/protocol",
		},
		{
			name:    "FLOWSTATE_PLUGIN_TOKEN",
			value:   "unset",
			purpose: "Handshake: the per-launch token a plugin authenticates its host with. Set by the host on the child process.",
			read:    "pkg/flowstate/v1/plugin/internal/protocol",
		},
		{
			name:    "FLOWSTATE_SECRET_COMMAND",
			value:   "unset",
			purpose: "Default for `--secret-command`: the argv of the command that resolves `command:` secrets, `$PATH`-list-separated (the executable first). `{{name}}` and, with `--secret-command-namespaced`, `{{namespace}}` are substituted literally into one argument, never through a shell.",
			read:    "cmd/flow/secrets.go",
		},
		{
			name:    "FLOWSTATE_SECRET_DIR",
			value:   "unset",
			purpose: "Default for `--secret-dir`: the directory `file:` secrets are read from.",
			read:    "cmd/flow/secrets.go",
		},
		{
			name:    "FLOWSTATE_SECRET_ENV_ALLOW",
			value:   "unset",
			purpose: "Default for `--secret-env`: comma-separated names this process may resolve as `env:` secrets.",
			read:    "cmd/flow/secrets.go",
		},
		{
			name:    "FLOWSTATE_SECRET_KEYCHAIN",
			value:   "unset",
			purpose: "Default for `--secret-keychain`: set to resolve `keychain:` secrets from the macOS keychain. Refused at startup, with a message naming the platform, on any OS other than macOS.",
			read:    "cmd/flow/secrets.go",
		},
		{
			name:    "FLOWSTATE_SECRET_KEYCHAIN_SERVICE",
			value:   "unset",
			purpose: "Default for `--secret-keychain-service`: the keychain service name entries are stored under, in place of the built-in default.",
			read:    "cmd/flow/secrets.go",
		},
		{
			name:    "FLOWSTATE_SECRET_OP",
			value:   "unset",
			purpose: "Default for `--secret-op`: set to resolve `op:` secrets through the 1Password CLI. Refused at startup when the `op` CLI is not on `PATH`.",
			read:    "cmd/flow/secrets.go",
		},
		{
			name:    "FLOWSTATE_SECRET_OP_VAULT",
			value:   "unset",
			purpose: "Default for `--secret-op-vault`: the 1Password vault read when a run has no namespace, in place of the built-in default.",
			read:    "cmd/flow/secrets.go",
		},
		{
			name:    "FLOWSTATE_SECRET_VAULT_ADDR",
			value:   "unset",
			purpose: "Default for `--secret-vault-addr`: the address of the Vault or OpenBao instance `vault:` secrets are read from. Unset, no vault provider is registered.",
			read:    "cmd/flow/secrets.go",
		},
		{
			name:    "FLOWSTATE_SECRET_VAULT_CA_FILE",
			value:   "unset",
			purpose: "Default for `--secret-vault-ca-file`: a PEM CA bundle to verify the vault's certificate against, instead of the system roots.",
			read:    "cmd/flow/secrets.go",
		},
		{
			name:    "FLOWSTATE_SECRET_VAULT_KUBERNETES_MOUNT",
			value:   "unset",
			purpose: "Default for `--secret-vault-kubernetes-mount`: where the Kubernetes auth method is mounted, in place of the built-in default.",
			read:    "cmd/flow/secrets.go",
		},
		{
			name:    "FLOWSTATE_SECRET_VAULT_KUBERNETES_ROLE",
			value:   "unset",
			purpose: "Default for `--secret-vault-kubernetes-role`: the Vault role to authenticate as via the Kubernetes auth method, using this pod's projected service account token. Exactly one of this or a token must be configured.",
			read:    "cmd/flow/secrets.go",
		},
		{
			name:    "FLOWSTATE_SECRET_VAULT_MOUNT",
			value:   "unset",
			purpose: "Default for `--secret-vault-mount`: where the KV v2 engine is mounted, in place of the built-in default.",
			read:    "cmd/flow/secrets.go",
		},
		{
			name:    "FLOWSTATE_SECRET_VAULT_NAMESPACE",
			value:   "unset",
			purpose: "Default for `--secret-vault-namespace`: the Vault Enterprise or OpenBao namespace header. This is the vault's own namespace, not the tenant namespace a run authenticates with.",
			read:    "cmd/flow/secrets.go",
		},
		{
			name:    "FLOWSTATE_SECRET_VAULT_PATH_PREFIX",
			value:   "unset",
			purpose: "Default for `--secret-vault-path-prefix`: a path prefix inside the mount, above the namespace segment.",
			read:    "cmd/flow/secrets.go",
		},
		{
			name:    "FLOWSTATE_SECRET_VAULT_TOKEN",
			value:   "unset",
			purpose: "A static Vault client token, read directly when `--secret-vault-token-file` (and `$FLOWSTATE_SECRET_VAULT_TOKEN_FILE`) is unset. For a development vault or a test; a long-running worker should prefer the file form or Kubernetes auth, since this one cannot be rotated without a restart.",
			read:    "cmd/flow/secrets.go",
		},
		{
			name:    "FLOWSTATE_SECRET_VAULT_TOKEN_FILE",
			value:   "unset",
			purpose: "Default for `--secret-vault-token-file`: a file holding a static Vault client token, re-read on every login so a rotated token is picked up without a restart.",
			read:    "cmd/flow/secrets.go",
		},
		{
			name:    "FLOWSTATE_SECRET_<NAME>",
			value:   "unset",
			purpose: "The value of an `env:` secret. Read only for a name the allowlist carries, and only inside the activity that applies it: the reference is what travels, never the value.",
			read:    "pkg/flowstate/v1/secrets/env.go",
			family:  true,
		},
		{
			name:    "FLOWSTATE_SYMBOLS",
			value:   "unset",
			purpose: "Override symbol selection (`unicode`/`ascii`) when terminal detection guesses wrong.",
			read:    "cmd/flow/internal/ui/ui.go",
		},
		{
			name:    "FLOWSTATE_TOKEN",
			value:   "unset",
			purpose: "Bearer token the client authenticates with, used when no token file is set.",
			read:    "cmd/flow/credentials.go",
		},
		{
			name:    "FLOWSTATE_TOKEN_FILE",
			value:   "unset",
			purpose: "Default for `--token-file`: a file holding the bearer token, re-read per request so a rotated token is picked up without a restart.",
			read:    "cmd/flow/client.go",
		},
		{
			name:    "FLOWSTATE_VERBOSE_LOGGING",
			value:   "false",
			purpose: "Default for `--verbose`. Read as a condition rather than as a string, so it does not appear as a flag default in the CLI reference.",
			read:    "cmd/flow/main.go",
		},
		{
			name:    "OTEL_EXPORTER_OTLP_ENDPOINT",
			value:   "unset",
			purpose: "Turns telemetry on and says where it goes. Unset means no exporter, no goroutines, no network.",
			read:    "cmd/flow/telemetry.go",
		},
		{
			name:    "OTEL_EXPORTER_OTLP_LOGS_ENDPOINT",
			value:   "unset",
			purpose: "The same, for a deployment sending logs somewhere different. Logs are exported through the OTLP log exporter beside stderr, never instead of it, so a collector is a destination gained, not exchanged.",
			read:    "cmd/flow/telemetry.go",
		},
		{
			name:    "OTEL_EXPORTER_OTLP_METRICS_ENDPOINT",
			value:   "unset",
			purpose: "The same, for a deployment sending metrics somewhere different. Any one of these variables being set enables telemetry.",
			read:    "cmd/flow/telemetry.go",
		},
		{
			name:    "OTEL_EXPORTER_OTLP_*",
			value:   "—",
			purpose: "Headers, protocol, timeouts and the rest: read by the OTLP exporters themselves rather than re-spelled here, so anything else OTLP-speaking is configured the same way.",
			read:    "go.opentelemetry.io/otel exporters",
			family:  true,
		},
		{
			name:  "FLOWSTATE_TASK_QUEUE_PREFIX",
			value: "unset",
			purpose: "Default for `--task-queue-prefix` on both `flow server` and `flow worker`: route each " +
				"tenant's runs to a task queue named `<prefix>_<namespace>` instead of the single shared " +
				"queue. Unset routes nothing, which is the zero-configuration behaviour. It has to be the " +
				"same value on the server and on every worker, because a worker that spelled it differently " +
				"would poll a queue nothing submits to, which is why one variable is the convenient way to " +
				"set it. A worker also needs `--tenant` to say which of those queues is its own.",
			read: "cmd/flow/main.go",
		},
		{
			name:  "TEMPORAL_ADDRESS",
			value: "unset",
			purpose: "Temporal's own environment configuration, honoured by every command that dials a " +
				"cluster: `flow server` and `flow worker` resolve it through the SDK, and `--address` " +
				"overrides it. `flow server dev` is the exception, and refuses to start while it is set: " +
				"that command starts a Temporal of its own, so a variable naming somebody else's cluster " +
				"would be silently unused while its operator believed their runs were landing there.",
			read: "cmd/flow/serverdev.go, go.temporal.io/sdk envconfig",
		},
		{
			name:  "TEMPORAL_PROFILE",
			value: "unset",
			purpose: "Selects a profile from the same `temporal.toml` the `temporal` CLI reads, which is " +
				"how one binary moves between a laptop, a self-hosted cluster and Cloud without a scheme " +
				"invented here. Refused by `flow server dev` for the same reason as `TEMPORAL_ADDRESS`.",
			read: "cmd/flow/serverdev.go, go.temporal.io/sdk envconfig",
		},
		{
			name:  "TEMPORAL_CONFIG_FILE",
			value: "unset",
			purpose: "Path to the TOML configuration file the profile is read from, honoured by the SDK's " +
				"environment configuration wherever a cluster is dialed. Refused by `flow server dev` for " +
				"the same reason as `TEMPORAL_ADDRESS`: an explicit file pointing at another cluster would " +
				"be the same silent misrouting through a different spelling.",
			read: "cmd/flow/serverdev.go, go.temporal.io/sdk envconfig",
		},
		{
			name:    "TEMPORAL_TASK_QUEUE",
			value:   "flowstate-run-task-queue",
			purpose: "Default for `--task-queue`: the queue workers serve and workflows are routed to.",
			read:    "cmd/flow/main.go",
		},
	}
}

// renderEnvVarReference documents every variable this build reads.
//
// The table VISION names as the proven drifter — it shipped ten variables short
// — so it is the one with the most machinery behind it. The prose is written by
// hand and the *set* is not: see [documentedEnvironmentVariables].
func renderEnvVarReference() string {
	var b strings.Builder

	b.WriteString(generatedNotice + "\n\n")
	b.WriteString("# Environment variable reference\n\n")
	b.WriteString("Every variable this build reads. There is no single registration point to derive\n")
	b.WriteString("this from (a variable is read where it is needed), so the prose is written by\n")
	b.WriteString("hand in `cmd/flow/docsgen.go` and the *set* is enforced: a test parses every\n")
	b.WriteString("non-test file under `cmd/` and `pkg/`, collects the variable names and the\n")
	b.WriteString("`os.Getenv`/`os.LookupEnv` call sites, and fails on a read this table does not\n")
	b.WriteString("carry or an entry nothing reads any more.\n\n")
	b.WriteString("Where a variable is the default of a flag, the flag wins when both are given.\n")
	b.WriteString("[cli.md](cli.md) says which flag each one feeds.\n\n")

	b.WriteString("| Variable | Default | Purpose | Read in |\n|---|---|---|---|\n")
	for _, variable := range documentedEnvironmentVariables() {
		fmt.Fprintf(&b, "| `%s` | %s | %s | `%s` |\n",
			cell(variable.name), orDash(codeOrEmpty(variable.value)), cell(variable.purpose), cell(variable.read))
	}

	return b.String()
}

// renderDiagnosticCodeReference documents every stable diagnostic code this
// build assigns.
//
// Derived from [v1.DiagnosticCodes] — the same registry flowfile's
// diagnostic-construction sites assign from — for the reason every generated
// document here exists: a code list kept by hand beside the code that assigns
// codes is a second source of truth, and CLAUDE.md's four proven driftors were
// all exactly that shape. TestDiagnosticCodesAreAssigned, in the flowfile
// package, is the other half — it holds the *registry* to the codes actually
// used, so this file documenting a code nothing assigns (or missing one that
// is assigned) fails there rather than only being wrong here.
func renderDiagnosticCodeReference() string {
	var b strings.Builder

	b.WriteString(generatedNotice + "\n\n")
	b.WriteString("# Diagnostic code reference\n\n")
	b.WriteString("Every stable `code` a [`Diagnostic`](../../proto/flowstate/v1/flowstate.proto)\n")
	b.WriteString("carries, so a program can decide what a validation failure *is* without parsing\n")
	b.WriteString("`message`, which this project reserves the right to reword. Deliberately small:\n")
	b.WriteString("only the classes an agent is actually expected to branch on have their own code,\n")
	b.WriteString("everything else is `general`, and that is documented rather than pretended away.\n\n")

	b.WriteString("| Code | Meaning |\n|---|---|\n")
	for _, info := range v1.DiagnosticCodes() {
		fmt.Fprintf(&b, "| `%s` | %s |\n", cell(string(info.Code)), cell(info.Description))
	}

	return b.String()
}

// cell makes a string safe to put in a markdown table cell.
func cell(text string) string {
	text = strings.ReplaceAll(text, "|", `\|`)
	text = strings.ReplaceAll(text, "\n", " ")

	return strings.TrimSpace(text)
}

// codeOrEmpty renders a value as code, or as nothing when there is none.
func codeOrEmpty(value string) string {
	if value == "" || value == "[]" {
		return ""
	}

	return "`" + cell(value) + "`"
}

// orDash gives an empty cell something to hold, since a blank one reads as an
// omission rather than as an absence.
func orDash(value string) string {
	if value == "" {
		return "—"
	}

	return value
}

// yesNo renders a boolean column.
func yesNo(value bool) string {
	if value {
		return "yes"
	}

	return "no"
}

// codeList renders names as an inline list, sorted.
//
// Sorted rather than kept in the catalog's order, because the order a listing
// arrives in is not something the catalog promises, and a document whose lines
// move for no reason is a document CI's pin fails on for no reason.
func codeList(names []string) string {
	var out []string
	for _, name := range slices.Sorted(slices.Values(names)) {
		out = append(out, "`"+cell(name)+"`")
	}
	if len(out) == 0 {
		return "none"
	}

	return strings.Join(out, ", ")
}
