// Package flowstatev1connect is the Connect RPC binding of the Flowstate API,
// flowstate.v1.WorkflowService, for programs that submit, observe, signal, and
// schedule runs on a Flowstate server.
//
// [NewWorkflowServiceClient] returns a client for a server's base URL, which is
// how the flow CLI talks to `flow server`; [NewWorkflowServiceHandler] mounts a
// [WorkflowServiceHandler] on an HTTP mux, and
// [github.com/picatz/flowstate/pkg/flowstate/v1/server.FlowstateServer] is the
// implementation Flowstate ships. The request and response messages live in
// [github.com/picatz/flowstate/pkg/flowstate/v1]. Everything except this file
// is generated by buf from proto/flowstate/v1/service.proto: change the schema
// and regenerate rather than editing the generated code.
package flowstatev1connect
