// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: flowstate/v1/exec_policy.proto

package flowstatev1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ExecPolicy is the deployment's answer to "which programs may a workflow
// start here", written as YAML (or JSON) and passed as `--exec-policy` or
// `FLOWSTATE_EXEC_POLICY`.
//
// # Why the file is a message
//
// The policy is read by the process that will run programs and is never sent
// anywhere, so it is not a wire shape in the usual sense. It is defined here
// anyway because it is a shape an operator authors and several tools read (the
// worker, `flow run local`, `flow task run`, the MCP and debug servers), and
// this schema is the one place where a shape gets one definition, its rules,
// and its documentation together.
//
// # What it is, and what it is not
//
// It is an allowlist of *what may be started*: which names map to which
// executables, which directories they may run in, which environment they see,
// and how long and how loud they may be. It is not a sandbox. The child runs
// with the worker's privileges, and nothing in this file restricts what it
// does afterwards (see Task.Exec).
//
// Without this file the built-in `exec` task is denied. There is no default
// policy and no way to enable the task from a workflow.
type ExecPolicy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Exec configures the built-in `exec` task. See [Exec].
	Exec          *ExecPolicy_Exec `protobuf:"bytes,1,opt,name=exec,proto3" json:"exec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecPolicy) Reset() {
	*x = ExecPolicy{}
	mi := &file_flowstate_v1_exec_policy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecPolicy) ProtoMessage() {}

func (x *ExecPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_flowstate_v1_exec_policy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecPolicy.ProtoReflect.Descriptor instead.
func (*ExecPolicy) Descriptor() ([]byte, []int) {
	return file_flowstate_v1_exec_policy_proto_rawDescGZIP(), []int{0}
}

func (x *ExecPolicy) GetExec() *ExecPolicy_Exec {
	if x != nil {
		return x.Exec
	}
	return nil
}

// Exec is the one section of the file today. It sits under a key of its own
// so that a later section (a second execution tier, for instance) is an
// addition and not a reshaping of every deployed file.
type ExecPolicy_Exec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Executables maps the program names a workflow may write as `argv[0]` to
	// the absolute path of the file that runs.
	//
	// A workflow names programs; only the operator locates them. The table is
	// the whole lookup: there is no search of PATH, and a name that is not a
	// key is refused. Every path is checked when the policy loads: absolute,
	// present, a regular file, executable, not writable by everyone, and
	// resolved through symbolic links to the file that will actually run.
	// Names are bare (no slash, no leading dash) so they cannot be mistaken for
	// paths or options.
	Executables map[string]string `protobuf:"bytes,1,rep,name=executables,proto3" json:"executables,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// ExecutableSha256 optionally pins an entry of [executables] to the SHA-256
	// of the file it resolves to, as 64 lowercase hex digits, keyed by the same
	// name.
	//
	// Checked at load against the resolved file, and again against the very
	// file descriptor that is executed where the platform allows it, so a file
	// swapped after the check does not run. A name with no pin is trusted by
	// path alone, which is the operator's decision to make per program. A pin
	// for a name that is not in [executables] is an error, not an ignored line.
	ExecutableSha256 map[string]string `protobuf:"bytes,2,rep,name=executable_sha256,json=executableSha256,proto3" json:"executable_sha256,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Roots are the absolute directories under which a step's `dir` must fall.
	//
	// Compared component by component after symbolic links are resolved on both
	// sides, so `/srv/work-evil` is not under `/srv/work` and a link inside a
	// root that points outside it does not admit the target. A policy with no
	// roots admits no directory, so the task cannot run: the worker's own
	// working directory is never a fallback.
	Roots []string `protobuf:"bytes,3,rep,name=roots,proto3" json:"roots,omitempty"`
	// EnvPassthrough lists worker environment variables copied into the child
	// when they are set in the worker, and skipped when they are not.
	//
	// The child never inherits the worker's environment wholesale, because the
	// worker's environment is where its credentials live. Loader-injection
	// variables (`LD_PRELOAD`, `LD_LIBRARY_PATH`, `LD_AUDIT`, and anything
	// starting `DYLD_`) are refused at load even if listed.
	EnvPassthrough []string `protobuf:"bytes,4,rep,name=env_passthrough,json=envPassthrough,proto3" json:"env_passthrough,omitempty"`
	// Env holds literal variables the operator sets for every child. A step
	// cannot override them. Values are text in the policy file, so they are
	// not the place for a credential: secret-valued environment is deliberately
	// not offered yet.
	Env map[string]string `protobuf:"bytes,5,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// EnvAuthored lists the variable names a *step* may set through its `env`
	// input. Empty means none: a workflow adds nothing to the environment unless
	// the operator named the key.
	EnvAuthored []string `protobuf:"bytes,6,rep,name=env_authored,json=envAuthored,proto3" json:"env_authored,omitempty"`
	// Timeout bounds how long one program may run, written as a duration such
	// as "10m". Required, positive, and at most one hour: there is no policy
	// spelling for "unbounded", and a file that asks for more than the ceiling
	// is refused at load rather than clamped, so the file says what is enforced.
	Timeout string `protobuf:"bytes,7,opt,name=timeout,proto3" json:"timeout,omitempty"`
	// MaxOutputBytes bounds what is kept of each output stream (standard output
	// and standard error separately), written the way sizes are said: "1MiB",
	// "10MB", or a bare count of bytes. Required, positive, and at most 16 MiB.
	// Bytes past the bound are read and discarded and the step reports the
	// stream as truncated.
	MaxOutputBytes string `protobuf:"bytes,8,opt,name=max_output_bytes,json=maxOutputBytes,proto3" json:"max_output_bytes,omitempty"`
	// Allow holds CEL allow rules. Configuring any turns the policy into an
	// allowlist: an invocation must match at least one. Rules read `argv`
	// (list of string), `executable` (the resolved absolute path), `name`
	// (argv[0] as written), `dir` (the cleaned absolute directory), `env_keys`
	// (the sorted names of the final environment, never its values) and
	// `identity` (subject, issuer, namespace, claims of the run's attested
	// workload). A policy with no allow rules permits what its other checks
	// admit.
	Allow []string `protobuf:"bytes,9,rep,name=allow,proto3" json:"allow,omitempty"`
	// Deny holds CEL deny rules, which run first and win. A rule that fails to
	// evaluate denies the invocation. Same variables as [allow].
	Deny          []string `protobuf:"bytes,10,rep,name=deny,proto3" json:"deny,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecPolicy_Exec) Reset() {
	*x = ExecPolicy_Exec{}
	mi := &file_flowstate_v1_exec_policy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecPolicy_Exec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecPolicy_Exec) ProtoMessage() {}

func (x *ExecPolicy_Exec) ProtoReflect() protoreflect.Message {
	mi := &file_flowstate_v1_exec_policy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecPolicy_Exec.ProtoReflect.Descriptor instead.
func (*ExecPolicy_Exec) Descriptor() ([]byte, []int) {
	return file_flowstate_v1_exec_policy_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ExecPolicy_Exec) GetExecutables() map[string]string {
	if x != nil {
		return x.Executables
	}
	return nil
}

func (x *ExecPolicy_Exec) GetExecutableSha256() map[string]string {
	if x != nil {
		return x.ExecutableSha256
	}
	return nil
}

func (x *ExecPolicy_Exec) GetRoots() []string {
	if x != nil {
		return x.Roots
	}
	return nil
}

func (x *ExecPolicy_Exec) GetEnvPassthrough() []string {
	if x != nil {
		return x.EnvPassthrough
	}
	return nil
}

func (x *ExecPolicy_Exec) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *ExecPolicy_Exec) GetEnvAuthored() []string {
	if x != nil {
		return x.EnvAuthored
	}
	return nil
}

func (x *ExecPolicy_Exec) GetTimeout() string {
	if x != nil {
		return x.Timeout
	}
	return ""
}

func (x *ExecPolicy_Exec) GetMaxOutputBytes() string {
	if x != nil {
		return x.MaxOutputBytes
	}
	return ""
}

func (x *ExecPolicy_Exec) GetAllow() []string {
	if x != nil {
		return x.Allow
	}
	return nil
}

func (x *ExecPolicy_Exec) GetDeny() []string {
	if x != nil {
		return x.Deny
	}
	return nil
}

var File_flowstate_v1_exec_policy_proto protoreflect.FileDescriptor

const file_flowstate_v1_exec_policy_proto_rawDesc = "" +
	"\n" +
	"\x1eflowstate/v1/exec_policy.proto\x12\fflowstate.v1\x1a\x1bbuf/validate/validate.proto\"\x86\b\n" +
	"\n" +
	"ExecPolicy\x121\n" +
	"\x04exec\x18\x01 \x01(\v2\x1d.flowstate.v1.ExecPolicy.ExecR\x04exec\x1a\xc4\a\n" +
	"\x04Exec\x12\x89\x01\n" +
	"\vexecutables\x18\x01 \x03(\v2..flowstate.v1.ExecPolicy.Exec.ExecutablesEntryB7\xbaH4\x9a\x011\"&r$\x10\x01\x18\x80\x012\x1d^[A-Za-z0-9][A-Za-z0-9._+-]*$*\ar\x05\x10\x01\x18\x80 R\vexecutables\x12\x85\x01\n" +
	"\x11executable_sha256\x18\x02 \x03(\v23.flowstate.v1.ExecPolicy.Exec.ExecutableSha256EntryB#\xbaH \x9a\x01\x1d\"\ar\x05\x10\x01\x18\x80\x01*\x12r\x102\x0e^[0-9a-f]{64}$R\x10executableSha256\x12'\n" +
	"\x05roots\x18\x03 \x03(\tB\x11\xbaH\x0e\x92\x01\v\x10@\"\ar\x05\x10\x01\x18\x80 R\x05roots\x12V\n" +
	"\x0fenv_passthrough\x18\x04 \x03(\tB-\xbaH*\x92\x01'\x10@\x18\x01\"!r\x1f\x10\x01\x18\x80\x012\x18^[A-Za-z_][A-Za-z0-9_]*$R\x0eenvPassthrough\x12l\n" +
	"\x03env\x18\x05 \x03(\v2&.flowstate.v1.ExecPolicy.Exec.EnvEntryB2\xbaH/\x9a\x01,\x10@\"!r\x1f\x10\x01\x18\x80\x012\x18^[A-Za-z_][A-Za-z0-9_]*$*\x05r\x03\x18\x80@R\x03env\x12P\n" +
	"\fenv_authored\x18\x06 \x03(\tB-\xbaH*\x92\x01'\x10@\x18\x01\"!r\x1f\x10\x01\x18\x80\x012\x18^[A-Za-z_][A-Za-z0-9_]*$R\venvAuthored\x12#\n" +
	"\atimeout\x18\a \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18 R\atimeout\x123\n" +
	"\x10max_output_bytes\x18\b \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18 R\x0emaxOutputBytes\x12(\n" +
	"\x05allow\x18\t \x03(\tB\x12\xbaH\x0f\x92\x01\f\x10\x80\x02\"\ar\x05\x10\x01\x18\x80 R\x05allow\x12&\n" +
	"\x04deny\x18\n" +
	" \x03(\tB\x12\xbaH\x0f\x92\x01\f\x10\x80\x02\"\ar\x05\x10\x01\x18\x80 R\x04deny\x1a>\n" +
	"\x10ExecutablesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aC\n" +
	"\x15ExecutableSha256Entry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\xae\x01\n" +
	"\x10com.flowstate.v1B\x0fExecPolicyProtoP\x01Z8github.com/picatz/flowstate/pkg/flowstate/v1;flowstatev1\xa2\x02\x03FXX\xaa\x02\fFlowstate.V1\xca\x02\fFlowstate\\V1\xe2\x02\x18Flowstate\\V1\\GPBMetadata\xea\x02\rFlowstate::V1b\x06proto3"

var (
	file_flowstate_v1_exec_policy_proto_rawDescOnce sync.Once
	file_flowstate_v1_exec_policy_proto_rawDescData []byte
)

func file_flowstate_v1_exec_policy_proto_rawDescGZIP() []byte {
	file_flowstate_v1_exec_policy_proto_rawDescOnce.Do(func() {
		file_flowstate_v1_exec_policy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_flowstate_v1_exec_policy_proto_rawDesc), len(file_flowstate_v1_exec_policy_proto_rawDesc)))
	})
	return file_flowstate_v1_exec_policy_proto_rawDescData
}

var file_flowstate_v1_exec_policy_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_flowstate_v1_exec_policy_proto_goTypes = []any{
	(*ExecPolicy)(nil),      // 0: flowstate.v1.ExecPolicy
	(*ExecPolicy_Exec)(nil), // 1: flowstate.v1.ExecPolicy.Exec
	nil,                     // 2: flowstate.v1.ExecPolicy.Exec.ExecutablesEntry
	nil,                     // 3: flowstate.v1.ExecPolicy.Exec.ExecutableSha256Entry
	nil,                     // 4: flowstate.v1.ExecPolicy.Exec.EnvEntry
}
var file_flowstate_v1_exec_policy_proto_depIdxs = []int32{
	1, // 0: flowstate.v1.ExecPolicy.exec:type_name -> flowstate.v1.ExecPolicy.Exec
	2, // 1: flowstate.v1.ExecPolicy.Exec.executables:type_name -> flowstate.v1.ExecPolicy.Exec.ExecutablesEntry
	3, // 2: flowstate.v1.ExecPolicy.Exec.executable_sha256:type_name -> flowstate.v1.ExecPolicy.Exec.ExecutableSha256Entry
	4, // 3: flowstate.v1.ExecPolicy.Exec.env:type_name -> flowstate.v1.ExecPolicy.Exec.EnvEntry
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_flowstate_v1_exec_policy_proto_init() }
func file_flowstate_v1_exec_policy_proto_init() {
	if File_flowstate_v1_exec_policy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_flowstate_v1_exec_policy_proto_rawDesc), len(file_flowstate_v1_exec_policy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_flowstate_v1_exec_policy_proto_goTypes,
		DependencyIndexes: file_flowstate_v1_exec_policy_proto_depIdxs,
		MessageInfos:      file_flowstate_v1_exec_policy_proto_msgTypes,
	}.Build()
	File_flowstate_v1_exec_policy_proto = out.File
	file_flowstate_v1_exec_policy_proto_goTypes = nil
	file_flowstate_v1_exec_policy_proto_depIdxs = nil
}
