// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: flowstate/v1/identity.proto

package flowstatev1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WorkloadIdentityMode says whether the host executing a workload established
// this call as production or as a rehearsal.
//
// UNSPECIFIED is deliberately the zero value and means unknown. A plugin built
// after this field was added receives it from an older host, rather than
// silently reading an old-host rehearsal as production. Plugins that gate side
// effects on this fact must admit only PRODUCTION, not merely reject REHEARSAL.
type WorkloadIdentityMode int32

const (
	// UNSPECIFIED means the host did not establish a mode, the identity was absent,
	// or the receiver does not understand the value. It is never evidence of a
	// production call.
	WorkloadIdentityMode_WORKLOAD_IDENTITY_MODE_UNSPECIFIED WorkloadIdentityMode = 0
	// PRODUCTION means the directly connected host established this as a durable
	// execution rather than a local rehearsal.
	WorkloadIdentityMode_WORKLOAD_IDENTITY_MODE_PRODUCTION WorkloadIdentityMode = 1
	// REHEARSAL means the directly connected host established this as a local,
	// unattested rehearsal.
	WorkloadIdentityMode_WORKLOAD_IDENTITY_MODE_REHEARSAL WorkloadIdentityMode = 2
)

// Enum value maps for WorkloadIdentityMode.
var (
	WorkloadIdentityMode_name = map[int32]string{
		0: "WORKLOAD_IDENTITY_MODE_UNSPECIFIED",
		1: "WORKLOAD_IDENTITY_MODE_PRODUCTION",
		2: "WORKLOAD_IDENTITY_MODE_REHEARSAL",
	}
	WorkloadIdentityMode_value = map[string]int32{
		"WORKLOAD_IDENTITY_MODE_UNSPECIFIED": 0,
		"WORKLOAD_IDENTITY_MODE_PRODUCTION":  1,
		"WORKLOAD_IDENTITY_MODE_REHEARSAL":   2,
	}
)

func (x WorkloadIdentityMode) Enum() *WorkloadIdentityMode {
	p := new(WorkloadIdentityMode)
	*p = x
	return p
}

func (x WorkloadIdentityMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkloadIdentityMode) Descriptor() protoreflect.EnumDescriptor {
	return file_flowstate_v1_identity_proto_enumTypes[0].Descriptor()
}

func (WorkloadIdentityMode) Type() protoreflect.EnumType {
	return &file_flowstate_v1_identity_proto_enumTypes[0]
}

func (x WorkloadIdentityMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkloadIdentityMode.Descriptor instead.
func (WorkloadIdentityMode) EnumDescriptor() ([]byte, []int) {
	return file_flowstate_v1_identity_proto_rawDescGZIP(), []int{0}
}

// WorkloadIdentity describes who a run acts as.
//
// A running workload has two identities at once, and both matter. It is a
// specific workload (this workflow, this run, this step) and it is acting on
// behalf of whoever asked for the work. Downstream systems need both to make an
// authorization decision: "the nightly-reconcile workflow" and "started by the
// deploy pipeline" answer different questions, and a system granting access
// usually cares about the pair.
//
// This is carried through the run so that every step knows what it is acting as,
// and so an assertion presented to an external system states something true
// rather than something assumed. It holds identity, never credentials: it is
// persisted in workflow history, which is durable and broadly readable, so
// nothing secret may appear here.
type WorkloadIdentity struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Subject identifies the caller that requested the run, as established by
	// authenticating their request. Empty when the run was started without
	// authentication, which is only possible in development.
	Subject string `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	// Issuer is the identity provider that vouched for the subject.
	Issuer string `protobuf:"bytes,2,opt,name=issuer,proto3" json:"issuer,omitempty"`
	// Claims carries additional non-secret claims from the caller's token that
	// authorization decisions may key on, such as a repository, environment, or
	// team. Only claims an operator has configured as relevant are copied here,
	// so this does not become a dumping ground for whole tokens.
	//
	// The bounds say the same thing the sentence above says, in a form the
	// machine enforces. They are the schema half of `auth.MaxCarriedClaims` and
	// its neighbours, which refuse the same sizes at mint: a claim set is a wire
	// format that gets signed and cached by relying parties, so an oversized one
	// has to be refused rather than truncated — a truncated claim set is a token
	// that says something other than what was authorized.
	//
	// 32 pairs is ten times the largest set anything in this repository carries
	// and twice `SignalPolicyRule.claims`'s bound; the key length is that rule's
	// own 128, since both name claims out of the same tokens. Values get 1024
	// rather than that rule's 256 because a carried value is data and not a
	// match pattern — the longest real one measured here is a 63-byte GitHub
	// Actions `job_workflow_ref`.
	//
	// `max_bytes` and not `max_len`, deliberately, and this is the whole reason
	// the unit is named in these field names. protovalidate's `max_len` is
	// `this.size()`, which counts Unicode *code points*; `max_bytes` is
	// `bytes(this).size()`, which is what Go's `len` on a string counts and what
	// `auth.validateCarriedClaims` therefore enforces. Under `max_len` a value of
	// 700 two-byte runes passes the schema at 700 and is refused at the mint at
	// 1400 bytes — one limit written down twice in two units, so the schema and
	// the mint disagree about which identities are valid, and the identity that
	// falls in the gap validates and then cannot obtain a credential. Same
	// number, same unit, both layers.
	Claims map[string]string `protobuf:"bytes,3,rep,name=claims,proto3" json:"claims,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Namespace is the tenant, and it is the boundary every authorization decision
	// about a run turns on: the caller's namespace is compared against the one
	// recorded on the run, and a mismatch is answered "no such run".
	//
	// Worth stating outright, because this field used to be described alongside
	// `deployment` as identifying "which Flowstate installation is running the
	// workload". That is what `deployment` is for. Reading the two as a pair
	// suggests both are labels for telling environments apart, and one of them
	// decides who may act on what.
	Namespace string `protobuf:"bytes,4,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// Deployment identifies which Flowstate installation is running the workload,
	// so an assertion from a staging deployment is distinguishable from a
	// production one.
	//
	// Not the tenant, and not what run access turns on: that is `namespace`
	// above. But not decorative either: an outbound authorization policy sees it as
	// `workload.deployment` and may key on it, which is how a rule like
	// `target == "internal" && workload.deployment == "prod"` keeps a staging
	// installation from assuming a production role.
	//
	// So the two are load-bearing for different decisions. `namespace` decides who
	// may act on a run; `deployment` is one of the attributes a policy may use to
	// decide what a run may reach.
	Deployment string `protobuf:"bytes,5,opt,name=deployment,proto3" json:"deployment,omitempty"`
	// Mode is an operational fact established by the host that launched and is
	// directly connected to the plugin. It is not a credential or an identity
	// claim, and a plugin must not derive it from subject, claims, task input, or
	// any workflow-authored value.
	//
	// Absence from an older host decodes as UNSPECIFIED (unknown), never
	// PRODUCTION. Unknown enum values must be treated the same way. A plugin
	// whose side effect is safe only in production therefore checks
	// mode == PRODUCTION; checking only mode != REHEARSAL is unsafe.
	//
	// Today's transport is a host-launched process over a private Unix socket,
	// so the launched host is authoritative for this fact. A future remote
	// plugin transport must authenticate the host and preserve that authority,
	// or replace this value with UNSPECIFIED rather than relay a caller-supplied
	// one.
	Mode          WorkloadIdentityMode `protobuf:"varint,6,opt,name=mode,proto3,enum=flowstate.v1.WorkloadIdentityMode" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkloadIdentity) Reset() {
	*x = WorkloadIdentity{}
	mi := &file_flowstate_v1_identity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadIdentity) ProtoMessage() {}

func (x *WorkloadIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_flowstate_v1_identity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadIdentity.ProtoReflect.Descriptor instead.
func (*WorkloadIdentity) Descriptor() ([]byte, []int) {
	return file_flowstate_v1_identity_proto_rawDescGZIP(), []int{0}
}

func (x *WorkloadIdentity) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *WorkloadIdentity) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *WorkloadIdentity) GetClaims() map[string]string {
	if x != nil {
		return x.Claims
	}
	return nil
}

func (x *WorkloadIdentity) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *WorkloadIdentity) GetDeployment() string {
	if x != nil {
		return x.Deployment
	}
	return ""
}

func (x *WorkloadIdentity) GetMode() WorkloadIdentityMode {
	if x != nil {
		return x.Mode
	}
	return WorkloadIdentityMode_WORKLOAD_IDENTITY_MODE_UNSPECIFIED
}

var File_flowstate_v1_identity_proto protoreflect.FileDescriptor

const file_flowstate_v1_identity_proto_rawDesc = "" +
	"\n" +
	"\x1bflowstate/v1/identity.proto\x12\fflowstate.v1\x1a\x1bbuf/validate/validate.proto\"\xd3\x02\n" +
	"\x10WorkloadIdentity\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x16\n" +
	"\x06issuer\x18\x02 \x01(\tR\x06issuer\x12\\\n" +
	"\x06claims\x18\x03 \x03(\v2*.flowstate.v1.WorkloadIdentity.ClaimsEntryB\x18\xbaH\x15\x9a\x01\x12\x10 \"\ar\x05 \x01(\x80\x01*\x05r\x03(\x80\bR\x06claims\x12\x1c\n" +
	"\tnamespace\x18\x04 \x01(\tR\tnamespace\x12\x1e\n" +
	"\n" +
	"deployment\x18\x05 \x01(\tR\n" +
	"deployment\x126\n" +
	"\x04mode\x18\x06 \x01(\x0e2\".flowstate.v1.WorkloadIdentityModeR\x04mode\x1a9\n" +
	"\vClaimsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\x8b\x01\n" +
	"\x14WorkloadIdentityMode\x12&\n" +
	"\"WORKLOAD_IDENTITY_MODE_UNSPECIFIED\x10\x00\x12%\n" +
	"!WORKLOAD_IDENTITY_MODE_PRODUCTION\x10\x01\x12$\n" +
	" WORKLOAD_IDENTITY_MODE_REHEARSAL\x10\x02B\xac\x01\n" +
	"\x10com.flowstate.v1B\rIdentityProtoP\x01Z8github.com/picatz/flowstate/pkg/flowstate/v1;flowstatev1\xa2\x02\x03FXX\xaa\x02\fFlowstate.V1\xca\x02\fFlowstate\\V1\xe2\x02\x18Flowstate\\V1\\GPBMetadata\xea\x02\rFlowstate::V1b\x06proto3"

var (
	file_flowstate_v1_identity_proto_rawDescOnce sync.Once
	file_flowstate_v1_identity_proto_rawDescData []byte
)

func file_flowstate_v1_identity_proto_rawDescGZIP() []byte {
	file_flowstate_v1_identity_proto_rawDescOnce.Do(func() {
		file_flowstate_v1_identity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_flowstate_v1_identity_proto_rawDesc), len(file_flowstate_v1_identity_proto_rawDesc)))
	})
	return file_flowstate_v1_identity_proto_rawDescData
}

var file_flowstate_v1_identity_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_flowstate_v1_identity_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_flowstate_v1_identity_proto_goTypes = []any{
	(WorkloadIdentityMode)(0), // 0: flowstate.v1.WorkloadIdentityMode
	(*WorkloadIdentity)(nil),  // 1: flowstate.v1.WorkloadIdentity
	nil,                       // 2: flowstate.v1.WorkloadIdentity.ClaimsEntry
}
var file_flowstate_v1_identity_proto_depIdxs = []int32{
	2, // 0: flowstate.v1.WorkloadIdentity.claims:type_name -> flowstate.v1.WorkloadIdentity.ClaimsEntry
	0, // 1: flowstate.v1.WorkloadIdentity.mode:type_name -> flowstate.v1.WorkloadIdentityMode
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_flowstate_v1_identity_proto_init() }
func file_flowstate_v1_identity_proto_init() {
	if File_flowstate_v1_identity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_flowstate_v1_identity_proto_rawDesc), len(file_flowstate_v1_identity_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_flowstate_v1_identity_proto_goTypes,
		DependencyIndexes: file_flowstate_v1_identity_proto_depIdxs,
		EnumInfos:         file_flowstate_v1_identity_proto_enumTypes,
		MessageInfos:      file_flowstate_v1_identity_proto_msgTypes,
	}.Build()
	File_flowstate_v1_identity_proto = out.File
	file_flowstate_v1_identity_proto_goTypes = nil
	file_flowstate_v1_identity_proto_depIdxs = nil
}
