// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: flowstate/v1/oauth.proto

package flowstatev1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProtocolRevision int32

const (
	ProtocolRevision_PROTOCOL_REVISION_UNSPECIFIED ProtocolRevision = 0
	ProtocolRevision_PROTOCOL_REVISION_OAUTH_2_0   ProtocolRevision = 1
	ProtocolRevision_PROTOCOL_REVISION_OAUTH_2_1   ProtocolRevision = 2
	ProtocolRevision_PROTOCOL_REVISION_OIDC_1_0    ProtocolRevision = 3
	ProtocolRevision_PROTOCOL_REVISION_RFC_8693    ProtocolRevision = 4
	ProtocolRevision_PROTOCOL_REVISION_RFC_8707    ProtocolRevision = 5
	ProtocolRevision_PROTOCOL_REVISION_RFC_9126    ProtocolRevision = 6
	ProtocolRevision_PROTOCOL_REVISION_RFC_9101    ProtocolRevision = 7
	ProtocolRevision_PROTOCOL_REVISION_RFC_9449    ProtocolRevision = 8
	ProtocolRevision_PROTOCOL_REVISION_RFC_9728    ProtocolRevision = 9
)

// Enum value maps for ProtocolRevision.
var (
	ProtocolRevision_name = map[int32]string{
		0: "PROTOCOL_REVISION_UNSPECIFIED",
		1: "PROTOCOL_REVISION_OAUTH_2_0",
		2: "PROTOCOL_REVISION_OAUTH_2_1",
		3: "PROTOCOL_REVISION_OIDC_1_0",
		4: "PROTOCOL_REVISION_RFC_8693",
		5: "PROTOCOL_REVISION_RFC_8707",
		6: "PROTOCOL_REVISION_RFC_9126",
		7: "PROTOCOL_REVISION_RFC_9101",
		8: "PROTOCOL_REVISION_RFC_9449",
		9: "PROTOCOL_REVISION_RFC_9728",
	}
	ProtocolRevision_value = map[string]int32{
		"PROTOCOL_REVISION_UNSPECIFIED": 0,
		"PROTOCOL_REVISION_OAUTH_2_0":   1,
		"PROTOCOL_REVISION_OAUTH_2_1":   2,
		"PROTOCOL_REVISION_OIDC_1_0":    3,
		"PROTOCOL_REVISION_RFC_8693":    4,
		"PROTOCOL_REVISION_RFC_8707":    5,
		"PROTOCOL_REVISION_RFC_9126":    6,
		"PROTOCOL_REVISION_RFC_9101":    7,
		"PROTOCOL_REVISION_RFC_9449":    8,
		"PROTOCOL_REVISION_RFC_9728":    9,
	}
)

func (x ProtocolRevision) Enum() *ProtocolRevision {
	p := new(ProtocolRevision)
	*p = x
	return p
}

func (x ProtocolRevision) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProtocolRevision) Descriptor() protoreflect.EnumDescriptor {
	return file_flowstate_v1_oauth_proto_enumTypes[0].Descriptor()
}

func (ProtocolRevision) Type() protoreflect.EnumType {
	return &file_flowstate_v1_oauth_proto_enumTypes[0]
}

func (x ProtocolRevision) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProtocolRevision.Descriptor instead.
func (ProtocolRevision) EnumDescriptor() ([]byte, []int) {
	return file_flowstate_v1_oauth_proto_rawDescGZIP(), []int{0}
}

type GrantType int32

const (
	GrantType_GRANT_TYPE_UNSPECIFIED        GrantType = 0
	GrantType_GRANT_TYPE_AUTHORIZATION_CODE GrantType = 1
	GrantType_GRANT_TYPE_CLIENT_CREDENTIALS GrantType = 2
	GrantType_GRANT_TYPE_TOKEN_EXCHANGE     GrantType = 3
	GrantType_GRANT_TYPE_JWT_BEARER         GrantType = 4
)

// Enum value maps for GrantType.
var (
	GrantType_name = map[int32]string{
		0: "GRANT_TYPE_UNSPECIFIED",
		1: "GRANT_TYPE_AUTHORIZATION_CODE",
		2: "GRANT_TYPE_CLIENT_CREDENTIALS",
		3: "GRANT_TYPE_TOKEN_EXCHANGE",
		4: "GRANT_TYPE_JWT_BEARER",
	}
	GrantType_value = map[string]int32{
		"GRANT_TYPE_UNSPECIFIED":        0,
		"GRANT_TYPE_AUTHORIZATION_CODE": 1,
		"GRANT_TYPE_CLIENT_CREDENTIALS": 2,
		"GRANT_TYPE_TOKEN_EXCHANGE":     3,
		"GRANT_TYPE_JWT_BEARER":         4,
	}
)

func (x GrantType) Enum() *GrantType {
	p := new(GrantType)
	*p = x
	return p
}

func (x GrantType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GrantType) Descriptor() protoreflect.EnumDescriptor {
	return file_flowstate_v1_oauth_proto_enumTypes[1].Descriptor()
}

func (GrantType) Type() protoreflect.EnumType {
	return &file_flowstate_v1_oauth_proto_enumTypes[1]
}

func (x GrantType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GrantType.Descriptor instead.
func (GrantType) EnumDescriptor() ([]byte, []int) {
	return file_flowstate_v1_oauth_proto_rawDescGZIP(), []int{1}
}

type ProofRequirement int32

const (
	ProofRequirement_PROOF_REQUIREMENT_UNSPECIFIED ProofRequirement = 0
	ProofRequirement_PROOF_REQUIREMENT_NONE        ProofRequirement = 1
	ProofRequirement_PROOF_REQUIREMENT_DPOP        ProofRequirement = 2
	ProofRequirement_PROOF_REQUIREMENT_MTLS        ProofRequirement = 3
)

// Enum value maps for ProofRequirement.
var (
	ProofRequirement_name = map[int32]string{
		0: "PROOF_REQUIREMENT_UNSPECIFIED",
		1: "PROOF_REQUIREMENT_NONE",
		2: "PROOF_REQUIREMENT_DPOP",
		3: "PROOF_REQUIREMENT_MTLS",
	}
	ProofRequirement_value = map[string]int32{
		"PROOF_REQUIREMENT_UNSPECIFIED": 0,
		"PROOF_REQUIREMENT_NONE":        1,
		"PROOF_REQUIREMENT_DPOP":        2,
		"PROOF_REQUIREMENT_MTLS":        3,
	}
)

func (x ProofRequirement) Enum() *ProofRequirement {
	p := new(ProofRequirement)
	*p = x
	return p
}

func (x ProofRequirement) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProofRequirement) Descriptor() protoreflect.EnumDescriptor {
	return file_flowstate_v1_oauth_proto_enumTypes[2].Descriptor()
}

func (ProofRequirement) Type() protoreflect.EnumType {
	return &file_flowstate_v1_oauth_proto_enumTypes[2]
}

func (x ProofRequirement) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProofRequirement.Descriptor instead.
func (ProofRequirement) EnumDescriptor() ([]byte, []int) {
	return file_flowstate_v1_oauth_proto_rawDescGZIP(), []int{2}
}

type TelemetryPrivacyClass int32

const (
	TelemetryPrivacyClass_TELEMETRY_PRIVACY_CLASS_UNSPECIFIED        TelemetryPrivacyClass = 0
	TelemetryPrivacyClass_TELEMETRY_PRIVACY_CLASS_PUBLIC             TelemetryPrivacyClass = 1
	TelemetryPrivacyClass_TELEMETRY_PRIVACY_CLASS_INTERNAL           TelemetryPrivacyClass = 2
	TelemetryPrivacyClass_TELEMETRY_PRIVACY_CLASS_SENSITIVE_METADATA TelemetryPrivacyClass = 3
)

// Enum value maps for TelemetryPrivacyClass.
var (
	TelemetryPrivacyClass_name = map[int32]string{
		0: "TELEMETRY_PRIVACY_CLASS_UNSPECIFIED",
		1: "TELEMETRY_PRIVACY_CLASS_PUBLIC",
		2: "TELEMETRY_PRIVACY_CLASS_INTERNAL",
		3: "TELEMETRY_PRIVACY_CLASS_SENSITIVE_METADATA",
	}
	TelemetryPrivacyClass_value = map[string]int32{
		"TELEMETRY_PRIVACY_CLASS_UNSPECIFIED":        0,
		"TELEMETRY_PRIVACY_CLASS_PUBLIC":             1,
		"TELEMETRY_PRIVACY_CLASS_INTERNAL":           2,
		"TELEMETRY_PRIVACY_CLASS_SENSITIVE_METADATA": 3,
	}
)

func (x TelemetryPrivacyClass) Enum() *TelemetryPrivacyClass {
	p := new(TelemetryPrivacyClass)
	*p = x
	return p
}

func (x TelemetryPrivacyClass) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TelemetryPrivacyClass) Descriptor() protoreflect.EnumDescriptor {
	return file_flowstate_v1_oauth_proto_enumTypes[3].Descriptor()
}

func (TelemetryPrivacyClass) Type() protoreflect.EnumType {
	return &file_flowstate_v1_oauth_proto_enumTypes[3]
}

func (x TelemetryPrivacyClass) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TelemetryPrivacyClass.Descriptor instead.
func (TelemetryPrivacyClass) EnumDescriptor() ([]byte, []int) {
	return file_flowstate_v1_oauth_proto_rawDescGZIP(), []int{3}
}

type DelegableField int32

const (
	DelegableField_DELEGABLE_FIELD_UNSPECIFIED       DelegableField = 0
	DelegableField_DELEGABLE_FIELD_TELEMETRY_PRIVACY DelegableField = 1
	DelegableField_DELEGABLE_FIELD_METADATA_LOCATION DelegableField = 2
)

// Enum value maps for DelegableField.
var (
	DelegableField_name = map[int32]string{
		0: "DELEGABLE_FIELD_UNSPECIFIED",
		1: "DELEGABLE_FIELD_TELEMETRY_PRIVACY",
		2: "DELEGABLE_FIELD_METADATA_LOCATION",
	}
	DelegableField_value = map[string]int32{
		"DELEGABLE_FIELD_UNSPECIFIED":       0,
		"DELEGABLE_FIELD_TELEMETRY_PRIVACY": 1,
		"DELEGABLE_FIELD_METADATA_LOCATION": 2,
	}
)

func (x DelegableField) Enum() *DelegableField {
	p := new(DelegableField)
	*p = x
	return p
}

func (x DelegableField) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DelegableField) Descriptor() protoreflect.EnumDescriptor {
	return file_flowstate_v1_oauth_proto_enumTypes[4].Descriptor()
}

func (DelegableField) Type() protoreflect.EnumType {
	return &file_flowstate_v1_oauth_proto_enumTypes[4]
}

func (x DelegableField) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DelegableField.Descriptor instead.
func (DelegableField) EnumDescriptor() ([]byte, []int) {
	return file_flowstate_v1_oauth_proto_rawDescGZIP(), []int{4}
}

// OAuthConfiguration is the complete, non-secret OAuth/OIDC and workload
// identity federation contract. It is safe to persist in workflow history.
// Credentials and key material are intentionally not representable here.
type OAuthConfiguration struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	AuthorizationServers []*AuthorizationServer `protobuf:"bytes,1,rep,name=authorization_servers,json=authorizationServers,proto3" json:"authorization_servers,omitempty"`
	ProtectedResources   []*ProtectedResource   `protobuf:"bytes,2,rep,name=protected_resources,json=protectedResources,proto3" json:"protected_resources,omitempty"`
	GrantProfiles        []*GrantProfile        `protobuf:"bytes,3,rep,name=grant_profiles,json=grantProfiles,proto3" json:"grant_profiles,omitempty"`
	Policies             []*PolicyReference     `protobuf:"bytes,4,rep,name=policies,proto3" json:"policies,omitempty"`
	TelemetryPrivacy     TelemetryPrivacyClass  `protobuf:"varint,5,opt,name=telemetry_privacy,json=telemetryPrivacy,proto3,enum=flowstate.v1.TelemetryPrivacyClass" json:"telemetry_privacy,omitempty"`
	// Names of deployment-owned fields that a lower layer may replace. Every
	// other collection is intersected and every requirement is strengthened.
	DelegableFields []DelegableField `protobuf:"varint,6,rep,packed,name=delegable_fields,json=delegableFields,proto3,enum=flowstate.v1.DelegableField" json:"delegable_fields,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OAuthConfiguration) Reset() {
	*x = OAuthConfiguration{}
	mi := &file_flowstate_v1_oauth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OAuthConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OAuthConfiguration) ProtoMessage() {}

func (x *OAuthConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_flowstate_v1_oauth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OAuthConfiguration.ProtoReflect.Descriptor instead.
func (*OAuthConfiguration) Descriptor() ([]byte, []int) {
	return file_flowstate_v1_oauth_proto_rawDescGZIP(), []int{0}
}

func (x *OAuthConfiguration) GetAuthorizationServers() []*AuthorizationServer {
	if x != nil {
		return x.AuthorizationServers
	}
	return nil
}

func (x *OAuthConfiguration) GetProtectedResources() []*ProtectedResource {
	if x != nil {
		return x.ProtectedResources
	}
	return nil
}

func (x *OAuthConfiguration) GetGrantProfiles() []*GrantProfile {
	if x != nil {
		return x.GrantProfiles
	}
	return nil
}

func (x *OAuthConfiguration) GetPolicies() []*PolicyReference {
	if x != nil {
		return x.Policies
	}
	return nil
}

func (x *OAuthConfiguration) GetTelemetryPrivacy() TelemetryPrivacyClass {
	if x != nil {
		return x.TelemetryPrivacy
	}
	return TelemetryPrivacyClass_TELEMETRY_PRIVACY_CLASS_UNSPECIFIED
}

func (x *OAuthConfiguration) GetDelegableFields() []DelegableField {
	if x != nil {
		return x.DelegableFields
	}
	return nil
}

type AuthorizationServer struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Name                string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Issuer              string                 `protobuf:"bytes,2,opt,name=issuer,proto3" json:"issuer,omitempty"`
	AuthorizationServer string                 `protobuf:"bytes,3,opt,name=authorization_server,json=authorizationServer,proto3" json:"authorization_server,omitempty"`
	Metadata            *MetadataLocation      `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Revisions           []ProtocolRevision     `protobuf:"varint,5,rep,packed,name=revisions,proto3,enum=flowstate.v1.ProtocolRevision" json:"revisions,omitempty"`
	EndpointTrust       *EndpointTrustRule     `protobuf:"bytes,6,opt,name=endpoint_trust,json=endpointTrust,proto3" json:"endpoint_trust,omitempty"`
	Cache               *CacheBounds           `protobuf:"bytes,7,opt,name=cache,proto3" json:"cache,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AuthorizationServer) Reset() {
	*x = AuthorizationServer{}
	mi := &file_flowstate_v1_oauth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizationServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizationServer) ProtoMessage() {}

func (x *AuthorizationServer) ProtoReflect() protoreflect.Message {
	mi := &file_flowstate_v1_oauth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizationServer.ProtoReflect.Descriptor instead.
func (*AuthorizationServer) Descriptor() ([]byte, []int) {
	return file_flowstate_v1_oauth_proto_rawDescGZIP(), []int{1}
}

func (x *AuthorizationServer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AuthorizationServer) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *AuthorizationServer) GetAuthorizationServer() string {
	if x != nil {
		return x.AuthorizationServer
	}
	return ""
}

func (x *AuthorizationServer) GetMetadata() *MetadataLocation {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *AuthorizationServer) GetRevisions() []ProtocolRevision {
	if x != nil {
		return x.Revisions
	}
	return nil
}

func (x *AuthorizationServer) GetEndpointTrust() *EndpointTrustRule {
	if x != nil {
		return x.EndpointTrust
	}
	return nil
}

func (x *AuthorizationServer) GetCache() *CacheBounds {
	if x != nil {
		return x.Cache
	}
	return nil
}

type ProtectedResource struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Name                     string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Resource                 string                 `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	Metadata                 *MetadataLocation      `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	AuthorizationServers     []string               `protobuf:"bytes,4,rep,name=authorization_servers,json=authorizationServers,proto3" json:"authorization_servers,omitempty"`
	Scopes                   []string               `protobuf:"bytes,5,rep,name=scopes,proto3" json:"scopes,omitempty"`
	AuthorizationDetailTypes []string               `protobuf:"bytes,6,rep,name=authorization_detail_types,json=authorizationDetailTypes,proto3" json:"authorization_detail_types,omitempty"`
	Proof                    ProofRequirement       `protobuf:"varint,7,opt,name=proof,proto3,enum=flowstate.v1.ProofRequirement" json:"proof,omitempty"`
	Assurance                *AssuranceRequirement  `protobuf:"bytes,8,opt,name=assurance,proto3" json:"assurance,omitempty"`
	TelemetryPrivacy         TelemetryPrivacyClass  `protobuf:"varint,9,opt,name=telemetry_privacy,json=telemetryPrivacy,proto3,enum=flowstate.v1.TelemetryPrivacyClass" json:"telemetry_privacy,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *ProtectedResource) Reset() {
	*x = ProtectedResource{}
	mi := &file_flowstate_v1_oauth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtectedResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtectedResource) ProtoMessage() {}

func (x *ProtectedResource) ProtoReflect() protoreflect.Message {
	mi := &file_flowstate_v1_oauth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtectedResource.ProtoReflect.Descriptor instead.
func (*ProtectedResource) Descriptor() ([]byte, []int) {
	return file_flowstate_v1_oauth_proto_rawDescGZIP(), []int{2}
}

func (x *ProtectedResource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProtectedResource) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *ProtectedResource) GetMetadata() *MetadataLocation {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ProtectedResource) GetAuthorizationServers() []string {
	if x != nil {
		return x.AuthorizationServers
	}
	return nil
}

func (x *ProtectedResource) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

func (x *ProtectedResource) GetAuthorizationDetailTypes() []string {
	if x != nil {
		return x.AuthorizationDetailTypes
	}
	return nil
}

func (x *ProtectedResource) GetProof() ProofRequirement {
	if x != nil {
		return x.Proof
	}
	return ProofRequirement_PROOF_REQUIREMENT_UNSPECIFIED
}

func (x *ProtectedResource) GetAssurance() *AssuranceRequirement {
	if x != nil {
		return x.Assurance
	}
	return nil
}

func (x *ProtectedResource) GetTelemetryPrivacy() TelemetryPrivacyClass {
	if x != nil {
		return x.TelemetryPrivacy
	}
	return TelemetryPrivacyClass_TELEMETRY_PRIVACY_CLASS_UNSPECIFIED
}

type MetadataLocation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Location:
	//
	//	*MetadataLocation_DiscoveryUrl
	//	*MetadataLocation_StaticDocumentRef
	Location      isMetadataLocation_Location `protobuf_oneof:"location"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataLocation) Reset() {
	*x = MetadataLocation{}
	mi := &file_flowstate_v1_oauth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataLocation) ProtoMessage() {}

func (x *MetadataLocation) ProtoReflect() protoreflect.Message {
	mi := &file_flowstate_v1_oauth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataLocation.ProtoReflect.Descriptor instead.
func (*MetadataLocation) Descriptor() ([]byte, []int) {
	return file_flowstate_v1_oauth_proto_rawDescGZIP(), []int{3}
}

func (x *MetadataLocation) GetLocation() isMetadataLocation_Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *MetadataLocation) GetDiscoveryUrl() string {
	if x != nil {
		if x, ok := x.Location.(*MetadataLocation_DiscoveryUrl); ok {
			return x.DiscoveryUrl
		}
	}
	return ""
}

func (x *MetadataLocation) GetStaticDocumentRef() string {
	if x != nil {
		if x, ok := x.Location.(*MetadataLocation_StaticDocumentRef); ok {
			return x.StaticDocumentRef
		}
	}
	return ""
}

type isMetadataLocation_Location interface {
	isMetadataLocation_Location()
}

type MetadataLocation_DiscoveryUrl struct {
	DiscoveryUrl string `protobuf:"bytes,1,opt,name=discovery_url,json=discoveryUrl,proto3,oneof"`
}

type MetadataLocation_StaticDocumentRef struct {
	StaticDocumentRef string `protobuf:"bytes,2,opt,name=static_document_ref,json=staticDocumentRef,proto3,oneof"`
}

func (*MetadataLocation_DiscoveryUrl) isMetadataLocation_Location() {}

func (*MetadataLocation_StaticDocumentRef) isMetadataLocation_Location() {}

type GrantProfile struct {
	state                         protoimpl.MessageState `protogen:"open.v1"`
	Name                          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Grant                         GrantType              `protobuf:"varint,2,opt,name=grant,proto3,enum=flowstate.v1.GrantType" json:"grant,omitempty"`
	Revisions                     []ProtocolRevision     `protobuf:"varint,3,rep,packed,name=revisions,proto3,enum=flowstate.v1.ProtocolRevision" json:"revisions,omitempty"`
	Audiences                     []string               `protobuf:"bytes,4,rep,name=audiences,proto3" json:"audiences,omitempty"`
	Resources                     []string               `protobuf:"bytes,5,rep,name=resources,proto3" json:"resources,omitempty"`
	Scopes                        []string               `protobuf:"bytes,6,rep,name=scopes,proto3" json:"scopes,omitempty"`
	AuthorizationDetailTypes      []string               `protobuf:"bytes,7,rep,name=authorization_detail_types,json=authorizationDetailTypes,proto3" json:"authorization_detail_types,omitempty"`
	ClientId                      string                 `protobuf:"bytes,8,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ClientAuthenticationMethodRef string                 `protobuf:"bytes,9,opt,name=client_authentication_method_ref,json=clientAuthenticationMethodRef,proto3" json:"client_authentication_method_ref,omitempty"`
	Proof                         ProofRequirement       `protobuf:"varint,10,opt,name=proof,proto3,enum=flowstate.v1.ProofRequirement" json:"proof,omitempty"`
	Assurance                     *AssuranceRequirement  `protobuf:"bytes,11,opt,name=assurance,proto3" json:"assurance,omitempty"`
	RequirePar                    bool                   `protobuf:"varint,12,opt,name=require_par,json=requirePar,proto3" json:"require_par,omitempty"`
	RequireJar                    bool                   `protobuf:"varint,13,opt,name=require_jar,json=requireJar,proto3" json:"require_jar,omitempty"`
	Policies                      []*PolicyReference     `protobuf:"bytes,14,rep,name=policies,proto3" json:"policies,omitempty"`
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *GrantProfile) Reset() {
	*x = GrantProfile{}
	mi := &file_flowstate_v1_oauth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrantProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantProfile) ProtoMessage() {}

func (x *GrantProfile) ProtoReflect() protoreflect.Message {
	mi := &file_flowstate_v1_oauth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantProfile.ProtoReflect.Descriptor instead.
func (*GrantProfile) Descriptor() ([]byte, []int) {
	return file_flowstate_v1_oauth_proto_rawDescGZIP(), []int{4}
}

func (x *GrantProfile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GrantProfile) GetGrant() GrantType {
	if x != nil {
		return x.Grant
	}
	return GrantType_GRANT_TYPE_UNSPECIFIED
}

func (x *GrantProfile) GetRevisions() []ProtocolRevision {
	if x != nil {
		return x.Revisions
	}
	return nil
}

func (x *GrantProfile) GetAudiences() []string {
	if x != nil {
		return x.Audiences
	}
	return nil
}

func (x *GrantProfile) GetResources() []string {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *GrantProfile) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

func (x *GrantProfile) GetAuthorizationDetailTypes() []string {
	if x != nil {
		return x.AuthorizationDetailTypes
	}
	return nil
}

func (x *GrantProfile) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *GrantProfile) GetClientAuthenticationMethodRef() string {
	if x != nil {
		return x.ClientAuthenticationMethodRef
	}
	return ""
}

func (x *GrantProfile) GetProof() ProofRequirement {
	if x != nil {
		return x.Proof
	}
	return ProofRequirement_PROOF_REQUIREMENT_UNSPECIFIED
}

func (x *GrantProfile) GetAssurance() *AssuranceRequirement {
	if x != nil {
		return x.Assurance
	}
	return nil
}

func (x *GrantProfile) GetRequirePar() bool {
	if x != nil {
		return x.RequirePar
	}
	return false
}

func (x *GrantProfile) GetRequireJar() bool {
	if x != nil {
		return x.RequireJar
	}
	return false
}

func (x *GrantProfile) GetPolicies() []*PolicyReference {
	if x != nil {
		return x.Policies
	}
	return nil
}

type AssuranceRequirement struct {
	state                           protoimpl.MessageState `protogen:"open.v1"`
	AcrValues                       []string               `protobuf:"bytes,1,rep,name=acr_values,json=acrValues,proto3" json:"acr_values,omitempty"`
	MinimumAuthenticationAgeSeconds uint32                 `protobuf:"varint,2,opt,name=minimum_authentication_age_seconds,json=minimumAuthenticationAgeSeconds,proto3" json:"minimum_authentication_age_seconds,omitempty"`
	RequireStepUp                   bool                   `protobuf:"varint,3,opt,name=require_step_up,json=requireStepUp,proto3" json:"require_step_up,omitempty"`
	unknownFields                   protoimpl.UnknownFields
	sizeCache                       protoimpl.SizeCache
}

func (x *AssuranceRequirement) Reset() {
	*x = AssuranceRequirement{}
	mi := &file_flowstate_v1_oauth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssuranceRequirement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssuranceRequirement) ProtoMessage() {}

func (x *AssuranceRequirement) ProtoReflect() protoreflect.Message {
	mi := &file_flowstate_v1_oauth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssuranceRequirement.ProtoReflect.Descriptor instead.
func (*AssuranceRequirement) Descriptor() ([]byte, []int) {
	return file_flowstate_v1_oauth_proto_rawDescGZIP(), []int{5}
}

func (x *AssuranceRequirement) GetAcrValues() []string {
	if x != nil {
		return x.AcrValues
	}
	return nil
}

func (x *AssuranceRequirement) GetMinimumAuthenticationAgeSeconds() uint32 {
	if x != nil {
		return x.MinimumAuthenticationAgeSeconds
	}
	return 0
}

func (x *AssuranceRequirement) GetRequireStepUp() bool {
	if x != nil {
		return x.RequireStepUp
	}
	return false
}

type EndpointTrustRule struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RequireHttps      bool                   `protobuf:"varint,1,opt,name=require_https,json=requireHttps,proto3" json:"require_https,omitempty"`
	RequireSameOrigin bool                   `protobuf:"varint,2,opt,name=require_same_origin,json=requireSameOrigin,proto3" json:"require_same_origin,omitempty"`
	AllowedOrigins    []string               `protobuf:"bytes,3,rep,name=allowed_origins,json=allowedOrigins,proto3" json:"allowed_origins,omitempty"`
	PinnedCaRefs      []string               `protobuf:"bytes,4,rep,name=pinned_ca_refs,json=pinnedCaRefs,proto3" json:"pinned_ca_refs,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *EndpointTrustRule) Reset() {
	*x = EndpointTrustRule{}
	mi := &file_flowstate_v1_oauth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndpointTrustRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndpointTrustRule) ProtoMessage() {}

func (x *EndpointTrustRule) ProtoReflect() protoreflect.Message {
	mi := &file_flowstate_v1_oauth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndpointTrustRule.ProtoReflect.Descriptor instead.
func (*EndpointTrustRule) Descriptor() ([]byte, []int) {
	return file_flowstate_v1_oauth_proto_rawDescGZIP(), []int{6}
}

func (x *EndpointTrustRule) GetRequireHttps() bool {
	if x != nil {
		return x.RequireHttps
	}
	return false
}

func (x *EndpointTrustRule) GetRequireSameOrigin() bool {
	if x != nil {
		return x.RequireSameOrigin
	}
	return false
}

func (x *EndpointTrustRule) GetAllowedOrigins() []string {
	if x != nil {
		return x.AllowedOrigins
	}
	return nil
}

func (x *EndpointTrustRule) GetPinnedCaRefs() []string {
	if x != nil {
		return x.PinnedCaRefs
	}
	return nil
}

type CacheBounds struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaximumAge    *durationpb.Duration   `protobuf:"bytes,1,opt,name=maximum_age,json=maximumAge,proto3" json:"maximum_age,omitempty"`
	StaleIfError  *durationpb.Duration   `protobuf:"bytes,2,opt,name=stale_if_error,json=staleIfError,proto3" json:"stale_if_error,omitempty"`
	ClockSkew     *durationpb.Duration   `protobuf:"bytes,3,opt,name=clock_skew,json=clockSkew,proto3" json:"clock_skew,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheBounds) Reset() {
	*x = CacheBounds{}
	mi := &file_flowstate_v1_oauth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheBounds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheBounds) ProtoMessage() {}

func (x *CacheBounds) ProtoReflect() protoreflect.Message {
	mi := &file_flowstate_v1_oauth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheBounds.ProtoReflect.Descriptor instead.
func (*CacheBounds) Descriptor() ([]byte, []int) {
	return file_flowstate_v1_oauth_proto_rawDescGZIP(), []int{7}
}

func (x *CacheBounds) GetMaximumAge() *durationpb.Duration {
	if x != nil {
		return x.MaximumAge
	}
	return nil
}

func (x *CacheBounds) GetStaleIfError() *durationpb.Duration {
	if x != nil {
		return x.StaleIfError
	}
	return nil
}

func (x *CacheBounds) GetClockSkew() *durationpb.Duration {
	if x != nil {
		return x.ClockSkew
	}
	return nil
}

type PolicyReference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Revision      string                 `protobuf:"bytes,2,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyReference) Reset() {
	*x = PolicyReference{}
	mi := &file_flowstate_v1_oauth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyReference) ProtoMessage() {}

func (x *PolicyReference) ProtoReflect() protoreflect.Message {
	mi := &file_flowstate_v1_oauth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyReference.ProtoReflect.Descriptor instead.
func (*PolicyReference) Descriptor() ([]byte, []int) {
	return file_flowstate_v1_oauth_proto_rawDescGZIP(), []int{8}
}

func (x *PolicyReference) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PolicyReference) GetRevision() string {
	if x != nil {
		return x.Revision
	}
	return ""
}

// SecretReference identifies material resolved only by the boundary using it.
// It names a value but can never contain that value.
type SecretReference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version       *string                `protobuf:"bytes,3,opt,name=version,proto3,oneof" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretReference) Reset() {
	*x = SecretReference{}
	mi := &file_flowstate_v1_oauth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretReference) ProtoMessage() {}

func (x *SecretReference) ProtoReflect() protoreflect.Message {
	mi := &file_flowstate_v1_oauth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretReference.ProtoReflect.Descriptor instead.
func (*SecretReference) Descriptor() ([]byte, []int) {
	return file_flowstate_v1_oauth_proto_rawDescGZIP(), []int{9}
}

func (x *SecretReference) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *SecretReference) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SecretReference) GetVersion() string {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return ""
}

var File_flowstate_v1_oauth_proto protoreflect.FileDescriptor

const file_flowstate_v1_oauth_proto_rawDesc = "" +
	"\n" +
	"\x18flowstate/v1/oauth.proto\x12\fflowstate.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1egoogle/protobuf/duration.proto\"\xa1\x04\n" +
	"\x12OAuthConfiguration\x12`\n" +
	"\x15authorization_servers\x18\x01 \x03(\v2!.flowstate.v1.AuthorizationServerB\b\xbaH\x05\x92\x01\x02\x10@R\x14authorizationServers\x12[\n" +
	"\x13protected_resources\x18\x02 \x03(\v2\x1f.flowstate.v1.ProtectedResourceB\t\xbaH\x06\x92\x01\x03\x10\x80\x01R\x12protectedResources\x12K\n" +
	"\x0egrant_profiles\x18\x03 \x03(\v2\x1a.flowstate.v1.GrantProfileB\b\xbaH\x05\x92\x01\x02\x10@R\rgrantProfiles\x12C\n" +
	"\bpolicies\x18\x04 \x03(\v2\x1d.flowstate.v1.PolicyReferenceB\b\xbaH\x05\x92\x01\x02\x10@R\bpolicies\x12\\\n" +
	"\x11telemetry_privacy\x18\x05 \x01(\x0e2#.flowstate.v1.TelemetryPrivacyClassB\n" +
	"\xbaH\a\x82\x01\x04\x10\x01 \x00R\x10telemetryPrivacy\x12\\\n" +
	"\x10delegable_fields\x18\x06 \x03(\x0e2\x1c.flowstate.v1.DelegableFieldB\x13\xbaH\x10\x92\x01\r\x10\x10\x18\x01\"\a\x82\x01\x04\x10\x01 \x00R\x0fdelegableFields\"\xda\x03\n" +
	"\x13AuthorizationServer\x12<\n" +
	"\x04name\x18\x01 \x01(\tB(\xbaH%r#\x10\x01\x18\x80\x012\x1c^[A-Za-z0-9][A-Za-z0-9._-]*$R\x04name\x12#\n" +
	"\x06issuer\x18\x02 \x01(\tB\v\xbaH\br\x06\x18\x80\x10\x88\x01\x01R\x06issuer\x12>\n" +
	"\x14authorization_server\x18\x03 \x01(\tB\v\xbaH\br\x06\x18\x80\x10\x88\x01\x01R\x13authorizationServer\x12B\n" +
	"\bmetadata\x18\x04 \x01(\v2\x1e.flowstate.v1.MetadataLocationB\x06\xbaH\x03\xc8\x01\x01R\bmetadata\x12S\n" +
	"\trevisions\x18\x05 \x03(\x0e2\x1e.flowstate.v1.ProtocolRevisionB\x15\xbaH\x12\x92\x01\x0f\b\x01\x10\x10\x18\x01\"\a\x82\x01\x04\x10\x01 \x00R\trevisions\x12N\n" +
	"\x0eendpoint_trust\x18\x06 \x01(\v2\x1f.flowstate.v1.EndpointTrustRuleB\x06\xbaH\x03\xc8\x01\x01R\rendpointTrust\x127\n" +
	"\x05cache\x18\a \x01(\v2\x19.flowstate.v1.CacheBoundsB\x06\xbaH\x03\xc8\x01\x01R\x05cache\"\xeb\x04\n" +
	"\x11ProtectedResource\x12<\n" +
	"\x04name\x18\x01 \x01(\tB(\xbaH%r#\x10\x01\x18\x80\x012\x1c^[A-Za-z0-9][A-Za-z0-9._-]*$R\x04name\x12'\n" +
	"\bresource\x18\x02 \x01(\tB\v\xbaH\br\x06\x18\x80\x10\x88\x01\x01R\bresource\x12B\n" +
	"\bmetadata\x18\x03 \x01(\v2\x1e.flowstate.v1.MetadataLocationB\x06\xbaH\x03\xc8\x01\x01R\bmetadata\x12J\n" +
	"\x15authorization_servers\x18\x04 \x03(\tB\x15\xbaH\x12\x92\x01\x0f\b\x01\x10 \x18\x01\"\ar\x05\x10\x01\x18\x80\x01R\x14authorizationServers\x12,\n" +
	"\x06scopes\x18\x05 \x03(\tB\x14\xbaH\x11\x92\x01\x0e\x10\x80\x01\x18\x01\"\ar\x05\x10\x01\x18\x80\x02R\x06scopes\x12Q\n" +
	"\x1aauthorization_detail_types\x18\x06 \x03(\tB\x13\xbaH\x10\x92\x01\r\x10@\x18\x01\"\ar\x05\x10\x01\x18\x80\x02R\x18authorizationDetailTypes\x12>\n" +
	"\x05proof\x18\a \x01(\x0e2\x1e.flowstate.v1.ProofRequirementB\b\xbaH\x05\x82\x01\x02\x10\x01R\x05proof\x12@\n" +
	"\tassurance\x18\b \x01(\v2\".flowstate.v1.AssuranceRequirementR\tassurance\x12\\\n" +
	"\x11telemetry_privacy\x18\t \x01(\x0e2#.flowstate.v1.TelemetryPrivacyClassB\n" +
	"\xbaH\a\x82\x01\x04\x10\x01 \x00R\x10telemetryPrivacy\"\x97\x01\n" +
	"\x10MetadataLocation\x122\n" +
	"\rdiscovery_url\x18\x01 \x01(\tB\v\xbaH\br\x06\x18\x80\x10\x88\x01\x01H\x00R\fdiscoveryUrl\x12<\n" +
	"\x13static_document_ref\x18\x02 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x80\x02H\x00R\x11staticDocumentRefB\x11\n" +
	"\blocation\x12\x05\xbaH\x02\b\x01\"\xcb\x06\n" +
	"\fGrantProfile\x12<\n" +
	"\x04name\x18\x01 \x01(\tB(\xbaH%r#\x10\x01\x18\x80\x012\x1c^[A-Za-z0-9][A-Za-z0-9._-]*$R\x04name\x129\n" +
	"\x05grant\x18\x02 \x01(\x0e2\x17.flowstate.v1.GrantTypeB\n" +
	"\xbaH\a\x82\x01\x04\x10\x01 \x00R\x05grant\x12S\n" +
	"\trevisions\x18\x03 \x03(\x0e2\x1e.flowstate.v1.ProtocolRevisionB\x15\xbaH\x12\x92\x01\x0f\b\x01\x10\x10\x18\x01\"\a\x82\x01\x04\x10\x01 \x00R\trevisions\x121\n" +
	"\taudiences\x18\x04 \x03(\tB\x13\xbaH\x10\x92\x01\r\x10@\x18\x01\"\ar\x05\x10\x01\x18\x80\x10R\taudiences\x122\n" +
	"\tresources\x18\x05 \x03(\tB\x14\xbaH\x11\x92\x01\x0e\x10@\x18\x01\"\br\x06\x18\x80\x10\x88\x01\x01R\tresources\x12,\n" +
	"\x06scopes\x18\x06 \x03(\tB\x14\xbaH\x11\x92\x01\x0e\x10\x80\x01\x18\x01\"\ar\x05\x10\x01\x18\x80\x02R\x06scopes\x12Q\n" +
	"\x1aauthorization_detail_types\x18\a \x03(\tB\x13\xbaH\x10\x92\x01\r\x10@\x18\x01\"\ar\x05\x10\x01\x18\x80\x02R\x18authorizationDetailTypes\x12'\n" +
	"\tclient_id\x18\b \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x80\x02R\bclientId\x12S\n" +
	" client_authentication_method_ref\x18\t \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x80\x02R\x1dclientAuthenticationMethodRef\x12>\n" +
	"\x05proof\x18\n" +
	" \x01(\x0e2\x1e.flowstate.v1.ProofRequirementB\b\xbaH\x05\x82\x01\x02\x10\x01R\x05proof\x12@\n" +
	"\tassurance\x18\v \x01(\v2\".flowstate.v1.AssuranceRequirementR\tassurance\x12\x1f\n" +
	"\vrequire_par\x18\f \x01(\bR\n" +
	"requirePar\x12\x1f\n" +
	"\vrequire_jar\x18\r \x01(\bR\n" +
	"requireJar\x12C\n" +
	"\bpolicies\x18\x0e \x03(\v2\x1d.flowstate.v1.PolicyReferenceB\b\xbaH\x05\x92\x01\x02\x10 R\bpolicies\"\xca\x01\n" +
	"\x14AssuranceRequirement\x122\n" +
	"\n" +
	"acr_values\x18\x01 \x03(\tB\x13\xbaH\x10\x92\x01\r\x10 \x18\x01\"\ar\x05\x10\x01\x18\x80\x02R\tacrValues\x12V\n" +
	"\"minimum_authentication_age_seconds\x18\x02 \x01(\rB\t\xbaH\x06*\x04\x18\x80\xa3\x05R\x1fminimumAuthenticationAgeSeconds\x12&\n" +
	"\x0frequire_step_up\x18\x03 \x01(\bR\rrequireStepUp\"\xe2\x01\n" +
	"\x11EndpointTrustRule\x12#\n" +
	"\rrequire_https\x18\x01 \x01(\bR\frequireHttps\x12.\n" +
	"\x13require_same_origin\x18\x02 \x01(\bR\x11requireSameOrigin\x12=\n" +
	"\x0fallowed_origins\x18\x03 \x03(\tB\x14\xbaH\x11\x92\x01\x0e\x10@\x18\x01\"\br\x06\x18\x80\x10\x88\x01\x01R\x0eallowedOrigins\x129\n" +
	"\x0epinned_ca_refs\x18\x04 \x03(\tB\x13\xbaH\x10\x92\x01\r\x10\x10\x18\x01\"\ar\x05\x10\x01\x18\x80\x02R\fpinnedCaRefs\"\xf2\x01\n" +
	"\vCacheBounds\x12J\n" +
	"\vmaximum_age\x18\x01 \x01(\v2\x19.google.protobuf.DurationB\x0e\xbaH\v\xaa\x01\b\"\x04\b\x80\xa3\x05*\x00R\n" +
	"maximumAge\x12N\n" +
	"\x0estale_if_error\x18\x02 \x01(\v2\x19.google.protobuf.DurationB\r\xbaH\n" +
	"\xaa\x01\a\"\x03\b\x90\x1c2\x00R\fstaleIfError\x12G\n" +
	"\n" +
	"clock_skew\x18\x03 \x01(\v2\x19.google.protobuf.DurationB\r\xbaH\n" +
	"\xaa\x01\a\"\x03\b\xac\x022\x00R\tclockSkew\"Y\n" +
	"\x0fPolicyReference\x12\x1e\n" +
	"\x04name\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x80\x02R\x04name\x12&\n" +
	"\brevision\x18\x02 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x80\x01R\brevision\"\x90\x01\n" +
	"\x0fSecretReference\x12&\n" +
	"\bprovider\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x80\x01R\bprovider\x12\x1e\n" +
	"\x04name\x18\x02 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x80\x04R\x04name\x12)\n" +
	"\aversion\x18\x03 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x80\x01H\x00R\aversion\x88\x01\x01B\n" +
	"\n" +
	"\b_version*\xd7\x02\n" +
	"\x10ProtocolRevision\x12!\n" +
	"\x1dPROTOCOL_REVISION_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bPROTOCOL_REVISION_OAUTH_2_0\x10\x01\x12\x1f\n" +
	"\x1bPROTOCOL_REVISION_OAUTH_2_1\x10\x02\x12\x1e\n" +
	"\x1aPROTOCOL_REVISION_OIDC_1_0\x10\x03\x12\x1e\n" +
	"\x1aPROTOCOL_REVISION_RFC_8693\x10\x04\x12\x1e\n" +
	"\x1aPROTOCOL_REVISION_RFC_8707\x10\x05\x12\x1e\n" +
	"\x1aPROTOCOL_REVISION_RFC_9126\x10\x06\x12\x1e\n" +
	"\x1aPROTOCOL_REVISION_RFC_9101\x10\a\x12\x1e\n" +
	"\x1aPROTOCOL_REVISION_RFC_9449\x10\b\x12\x1e\n" +
	"\x1aPROTOCOL_REVISION_RFC_9728\x10\t*\xa7\x01\n" +
	"\tGrantType\x12\x1a\n" +
	"\x16GRANT_TYPE_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dGRANT_TYPE_AUTHORIZATION_CODE\x10\x01\x12!\n" +
	"\x1dGRANT_TYPE_CLIENT_CREDENTIALS\x10\x02\x12\x1d\n" +
	"\x19GRANT_TYPE_TOKEN_EXCHANGE\x10\x03\x12\x19\n" +
	"\x15GRANT_TYPE_JWT_BEARER\x10\x04*\x89\x01\n" +
	"\x10ProofRequirement\x12!\n" +
	"\x1dPROOF_REQUIREMENT_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16PROOF_REQUIREMENT_NONE\x10\x01\x12\x1a\n" +
	"\x16PROOF_REQUIREMENT_DPOP\x10\x02\x12\x1a\n" +
	"\x16PROOF_REQUIREMENT_MTLS\x10\x03*\xba\x01\n" +
	"\x15TelemetryPrivacyClass\x12'\n" +
	"#TELEMETRY_PRIVACY_CLASS_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eTELEMETRY_PRIVACY_CLASS_PUBLIC\x10\x01\x12$\n" +
	" TELEMETRY_PRIVACY_CLASS_INTERNAL\x10\x02\x12.\n" +
	"*TELEMETRY_PRIVACY_CLASS_SENSITIVE_METADATA\x10\x03*\x7f\n" +
	"\x0eDelegableField\x12\x1f\n" +
	"\x1bDELEGABLE_FIELD_UNSPECIFIED\x10\x00\x12%\n" +
	"!DELEGABLE_FIELD_TELEMETRY_PRIVACY\x10\x01\x12%\n" +
	"!DELEGABLE_FIELD_METADATA_LOCATION\x10\x02B\xa9\x01\n" +
	"\x10com.flowstate.v1B\n" +
	"OauthProtoP\x01Z8github.com/picatz/flowstate/pkg/flowstate/v1;flowstatev1\xa2\x02\x03FXX\xaa\x02\fFlowstate.V1\xca\x02\fFlowstate\\V1\xe2\x02\x18Flowstate\\V1\\GPBMetadata\xea\x02\rFlowstate::V1b\x06proto3"

var (
	file_flowstate_v1_oauth_proto_rawDescOnce sync.Once
	file_flowstate_v1_oauth_proto_rawDescData []byte
)

func file_flowstate_v1_oauth_proto_rawDescGZIP() []byte {
	file_flowstate_v1_oauth_proto_rawDescOnce.Do(func() {
		file_flowstate_v1_oauth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_flowstate_v1_oauth_proto_rawDesc), len(file_flowstate_v1_oauth_proto_rawDesc)))
	})
	return file_flowstate_v1_oauth_proto_rawDescData
}

var file_flowstate_v1_oauth_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_flowstate_v1_oauth_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_flowstate_v1_oauth_proto_goTypes = []any{
	(ProtocolRevision)(0),        // 0: flowstate.v1.ProtocolRevision
	(GrantType)(0),               // 1: flowstate.v1.GrantType
	(ProofRequirement)(0),        // 2: flowstate.v1.ProofRequirement
	(TelemetryPrivacyClass)(0),   // 3: flowstate.v1.TelemetryPrivacyClass
	(DelegableField)(0),          // 4: flowstate.v1.DelegableField
	(*OAuthConfiguration)(nil),   // 5: flowstate.v1.OAuthConfiguration
	(*AuthorizationServer)(nil),  // 6: flowstate.v1.AuthorizationServer
	(*ProtectedResource)(nil),    // 7: flowstate.v1.ProtectedResource
	(*MetadataLocation)(nil),     // 8: flowstate.v1.MetadataLocation
	(*GrantProfile)(nil),         // 9: flowstate.v1.GrantProfile
	(*AssuranceRequirement)(nil), // 10: flowstate.v1.AssuranceRequirement
	(*EndpointTrustRule)(nil),    // 11: flowstate.v1.EndpointTrustRule
	(*CacheBounds)(nil),          // 12: flowstate.v1.CacheBounds
	(*PolicyReference)(nil),      // 13: flowstate.v1.PolicyReference
	(*SecretReference)(nil),      // 14: flowstate.v1.SecretReference
	(*durationpb.Duration)(nil),  // 15: google.protobuf.Duration
}
var file_flowstate_v1_oauth_proto_depIdxs = []int32{
	6,  // 0: flowstate.v1.OAuthConfiguration.authorization_servers:type_name -> flowstate.v1.AuthorizationServer
	7,  // 1: flowstate.v1.OAuthConfiguration.protected_resources:type_name -> flowstate.v1.ProtectedResource
	9,  // 2: flowstate.v1.OAuthConfiguration.grant_profiles:type_name -> flowstate.v1.GrantProfile
	13, // 3: flowstate.v1.OAuthConfiguration.policies:type_name -> flowstate.v1.PolicyReference
	3,  // 4: flowstate.v1.OAuthConfiguration.telemetry_privacy:type_name -> flowstate.v1.TelemetryPrivacyClass
	4,  // 5: flowstate.v1.OAuthConfiguration.delegable_fields:type_name -> flowstate.v1.DelegableField
	8,  // 6: flowstate.v1.AuthorizationServer.metadata:type_name -> flowstate.v1.MetadataLocation
	0,  // 7: flowstate.v1.AuthorizationServer.revisions:type_name -> flowstate.v1.ProtocolRevision
	11, // 8: flowstate.v1.AuthorizationServer.endpoint_trust:type_name -> flowstate.v1.EndpointTrustRule
	12, // 9: flowstate.v1.AuthorizationServer.cache:type_name -> flowstate.v1.CacheBounds
	8,  // 10: flowstate.v1.ProtectedResource.metadata:type_name -> flowstate.v1.MetadataLocation
	2,  // 11: flowstate.v1.ProtectedResource.proof:type_name -> flowstate.v1.ProofRequirement
	10, // 12: flowstate.v1.ProtectedResource.assurance:type_name -> flowstate.v1.AssuranceRequirement
	3,  // 13: flowstate.v1.ProtectedResource.telemetry_privacy:type_name -> flowstate.v1.TelemetryPrivacyClass
	1,  // 14: flowstate.v1.GrantProfile.grant:type_name -> flowstate.v1.GrantType
	0,  // 15: flowstate.v1.GrantProfile.revisions:type_name -> flowstate.v1.ProtocolRevision
	2,  // 16: flowstate.v1.GrantProfile.proof:type_name -> flowstate.v1.ProofRequirement
	10, // 17: flowstate.v1.GrantProfile.assurance:type_name -> flowstate.v1.AssuranceRequirement
	13, // 18: flowstate.v1.GrantProfile.policies:type_name -> flowstate.v1.PolicyReference
	15, // 19: flowstate.v1.CacheBounds.maximum_age:type_name -> google.protobuf.Duration
	15, // 20: flowstate.v1.CacheBounds.stale_if_error:type_name -> google.protobuf.Duration
	15, // 21: flowstate.v1.CacheBounds.clock_skew:type_name -> google.protobuf.Duration
	22, // [22:22] is the sub-list for method output_type
	22, // [22:22] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_flowstate_v1_oauth_proto_init() }
func file_flowstate_v1_oauth_proto_init() {
	if File_flowstate_v1_oauth_proto != nil {
		return
	}
	file_flowstate_v1_oauth_proto_msgTypes[3].OneofWrappers = []any{
		(*MetadataLocation_DiscoveryUrl)(nil),
		(*MetadataLocation_StaticDocumentRef)(nil),
	}
	file_flowstate_v1_oauth_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_flowstate_v1_oauth_proto_rawDesc), len(file_flowstate_v1_oauth_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_flowstate_v1_oauth_proto_goTypes,
		DependencyIndexes: file_flowstate_v1_oauth_proto_depIdxs,
		EnumInfos:         file_flowstate_v1_oauth_proto_enumTypes,
		MessageInfos:      file_flowstate_v1_oauth_proto_msgTypes,
	}.Build()
	File_flowstate_v1_oauth_proto = out.File
	file_flowstate_v1_oauth_proto_goTypes = nil
	file_flowstate_v1_oauth_proto_depIdxs = nil
}
