// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: flowstate/v1/schema.proto

package flowstatev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_flowstate_v1_schema_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.EnumValueOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50000,
		Name:          "flowstate.v1.test_only",
		Tag:           "varint,50000,opt,name=test_only",
		Filename:      "flowstate/v1/schema.proto",
	},
}

// Extension fields to descriptorpb.EnumValueOptions.
var (
	// test_only marks an enum value the declaring program compiles into its
	// test builds only, and whose released builds refuse at the point of use.
	//
	// A closed enum is supposed to name exactly the choices a build carries, but
	// a build can carry a value for its own hermetic tests that it will not run
	// for a user: an embedded database an SQL plugin's tests exercise the
	// dialect logic against, which a released binary refuses because opening one
	// grants the worker's filesystem to the workflow. Without this option the
	// catalog advertised that value on every surface and `flow validate`
	// accepted it, and the refusal came at dispatch (#1692).
	//
	// The host does not advertise a value marked here and does not accept it: it
	// is left out of the choices every surface lists, and a Flowfile naming it
	// is refused where it is written, saying the value is test-only, rather than
	// at dispatch. The declaring program still refuses it at the point of use,
	// as it did before; this option moves the refusal earlier, it does not
	// replace it.
	//
	// optional bool test_only = 50000;
	E_TestOnly = &file_flowstate_v1_schema_proto_extTypes[0]
)

var File_flowstate_v1_schema_proto protoreflect.FileDescriptor

const file_flowstate_v1_schema_proto_rawDesc = "" +
	"\n" +
	"\x19flowstate/v1/schema.proto\x12\fflowstate.v1\x1a google/protobuf/descriptor.proto:@\n" +
	"\ttest_only\x12!.google.protobuf.EnumValueOptions\x18І\x03 \x01(\bR\btestOnlyB\xaa\x01\n" +
	"\x10com.flowstate.v1B\vSchemaProtoP\x01Z8github.com/picatz/flowstate/pkg/flowstate/v1;flowstatev1\xa2\x02\x03FXX\xaa\x02\fFlowstate.V1\xca\x02\fFlowstate\\V1\xe2\x02\x18Flowstate\\V1\\GPBMetadata\xea\x02\rFlowstate::V1b\x06proto3"

var file_flowstate_v1_schema_proto_goTypes = []any{
	(*descriptorpb.EnumValueOptions)(nil), // 0: google.protobuf.EnumValueOptions
}
var file_flowstate_v1_schema_proto_depIdxs = []int32{
	0, // 0: flowstate.v1.test_only:extendee -> google.protobuf.EnumValueOptions
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_flowstate_v1_schema_proto_init() }
func file_flowstate_v1_schema_proto_init() {
	if File_flowstate_v1_schema_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_flowstate_v1_schema_proto_rawDesc), len(file_flowstate_v1_schema_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_flowstate_v1_schema_proto_goTypes,
		DependencyIndexes: file_flowstate_v1_schema_proto_depIdxs,
		ExtensionInfos:    file_flowstate_v1_schema_proto_extTypes,
	}.Build()
	File_flowstate_v1_schema_proto = out.File
	file_flowstate_v1_schema_proto_goTypes = nil
	file_flowstate_v1_schema_proto_depIdxs = nil
}
