// Package reference contains the source-info-bearing documentation half of the
// issue #1227 pilot. It is separate so static or linked-descriptor-only binding
// does not pull the embedded source descriptor set into a binary.
package reference

import (
	"fmt"
	"io"
	"strings"

	"github.com/picatz/flowstate/internal/schemaifacepilot"
	flowstatev1 "github.com/picatz/flowstate/pkg/flowstate/v1"
	"github.com/picatz/flowstate/pkg/flowstate/v1/protodoc"
	"google.golang.org/protobuf/reflect/protoreflect"
)

// GenerateGet demonstrates descriptor-derived contract documentation while
// leaving spelling and usage copy in the command-owned selection.
func GenerateGet(out io.Writer) error {
	linked := (&flowstatev1.GetRequest{}).ProtoReflect().Descriptor()
	if err := schemaifacepilot.ValidateSelections(linked, schemaifacepilot.GetSelections); err != nil {
		return err
	}

	files, err := protodoc.Files()
	if err != nil {
		return fmt.Errorf("schema interface pilot: source descriptors: %w", err)
	}
	descriptor, err := files.FindDescriptorByName(linked.FullName())
	if err != nil {
		return fmt.Errorf("schema interface pilot: source descriptor %s: %w", linked.FullName(), err)
	}
	sourceMessage, ok := descriptor.(protoreflect.MessageDescriptor)
	if !ok {
		return fmt.Errorf("schema interface pilot: source descriptor %s is %T, not a message", linked.FullName(), descriptor)
	}

	fmt.Fprintln(out, "<!-- Generated by the issue #1227 pilot. Do not edit. -->")
	fmt.Fprintln(out)
	fmt.Fprintln(out, "# `flow get` selected request fields")
	fmt.Fprintln(out)
	if comment, ok := protodoc.CommentOf(sourceMessage); ok {
		fmt.Fprintln(out, comment)
		fmt.Fprintln(out)
	}
	fmt.Fprintln(out, "| CLI input | Request field | Presence | Schema constraints | Schema field prose | Command-owned usage |")
	fmt.Fprintln(out, "|---|---|---|---|---|---|")
	for _, selection := range schemaifacepilot.GetSelections {
		field := linked.Fields().ByName(selection.ProtoName)
		constraints := fieldConstraints(field)
		if len(constraints) == 0 {
			constraints = []string{"—"}
		}
		prose := "—"
		if sourceField := sourceMessage.Fields().ByName(selection.ProtoName); sourceField != nil {
			if comment, ok := protodoc.CommentOf(sourceField); ok {
				prose = comment
			}
		}
		fmt.Fprintf(out, "| %s | `%s` | %s | %s | %s | %s |\n",
			surfaceSpelling(selection), selection.ProtoName, presenceLabel(field),
			strings.Join(constraints, "; "), escapeTable(prose), escapeTable(selection.Usage))
	}
	return nil
}

func presenceLabel(field protoreflect.FieldDescriptor) string {
	switch {
	case flowstatev1.RequiredInput(field):
		return "required"
	case field.HasPresence():
		return "optional; unset stays absent"
	default:
		return "optional; unset uses the scalar zero value"
	}
}

func fieldConstraints(field protoreflect.FieldDescriptor) []string {
	constraints := flowstatev1.FieldConstraints(field)
	rules := flowstatev1.FieldRules(field)
	if rules != nil && rules.GetString().GetUuid() {
		constraints = append(constraints, "UUID")
	}
	return constraints
}

func surfaceSpelling(selection schemaifacepilot.Selection) string {
	if selection.Positional {
		return "`[" + selection.SurfaceName + "]`"
	}
	return "`--" + selection.SurfaceName + "`"
}

func escapeTable(value string) string {
	value = strings.ReplaceAll(value, "|", "\\|")
	return strings.ReplaceAll(value, "\n", " ")
}
