// Package pluginv1 holds the generated messages of the Flowstate plugin
// protocol, flowstate.plugin.v1: the manifest a plugin describes itself with,
// and the requests and responses a worker exchanges with it to resolve secrets
// and execute tasks.
//
// Plugin authors writing in Go should use
// [github.com/picatz/flowstate/pkg/flowstate/v1/plugin/sdk], which builds the
// [PluginManifest] from a plugin's own declarations and serves the protocol;
// the host side, which launches and supervises plugins, is
// [github.com/picatz/flowstate/pkg/flowstate/v1/plugin]. The Connect service
// bindings are in
// [github.com/picatz/flowstate/pkg/flowstate/plugin/v1/pluginv1connect].
// Everything except this file is generated by buf from
// proto/flowstate/plugin/v1/plugin.proto, which is also the protocol reference
// for a plugin written in another language.
package pluginv1
