package sdk

import (
	"context"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protodesc"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/reflect/protoregistry"
	"google.golang.org/protobuf/types/descriptorpb"

	flowstatev1 "github.com/picatz/flowstate/pkg/flowstate/v1"
	examplev1 "github.com/picatz/flowstate/pkg/flowstate/v1/plugin/examples/flowstate-plugin-example/gen/example/v1"
)

// What an author's schema comments buy them, asserted at the seam they actually
// touch: the plugin they declare with [Plugin] (#723, #2148).
//
// The example plugin's schema is borrowed rather than invented because it is the
// one schema in this repository that is a *plugin's*: messages the engine does
// not have, generated by protoc and therefore stripped of their comments, with
// those comments generated beside them by protoc-gen-flowstate-doc. The whole
// path through a launched process is asserted in the plugin package
// (TestExamplePluginShipsItsOwnFieldProse); this is the SDK's own half of it,
// with no subprocess.

// exampleTask is a task declared the way the example plugin declares its own.
func exampleTask() Task {
	return Task{
		Name:    "greet",
		Summary: "Greet someone by name.",
		Input:   &examplev1.GreetInputs{},
		Output:  &examplev1.GreetOutputs{},
		Fn: func(context.Context, map[string]*flowstatev1.Value, *flowstatev1.Scope) (*flowstatev1.Node_Outputs, error) {
			return nil, nil
		},
	}
}

// commentOn reconstructs a serialized descriptor the way a host does and reads
// back how one field is documented, which is the only question the prose
// mechanism is ever asked.
func commentOn(t *testing.T, raw []byte, message, field string) string {
	t.Helper()

	require.NotEmpty(t, raw, "no descriptor travelled, so there is nothing to document")

	var fdp descriptorpb.FileDescriptorProto
	require.NoError(t, proto.Unmarshal(raw, &fdp))

	file, err := protodesc.NewFile(&fdp, protoregistry.GlobalFiles)
	require.NoError(t, err)

	md := file.Messages().ByName(protoreflect.Name(message))
	require.NotNil(t, md, "the descriptor does not define %s", message)

	fd := md.Fields().ByName(protoreflect.Name(field))
	require.NotNil(t, fd, "%s has no field %s", message, field)

	return file.SourceLocations().ByDescriptor(fd).LeadingComments
}

// TestGeneratedProseTravelsInTheTaskDescriptor is the default: a plugin whose
// schema was generated with protoc-gen-flowstate-doc sets nothing, and the
// comments its author wrote end up in the descriptors the manifest was already
// shipping, with no second channel to carry them.
func TestGeneratedProseTravelsInTheTaskDescriptor(t *testing.T) {
	t.Parallel()

	manifest, err := Plugin{Name: "example", Tasks: []Task{exampleTask()}}.manifest()
	require.NoError(t, err)
	require.Len(t, manifest.GetTasks(), 1)
	task := manifest.GetTasks()[0]

	assert.Equal(t, " Name is who to greet.\n",
		commentOn(t, task.GetInputDescriptor(), "GreetInputs", "name"))
	assert.Equal(t, " Message is the assembled greeting.\n",
		commentOn(t, task.GetOutputDescriptor(), "GreetOutputs", "message"))
}

// TestATaskWithNoProseShipsWhatItAlwaysDid is the fallback, which is the
// compatibility promise: not merely that a task described without prose still
// works, but that it sends the same descriptor it always sent, documenting
// nothing.
func TestATaskWithNoProseShipsWhatItAlwaysDid(t *testing.T) {
	t.Parallel()

	manifest, err := exampleTask().manifest(nil)
	require.NoError(t, err)

	assert.Empty(t, commentOn(t, manifest.GetInputDescriptor(), "GreetInputs", "name"),
		"a task described without prose documents nothing, and nothing may be invented for it")
}
