package sdk

import (
	"context"
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protodesc"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/types/descriptorpb"

	flowstatev1 "github.com/picatz/flowstate/pkg/flowstate/v1"
	examplev1 "github.com/picatz/flowstate/pkg/flowstate/v1/plugin/examples/flowstate-plugin-example/gen/example/v1"
)

// What an author's `buf build` artifact buys them, asserted at the seam they
// actually touch: the field they set on [Plugin] (#723).
//
// The example plugin's schema is borrowed rather than invented because it is the
// one schema in this repository that is a *plugin's* — messages the engine does
// not have, generated by protoc and therefore stripped of their comments, with a
// checked-in descriptor set built by the same `make check` line that builds the
// engine's own. The whole path through a launched process is asserted in the
// plugin package (TestExamplePluginShipsItsOwnFieldProse); this is the SDK's own
// half of it, with no subprocess.

// exampleSchemaProseFile is the artifact the example plugin embeds, read from
// disk here because a package main's variables cannot be imported.
const exampleSchemaProseFile = "../examples/flowstate-plugin-example/schema.descriptorset.binpb"

// exampleTask is a task declared the way the example plugin declares its own.
func exampleTask() Task {
	return Task{
		Name:    "greet",
		Summary: "Greet someone by name.",
		Input:   &examplev1.GreetInputs{},
		Output:  &examplev1.GreetOutputs{},
		Fn: func(context.Context, map[string]*flowstatev1.Value, *flowstatev1.Scope) (*flowstatev1.Node_Outputs, error) {
			return nil, nil
		},
	}
}

// commentOn reconstructs a serialized descriptor the way a host does and reads
// back how one field is documented, which is the only question the prose
// mechanism is ever asked.
func commentOn(t *testing.T, raw []byte, message, field string) string {
	t.Helper()

	require.NotEmpty(t, raw, "no descriptor travelled, so there is nothing to document")

	var fdp descriptorpb.FileDescriptorProto
	require.NoError(t, proto.Unmarshal(raw, &fdp))

	file, err := protodesc.NewFile(&fdp, nil)
	require.NoError(t, err)

	md := file.Messages().ByName(protoreflect.Name(message))
	require.NotNil(t, md, "the descriptor does not define %s", message)

	fd := md.Fields().ByName(protoreflect.Name(field))
	require.NotNil(t, fd, "%s has no field %s", message, field)

	return file.SourceLocations().ByDescriptor(fd).LeadingComments
}

// TestSchemaProseTravelsInTheTaskDescriptor is the opt-in direction: the
// comments an author kept with `buf build` end up in the descriptor the manifest
// was already shipping, with no second channel to carry them.
func TestSchemaProseTravelsInTheTaskDescriptor(t *testing.T) {
	t.Parallel()

	raw, err := os.ReadFile(filepath.FromSlash(exampleSchemaProseFile))
	require.NoError(t, err, "the example plugin's descriptor set is missing; `make check` builds it")

	prose, err := flowstatev1.ParseDescriptorProse(raw)
	require.NoError(t, err)

	manifest, err := exampleTask().manifest(prose)
	require.NoError(t, err)

	assert.Equal(t, " Name is who to greet.\n",
		commentOn(t, manifest.GetInputDescriptor(), "GreetInputs", "name"))
	assert.Equal(t, " Message is the assembled greeting.\n",
		commentOn(t, manifest.GetOutputDescriptor(), "GreetOutputs", "message"))
}

// TestATaskWithNoSchemaProseShipsWhatItAlwaysDid is the fallback, which is the
// compatibility promise: not merely that a plugin without the artifact still
// works, but that it sends the same descriptor it always sent, documenting
// nothing.
func TestATaskWithNoSchemaProseShipsWhatItAlwaysDid(t *testing.T) {
	t.Parallel()

	manifest, err := exampleTask().manifest(nil)
	require.NoError(t, err)

	assert.Empty(t, commentOn(t, manifest.GetInputDescriptor(), "GreetInputs", "name"),
		"a plugin that ships no descriptor set documents nothing, and nothing may be invented for it")
}

// TestSchemaProseThatIsNotADescriptorSetIsRefusedAtStartup keeps the one failure
// an author can act on where they can see it: at [Main], naming the field, rather
// than as a plugin that quietly documents nothing.
func TestSchemaProseThatIsNotADescriptorSetIsRefusedAtStartup(t *testing.T) {
	t.Parallel()

	_, err := Plugin{
		Name:        "example",
		SchemaProse: []byte{0x0a, 0x7f}, // a length claiming more bytes than follow it
		Tasks:       []Task{exampleTask()},
	}.manifest()

	require.ErrorContains(t, err, "SchemaProse")
}
