// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: flowstate/auth/v1/trust_policy.proto

package authv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TrustAdmissionCondition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Expression    string                 `protobuf:"bytes,2,opt,name=expression,proto3" json:"expression,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrustAdmissionCondition) Reset() {
	*x = TrustAdmissionCondition{}
	mi := &file_flowstate_auth_v1_trust_policy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrustAdmissionCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrustAdmissionCondition) ProtoMessage() {}

func (x *TrustAdmissionCondition) ProtoReflect() protoreflect.Message {
	mi := &file_flowstate_auth_v1_trust_policy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrustAdmissionCondition.ProtoReflect.Descriptor instead.
func (*TrustAdmissionCondition) Descriptor() ([]byte, []int) {
	return file_flowstate_auth_v1_trust_policy_proto_rawDescGZIP(), []int{0}
}

func (x *TrustAdmissionCondition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TrustAdmissionCondition) GetExpression() string {
	if x != nil {
		return x.Expression
	}
	return ""
}

type TrustAdmissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Issuer        string                 `protobuf:"bytes,1,opt,name=issuer,proto3" json:"issuer,omitempty"`
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Audiences     []string               `protobuf:"bytes,3,rep,name=audiences,proto3" json:"audiences,omitempty"`
	IssuedAtUnix  int64                  `protobuf:"varint,4,opt,name=issued_at_unix,json=issuedAtUnix,proto3" json:"issued_at_unix,omitempty"`
	ExpiresAtUnix int64                  `protobuf:"varint,5,opt,name=expires_at_unix,json=expiresAtUnix,proto3" json:"expires_at_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrustAdmissionRequest) Reset() {
	*x = TrustAdmissionRequest{}
	mi := &file_flowstate_auth_v1_trust_policy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrustAdmissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrustAdmissionRequest) ProtoMessage() {}

func (x *TrustAdmissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flowstate_auth_v1_trust_policy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrustAdmissionRequest.ProtoReflect.Descriptor instead.
func (*TrustAdmissionRequest) Descriptor() ([]byte, []int) {
	return file_flowstate_auth_v1_trust_policy_proto_rawDescGZIP(), []int{1}
}

func (x *TrustAdmissionRequest) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *TrustAdmissionRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *TrustAdmissionRequest) GetAudiences() []string {
	if x != nil {
		return x.Audiences
	}
	return nil
}

func (x *TrustAdmissionRequest) GetIssuedAtUnix() int64 {
	if x != nil {
		return x.IssuedAtUnix
	}
	return 0
}

func (x *TrustAdmissionRequest) GetExpiresAtUnix() int64 {
	if x != nil {
		return x.ExpiresAtUnix
	}
	return 0
}

type TrustAdmissionDeployment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IssuerEntry   string                 `protobuf:"bytes,1,opt,name=issuer_entry,json=issuerEntry,proto3" json:"issuer_entry,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Namespace     string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrustAdmissionDeployment) Reset() {
	*x = TrustAdmissionDeployment{}
	mi := &file_flowstate_auth_v1_trust_policy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrustAdmissionDeployment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrustAdmissionDeployment) ProtoMessage() {}

func (x *TrustAdmissionDeployment) ProtoReflect() protoreflect.Message {
	mi := &file_flowstate_auth_v1_trust_policy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrustAdmissionDeployment.ProtoReflect.Descriptor instead.
func (*TrustAdmissionDeployment) Descriptor() ([]byte, []int) {
	return file_flowstate_auth_v1_trust_policy_proto_rawDescGZIP(), []int{2}
}

func (x *TrustAdmissionDeployment) GetIssuerEntry() string {
	if x != nil {
		return x.IssuerEntry
	}
	return ""
}

func (x *TrustAdmissionDeployment) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *TrustAdmissionDeployment) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

var File_flowstate_auth_v1_trust_policy_proto protoreflect.FileDescriptor

const file_flowstate_auth_v1_trust_policy_proto_rawDesc = "" +
	"\n" +
	"$flowstate/auth/v1/trust_policy.proto\x12\x11flowstate.auth.v1\x1a\x1bbuf/validate/validate.proto\"f\n" +
	"\x17TrustAdmissionCondition\x12\x1e\n" +
	"\x04name\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x80\x01R\x04name\x12+\n" +
	"\n" +
	"expression\x18\x02 \x01(\tB\v\xbaH\br\x06\x10\x01(\x80\x80\x01R\n" +
	"expression\"\xb5\x01\n" +
	"\x15TrustAdmissionRequest\x12\x16\n" +
	"\x06issuer\x18\x01 \x01(\tR\x06issuer\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x1c\n" +
	"\taudiences\x18\x03 \x03(\tR\taudiences\x12$\n" +
	"\x0eissued_at_unix\x18\x04 \x01(\x03R\fissuedAtUnix\x12&\n" +
	"\x0fexpires_at_unix\x18\x05 \x01(\x03R\rexpiresAtUnix\"o\n" +
	"\x18TrustAdmissionDeployment\x12!\n" +
	"\fissuer_entry\x18\x01 \x01(\tR\vissuerEntry\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespaceB\xc9\x01\n" +
	"\x15com.flowstate.auth.v1B\x10TrustPolicyProtoP\x01Z8github.com/picatz/flowstate/pkg/flowstate/auth/v1;authv1\xa2\x02\x03FAX\xaa\x02\x11Flowstate.Auth.V1\xca\x02\x11Flowstate\\Auth\\V1\xe2\x02\x1dFlowstate\\Auth\\V1\\GPBMetadata\xea\x02\x13Flowstate::Auth::V1b\x06proto3"

var (
	file_flowstate_auth_v1_trust_policy_proto_rawDescOnce sync.Once
	file_flowstate_auth_v1_trust_policy_proto_rawDescData []byte
)

func file_flowstate_auth_v1_trust_policy_proto_rawDescGZIP() []byte {
	file_flowstate_auth_v1_trust_policy_proto_rawDescOnce.Do(func() {
		file_flowstate_auth_v1_trust_policy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_flowstate_auth_v1_trust_policy_proto_rawDesc), len(file_flowstate_auth_v1_trust_policy_proto_rawDesc)))
	})
	return file_flowstate_auth_v1_trust_policy_proto_rawDescData
}

var file_flowstate_auth_v1_trust_policy_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_flowstate_auth_v1_trust_policy_proto_goTypes = []any{
	(*TrustAdmissionCondition)(nil),  // 0: flowstate.auth.v1.TrustAdmissionCondition
	(*TrustAdmissionRequest)(nil),    // 1: flowstate.auth.v1.TrustAdmissionRequest
	(*TrustAdmissionDeployment)(nil), // 2: flowstate.auth.v1.TrustAdmissionDeployment
}
var file_flowstate_auth_v1_trust_policy_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_flowstate_auth_v1_trust_policy_proto_init() }
func file_flowstate_auth_v1_trust_policy_proto_init() {
	if File_flowstate_auth_v1_trust_policy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_flowstate_auth_v1_trust_policy_proto_rawDesc), len(file_flowstate_auth_v1_trust_policy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_flowstate_auth_v1_trust_policy_proto_goTypes,
		DependencyIndexes: file_flowstate_auth_v1_trust_policy_proto_depIdxs,
		MessageInfos:      file_flowstate_auth_v1_trust_policy_proto_msgTypes,
	}.Build()
	File_flowstate_auth_v1_trust_policy_proto = out.File
	file_flowstate_auth_v1_trust_policy_proto_goTypes = nil
	file_flowstate_auth_v1_trust_policy_proto_depIdxs = nil
}
