package main

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/picatz/flowstate/internal/commitcheck"
)

// TestAnAnnotationCannotBeForgedByTheMessageItReports pins the escaping: an
// author's line holding a newline and a `::` reaches the runner as one
// warning about that text, never as a second command.
func TestAnAnnotationCannotBeForgedByTheMessageItReports(t *testing.T) {
	t.Parallel()

	var out strings.Builder
	report(&out, []commitcheck.Finding{{
		Rule:    commitcheck.RuleAbsolute,
		Message: "line one\n::error::forged, with 100% certainty",
		Skill:   "x",
	}}, true)

	lines := strings.Split(strings.TrimSpace(out.String()), "\n")
	assert.Len(t, lines, 1, "the message's newline became a second line:\n%s", out.String())
	assert.True(t, strings.HasPrefix(lines[0], "::warning title=commitcheck/absolute::"), lines[0])
	// A `::` inside the data is literal text: the command's grammar reads
	// the data to the end of the line, so only a line break could start a
	// second command, and that is what the encoding removes.
	assert.Contains(t, lines[0], "%0A", "the newline was not encoded")
	assert.Contains(t, lines[0], "100%25", "the percent sign was not encoded")
}

func TestOutsideActionsAFindingIsAPlainLine(t *testing.T) {
	t.Parallel()

	var out strings.Builder
	report(&out, []commitcheck.Finding{{Rule: commitcheck.RuleIssue, Message: "no issue", Skill: "s"}}, false)
	assert.Equal(t, "commitcheck: issue: no issue (see s)\n", out.String())
}

func TestAnOversizedInputIsRefusedRatherThanRead(t *testing.T) {
	t.Parallel()

	_, _, _, _, err := message("", "", "", strings.NewReader(strings.Repeat("x", maxInput+1)))
	assert.ErrorContains(t, err, "over", "a message past the bound was read whole")

	subject, body, where, actor, err := message("", "", "", strings.NewReader("a: b\n\nbody\n"))
	assert.NoError(t, err)
	assert.Equal(t, "a: b", subject)
	assert.Equal(t, "\nbody", body)
	assert.Equal(t, commitcheck.SurfaceCommit, where, "stdin carries whatever the caller has; the stricter surface applies")
	assert.Empty(t, actor, "stdin carries no pull request, so no actor to read one from")
}

// The event payload is the only place [commitcheck.SurfacePullRequest] is
// produced, and CI takes that path on every pull request. Because
// [commitcheck.SurfaceCommit] is the zero value, a change that dropped the
// surface here would compile, leave every other test green, and report the
// footer a forge appends as though its author had written it — which is the
// defect this rule's first head shipped and CI caught.
func TestTheEventPayloadIsReadAsAPullRequestBody(t *testing.T) {
	t.Parallel()

	// A body as the forge stores one: the author's text, then the footer it
	// appended under a rule.
	stored := "Refs #1\n\nVerification: `go test ./...` ok\n\n---\n_Generated by [Claude Code](https://claude.ai/code/session_01EXAMPLEEXAMPLEEXAMPLE03)_"

	path := filepath.Join(t.TempDir(), "event.json")
	payload, err := json.Marshal(map[string]any{
		"pull_request": map[string]any{
			"title": "a: b",
			"body":  stored,
			"user":  map[string]string{"login": "someone"},
		},
	})
	require.NoError(t, err)
	require.NoError(t, os.WriteFile(path, payload, 0o600))

	subject, body, where, actor, err := message("", "", path, nil)
	require.NoError(t, err)
	assert.Equal(t, "a: b", subject)
	assert.Equal(t, stored, body)
	require.Equal(t, commitcheck.SurfacePullRequest, where,
		"a body read back from the forge already carries the footer the forge appended")
	assert.Equal(t, "someone", actor)

	assert.Empty(t, commitcheck.Check(subject, body, where),
		"end to end: the appended footer is not reported against the author who did not write it")
	assert.NotEmpty(t, commitcheck.Check(subject, body, commitcheck.SurfaceCommit),
		"and the same text in a commit message still is, so the surface is what decides")
}

// TestARatchetDateMakesTheCheckStrictOnItsOwn pins both sides of
// [ratchetDate]: nothing in the workflow has to flip a flag, because the
// comparison itself is what #2024 found missing.
func TestARatchetDateMakesTheCheckStrictOnItsOwn(t *testing.T) {
	t.Parallel()

	assert.False(t, ratchetPassed(ratchetDate.Add(-time.Second)), "a moment before the ratchet date is still warning-only")
	assert.True(t, ratchetPassed(ratchetDate), "the ratchet date itself is strict")
	assert.True(t, ratchetPassed(ratchetDate.Add(time.Second)), "a moment after the ratchet date is strict")
}

// TestADependabotPullRequestIsExempt pins the one exemption #2024 added:
// Dependabot's own title and body, which its human maintainer never chose
// and could not have held to these conventions, do not count against it.
func TestADependabotPullRequestIsExempt(t *testing.T) {
	t.Parallel()

	assert.True(t, exempt(commitcheck.SurfacePullRequest, dependabotActor))
	assert.False(t, exempt(commitcheck.SurfacePullRequest, "someone"),
		"a human's pull request still owes the conventions")
	assert.False(t, exempt(commitcheck.SurfaceCommit, dependabotActor),
		"a commit message carries no actor to exempt; only the event payload does")

	path := filepath.Join(t.TempDir(), "event.json")
	payload, err := json.Marshal(map[string]any{
		"pull_request": map[string]any{
			"title": "build(deps): bump x from 1 to 2",
			"body":  "Bumps x from 1 to 2.",
			"user":  map[string]string{"login": dependabotActor},
		},
	})
	require.NoError(t, err)
	require.NoError(t, os.WriteFile(path, payload, 0o600))

	subject, body, where, actor, err := message("", "", path, nil)
	require.NoError(t, err)
	require.Equal(t, dependabotActor, actor)
	assert.NotEmpty(t, commitcheck.Check(subject, body, where),
		"the conventions this exemption skips are real: on its own the check would flag this title and body")
	assert.True(t, exempt(where, actor))
}
