// Package pluginv1connect is the Connect RPC binding of the Flowstate plugin
// protocol: the PluginService, SecretService, and TaskService a plugin process
// serves and a Flowstate worker calls.
//
// Each service has a client constructor, such as [NewTaskServiceClient], and a
// handler constructor, such as [NewTaskServiceHandler], over the messages in
// [github.com/picatz/flowstate/pkg/flowstate/plugin/v1]. Few programs use this
// package directly: a Go plugin is written with
// [github.com/picatz/flowstate/pkg/flowstate/v1/plugin/sdk], which mounts these
// handlers, and the worker side is
// [github.com/picatz/flowstate/pkg/flowstate/v1/plugin]. Everything except this
// file is generated by buf from proto/flowstate/plugin/v1/plugin.proto.
package pluginv1connect
