// Command genguard is a Claude Code PreToolUse hook on Edit and Write
// (#482): it refuses edits to generated files, naming the source to edit
// and the command that regenerates. Editing a generated file is never what
// anyone means; the edit either vanishes at the next regeneration or fails
// a git-diff-clean pin in CI, and both cost a round trip this refusal ends
// at the keystroke.
//
// Wired in .claude/settings.json as:
//
//	bash "${CLAUDE_PROJECT_DIR}/.claude/hooks/run-hook.sh" genguard
//
// The generated surfaces, each with its source and regenerate command:
//
//	*.pb.go                            <- proto/flowstate/v1/*.proto, buf generate
//	protodoc/*.doc.pb.go               <- the schema's comments; buf generate
//	…-example/gen/**/*.pb.go           <- that plugin's schema; its own buf generate
//	docs/reference/                    <- the registry, cobra tree, MCP table; make docs
//	cmd/flow/internal/reference/mirror <- docs/DSL.md and examples/; go generate
//
// Only the mirror under cmd/flow/internal/reference is generated;
// reference.go, reference_test.go and sync.go beside it are source and stay
// editable.
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/picatz/flowstate/tools/hooks/internal/hook"
)

func main() {
	in, err := hook.Read(os.Stdin)
	if err != nil {
		return // lenient: unrecognized input allows
	}
	rel := projectRel(in.FilePath(), in.CWD)
	if rel == "" {
		return
	}
	if reason := generated(rel); reason != "" {
		hook.Deny(reason)
	}
}

// projectRel resolves the edited path to a project-relative slash path, or
// "" when it cannot ("" allows: a path outside the project is not ours to
// guard, and a path this cannot resolve is not one it can match rules
// against honestly).
func projectRel(path, cwd string) string {
	if path == "" {
		return ""
	}
	root := os.Getenv("CLAUDE_PROJECT_DIR")
	if root == "" {
		root = cwd
	}
	if root == "" {
		return ""
	}
	if !filepath.IsAbs(path) {
		base := cwd
		if base == "" {
			base = root
		}
		path = filepath.Join(base, path)
	}
	rel, err := filepath.Rel(root, path)
	if err != nil || rel == ".." || strings.HasPrefix(rel, ".."+string(filepath.Separator)) {
		return ""
	}
	return filepath.ToSlash(rel)
}

// generated returns the refusal message for a project-relative path that is
// generated, or "" when the path is source.
func generated(rel string) string {
	switch {
	// The example plugin's generated code, which comes from that plugin's own
	// schema and buf.gen.yaml rather than the engine's. Its own case ahead of
	// the general one, because the source to edit and the command that
	// regenerates are both different, and a refusal naming the wrong .proto
	// is a refusal that sends somebody to the wrong file.
	case strings.HasPrefix(rel, examplePlugin+"gen/") && strings.HasSuffix(rel, ".pb.go"):
		return fmt.Sprintf("%s is generated from the example plugin's own schema. Edit %sproto/example/v1/example.proto, then run `go tool -modfile=tools/external/go.mod buf generate %sproto --template %sbuf.gen.yaml -o %s` and commit the regenerated files.", rel, examplePlugin, examplePlugin, examplePlugin, examplePlugin)

	// The schema's comments, which protoc-gen-flowstate-doc writes (#2147).
	case strings.HasPrefix(rel, "pkg/flowstate/v1/protodoc/") && strings.HasSuffix(rel, ".doc.pb.go"):
		return fmt.Sprintf("%s holds the schema's comments, generated from them. Edit the comment above the declaration in the .proto under proto/ that declares it, then run `go tool -modfile=tools/external/go.mod buf generate` and commit the regenerated files.", rel)

	case strings.HasSuffix(rel, ".pb.go"):
		return fmt.Sprintf("%s is generated by buf from the schema. Edit the .proto under proto/flowstate/v1/ that declares this type, then run `go tool -modfile=tools/external/go.mod buf generate` and commit the regenerated files.", rel)

	case rel == "docs/reference" || strings.HasPrefix(rel, "docs/reference/"):
		return fmt.Sprintf("%s is generated: docs/reference/ is derived from the task registry, the cobra tree, the MCP tool table and the env-var table. Edit the source instead (cmd/flow/internal/docsgen/envvars.go holds the env-var prose; task and command prose live on the registry and cobra definitions), then run `make docs` (go run ./cmd/flow docs generate).", rel)

	case rel == "cmd/flow/internal/reference/mirror" || strings.HasPrefix(rel, "cmd/flow/internal/reference/mirror/"):
		return fmt.Sprintf("%s is a generated mirror. Edit docs/DSL.md (or the example workflow it mirrors under examples/), then run `go generate ./cmd/flow/internal/reference`.", rel)

	}
	return ""
}

// examplePlugin is the example plugin's directory, which is its own buf module.
const examplePlugin = "pkg/flowstate/v1/plugin/examples/flowstate-plugin-example/"
