// Command genguard is a Claude Code PreToolUse hook on Edit and Write
// (#482): it refuses edits to generated files, naming the source to edit
// and the command that regenerates. Editing a generated file is never what
// anyone means; the edit either vanishes at the next regeneration or fails
// a git-diff-clean pin in CI, and both cost a round trip this refusal ends
// at the keystroke.
//
// Wired in .claude/settings.json as:
//
//	go -C "${CLAUDE_PROJECT_DIR}" run ./tools/hooks/genguard
//
// The generated surfaces, each with its source and regenerate command:
//
//	*.pb.go                            <- proto/flowstate/v1/*.proto, buf generate
//	docs/reference/                    <- the registry, cobra tree, MCP table; make docs
//	cmd/flow/internal/reference/mirror <- docs/DSL.md and examples/; go generate
//	pkg/flowstate/v1/protodoc/*.binpb  <- the schema; buf build
//	…-example/schema.descriptorset.binpb <- that plugin's schema; buf build
//
// Only the mirror under cmd/flow/internal/reference is generated;
// reference.go, reference_test.go and sync.go beside it are source and stay
// editable.
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/picatz/flowstate/tools/hooks/internal/hook"
)

func main() {
	in, err := hook.Read(os.Stdin)
	if err != nil {
		return // lenient: unrecognized input allows
	}
	rel := projectRel(in.FilePath(), in.CWD)
	if rel == "" {
		return
	}
	if reason := generated(rel); reason != "" {
		hook.Deny(reason)
	}
}

// projectRel resolves the edited path to a project-relative slash path, or
// "" when it cannot ("" allows: a path outside the project is not ours to
// guard, and a path this cannot resolve is not one it can match rules
// against honestly).
func projectRel(path, cwd string) string {
	if path == "" {
		return ""
	}
	root := os.Getenv("CLAUDE_PROJECT_DIR")
	if root == "" {
		root = cwd
	}
	if root == "" {
		return ""
	}
	if !filepath.IsAbs(path) {
		base := cwd
		if base == "" {
			base = root
		}
		path = filepath.Join(base, path)
	}
	rel, err := filepath.Rel(root, path)
	if err != nil || rel == ".." || strings.HasPrefix(rel, ".."+string(filepath.Separator)) {
		return ""
	}
	return filepath.ToSlash(rel)
}

// generated returns the refusal message for a project-relative path that is
// generated, or "" when the path is source.
func generated(rel string) string {
	switch {
	case strings.HasSuffix(rel, ".pb.go"):
		return fmt.Sprintf("%s is generated by buf from the schema. Edit the .proto under proto/flowstate/v1/ that declares this type, then run `go run github.com/bufbuild/buf/cmd/buf@v1.72.0 generate` and commit the regenerated files.", rel)

	case rel == "docs/reference" || strings.HasPrefix(rel, "docs/reference/"):
		return fmt.Sprintf("%s is generated: docs/reference/ is derived from the task registry, the cobra tree, the MCP tool table and the env-var table. Edit the source instead (cmd/flow/internal/docsgen/envvars.go holds the env-var prose; task and command prose live on the registry and cobra definitions), then run `make docs` (go run ./cmd/flow docs generate).", rel)

	case rel == "cmd/flow/internal/reference/mirror" || strings.HasPrefix(rel, "cmd/flow/internal/reference/mirror/"):
		return fmt.Sprintf("%s is a generated mirror. Edit docs/DSL.md (or the example workflow it mirrors under examples/), then run `go generate ./cmd/flow/internal/reference`.", rel)

	// The example plugin's own descriptor set, which is the same artifact for
	// a plugin's schema rather than the engine's: it is what carries that
	// plugin's field comments to an editor (#723). Its own case rather than a
	// widened one above, because the source to edit and the command that
	// rebuilds it are both different, and a refusal naming the wrong .proto is
	// a refusal that sends somebody to the wrong file.
	case rel == "pkg/flowstate/v1/plugin/examples/flowstate-plugin-example/schema.descriptorset.binpb":
		return fmt.Sprintf("%s is the descriptor set `buf build` writes so the example plugin's own comments travel with its task descriptors. Edit proto/example/v1/example.proto beside it, then run `go run github.com/bufbuild/buf/cmd/buf@v1.72.0 build --exclude-imports -o pkg/flowstate/v1/plugin/examples/flowstate-plugin-example/schema.descriptorset.binpb pkg/flowstate/v1/plugin/examples/flowstate-plugin-example/proto`.", rel)

	case strings.HasPrefix(rel, "pkg/flowstate/v1/protodoc/") && strings.HasSuffix(rel, ".binpb"):
		return fmt.Sprintf("%s is the descriptor set `buf build` writes so the schema's comments travel with it. Edit the .proto under proto/flowstate/v1/ that declares the type, then run `go run github.com/bufbuild/buf/cmd/buf@v1.72.0 build --exclude-imports -o pkg/flowstate/v1/protodoc/flowstate.descriptorset.binpb`.", rel)
	}
	return ""
}
