name: http-json-via-cel
steps:
  - id: web
    http:
      method: GET
      url: https://httpbin.org/json
  - id: title
    cel:
      libs: [json]
      expr: json_parse(web.body)['slideshow']['title']
