name: cel-demo
steps:
  - id: greet
    echo:
      message: hello
  - id: modify
    cel:
      expr: "regex.replace(vars.greeting.upperAscii(), 'HELLO', 'HI')"
      libs: [strings, regex]
      vars:
        greeting: ${steps.greet.result}

